// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CdRsColumns holds the columns for the "cd_rs" table.
	CdRsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "device_code", Type: field.TypeString},
		{Name: "device_type", Type: field.TypeString},
		{Name: "last_data_value", Type: field.TypeInt64},
		{Name: "data_value", Type: field.TypeInt64},
		{Name: "last_data_code", Type: field.TypeString},
		{Name: "data_code", Type: field.TypeString},
		{Name: "last_data_time", Type: field.TypeTime},
		{Name: "data_time", Type: field.TypeTime},
		{Name: "ploy_id", Type: field.TypeString},
		{Name: "rule_id", Type: field.TypeString},
		{Name: "value", Type: field.TypeInt64},
		{Name: "unit_fee", Type: field.TypeInt64},
		{Name: "fee", Type: field.TypeInt64},
		{Name: "pos_code", Type: field.TypeString},
		{Name: "project", Type: field.TypeString},
		{Name: "remark", Type: field.TypeString, Default: ""},
	}
	// CdRsTable holds the schema information for the "cd_rs" table.
	CdRsTable = &schema.Table{
		Name:       "cd_rs",
		Columns:    CdRsColumns,
		PrimaryKey: []*schema.Column{CdRsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "cdr_device_code",
				Unique:  false,
				Columns: []*schema.Column{CdRsColumns[1]},
			},
			{
				Name:    "cdr_device_type",
				Unique:  false,
				Columns: []*schema.Column{CdRsColumns[2]},
			},
			{
				Name:    "cdr_data_code",
				Unique:  false,
				Columns: []*schema.Column{CdRsColumns[6]},
			},
			{
				Name:    "cdr_data_time",
				Unique:  false,
				Columns: []*schema.Column{CdRsColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CdRsTable,
	}
)

func init() {
}
