// Code generated by ent, DO NOT EDIT.

package top

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the top type in the database.
	Label = "top"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldDeviceCode holds the string denoting the device_code field in the database.
	FieldDeviceCode = "device_code"
	// FieldDeviceType holds the string denoting the device_type field in the database.
	FieldDeviceType = "device_type"
	// FieldPosCode holds the string denoting the pos_code field in the database.
	FieldPosCode = "pos_code"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldTop holds the string denoting the top field in the database.
	FieldTop = "top"
	// FieldStock holds the string denoting the stock field in the database.
	FieldStock = "stock"
	// FieldIncr holds the string denoting the incr field in the database.
	FieldIncr = "incr"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldChargeTime holds the string denoting the charge_time field in the database.
	FieldChargeTime = "charge_time"
	// FieldAlarm holds the string denoting the alarm field in the database.
	FieldAlarm = "alarm"
	// FieldAlarmTime holds the string denoting the alarm_time field in the database.
	FieldAlarmTime = "alarm_time"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldMemo holds the string denoting the memo field in the database.
	FieldMemo = "memo"
	// FieldIsDel holds the string denoting the is_del field in the database.
	FieldIsDel = "is_del"
	// Table holds the table name of the top in the database.
	Table = "device_top"
)

// Columns holds all SQL columns for top fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldCode,
	FieldDeviceCode,
	FieldDeviceType,
	FieldPosCode,
	FieldProject,
	FieldOwner,
	FieldTop,
	FieldStock,
	FieldIncr,
	FieldAmount,
	FieldUnitPrice,
	FieldChargeTime,
	FieldAlarm,
	FieldAlarmTime,
	FieldStatus,
	FieldEndTime,
	FieldMemo,
	FieldIsDel,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultCode holds the default value on creation for the "code" field.
	DefaultCode func() string
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DeviceCodeValidator is a validator for the "device_code" field. It is called by the builders before save.
	DeviceCodeValidator func(string) error
	// DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	DeviceTypeValidator func(string) error
	// PosCodeValidator is a validator for the "pos_code" field. It is called by the builders before save.
	PosCodeValidator func(string) error
	// ProjectValidator is a validator for the "project" field. It is called by the builders before save.
	ProjectValidator func(string) error
	// DefaultTop holds the default value on creation for the "top" field.
	DefaultTop int64
	// DefaultStock holds the default value on creation for the "stock" field.
	DefaultStock int64
	// DefaultIncr holds the default value on creation for the "incr" field.
	DefaultIncr int64
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount int64
	// DefaultUnitPrice holds the default value on creation for the "unit_price" field.
	DefaultUnitPrice int64
	// DefaultChargeTime holds the default value on creation for the "charge_time" field.
	DefaultChargeTime func() time.Time
	// DefaultAlarm holds the default value on creation for the "alarm" field.
	DefaultAlarm int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
	// DefaultIsDel holds the default value on creation for the "is_del" field.
	DefaultIsDel int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Top queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByDeviceCode orders the results by the device_code field.
func ByDeviceCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceCode, opts...).ToFunc()
}

// ByDeviceType orders the results by the device_type field.
func ByDeviceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceType, opts...).ToFunc()
}

// ByPosCode orders the results by the pos_code field.
func ByPosCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosCode, opts...).ToFunc()
}

// ByProject orders the results by the project field.
func ByProject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProject, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByTop orders the results by the top field.
func ByTop(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTop, opts...).ToFunc()
}

// ByStock orders the results by the stock field.
func ByStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStock, opts...).ToFunc()
}

// ByIncr orders the results by the incr field.
func ByIncr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncr, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByChargeTime orders the results by the charge_time field.
func ByChargeTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargeTime, opts...).ToFunc()
}

// ByAlarm orders the results by the alarm field.
func ByAlarm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarm, opts...).ToFunc()
}

// ByAlarmTime orders the results by the alarm_time field.
func ByAlarmTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarmTime, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByMemo orders the results by the memo field.
func ByMemo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemo, opts...).ToFunc()
}

// ByIsDel orders the results by the is_del field.
func ByIsDel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDel, opts...).ToFunc()
}
