// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/twiglab/h2o/dbcli/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/h2o/dbcli/ent/alarm"
	"github.com/twiglab/h2o/dbcli/ent/device"
	"github.com/twiglab/h2o/dbcli/ent/nhrecord"
	"github.com/twiglab/h2o/dbcli/ent/top"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Alarm is the client for interacting with the Alarm builders.
	Alarm *AlarmClient
	// Device is the client for interacting with the Device builders.
	Device *DeviceClient
	// NhRecord is the client for interacting with the NhRecord builders.
	NhRecord *NhRecordClient
	// Top is the client for interacting with the Top builders.
	Top *TopClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Alarm = NewAlarmClient(c.config)
	c.Device = NewDeviceClient(c.config)
	c.NhRecord = NewNhRecordClient(c.config)
	c.Top = NewTopClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Alarm:    NewAlarmClient(cfg),
		Device:   NewDeviceClient(cfg),
		NhRecord: NewNhRecordClient(cfg),
		Top:      NewTopClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Alarm:    NewAlarmClient(cfg),
		Device:   NewDeviceClient(cfg),
		NhRecord: NewNhRecordClient(cfg),
		Top:      NewTopClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Alarm.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Alarm.Use(hooks...)
	c.Device.Use(hooks...)
	c.NhRecord.Use(hooks...)
	c.Top.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Alarm.Intercept(interceptors...)
	c.Device.Intercept(interceptors...)
	c.NhRecord.Intercept(interceptors...)
	c.Top.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AlarmMutation:
		return c.Alarm.mutate(ctx, m)
	case *DeviceMutation:
		return c.Device.mutate(ctx, m)
	case *NhRecordMutation:
		return c.NhRecord.mutate(ctx, m)
	case *TopMutation:
		return c.Top.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AlarmClient is a client for the Alarm schema.
type AlarmClient struct {
	config
}

// NewAlarmClient returns a client for the Alarm from the given config.
func NewAlarmClient(c config) *AlarmClient {
	return &AlarmClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `alarm.Hooks(f(g(h())))`.
func (c *AlarmClient) Use(hooks ...Hook) {
	c.hooks.Alarm = append(c.hooks.Alarm, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `alarm.Intercept(f(g(h())))`.
func (c *AlarmClient) Intercept(interceptors ...Interceptor) {
	c.inters.Alarm = append(c.inters.Alarm, interceptors...)
}

// Create returns a builder for creating a Alarm entity.
func (c *AlarmClient) Create() *AlarmCreate {
	mutation := newAlarmMutation(c.config, OpCreate)
	return &AlarmCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Alarm entities.
func (c *AlarmClient) CreateBulk(builders ...*AlarmCreate) *AlarmCreateBulk {
	return &AlarmCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AlarmClient) MapCreateBulk(slice any, setFunc func(*AlarmCreate, int)) *AlarmCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AlarmCreateBulk{err: fmt.Errorf("calling to AlarmClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AlarmCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AlarmCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Alarm.
func (c *AlarmClient) Update() *AlarmUpdate {
	mutation := newAlarmMutation(c.config, OpUpdate)
	return &AlarmUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AlarmClient) UpdateOne(_m *Alarm) *AlarmUpdateOne {
	mutation := newAlarmMutation(c.config, OpUpdateOne, withAlarm(_m))
	return &AlarmUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AlarmClient) UpdateOneID(id string) *AlarmUpdateOne {
	mutation := newAlarmMutation(c.config, OpUpdateOne, withAlarmID(id))
	return &AlarmUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Alarm.
func (c *AlarmClient) Delete() *AlarmDelete {
	mutation := newAlarmMutation(c.config, OpDelete)
	return &AlarmDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AlarmClient) DeleteOne(_m *Alarm) *AlarmDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AlarmClient) DeleteOneID(id string) *AlarmDeleteOne {
	builder := c.Delete().Where(alarm.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AlarmDeleteOne{builder}
}

// Query returns a query builder for Alarm.
func (c *AlarmClient) Query() *AlarmQuery {
	return &AlarmQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAlarm},
		inters: c.Interceptors(),
	}
}

// Get returns a Alarm entity by its id.
func (c *AlarmClient) Get(ctx context.Context, id string) (*Alarm, error) {
	return c.Query().Where(alarm.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AlarmClient) GetX(ctx context.Context, id string) *Alarm {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AlarmClient) Hooks() []Hook {
	return c.hooks.Alarm
}

// Interceptors returns the client interceptors.
func (c *AlarmClient) Interceptors() []Interceptor {
	return c.inters.Alarm
}

func (c *AlarmClient) mutate(ctx context.Context, m *AlarmMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AlarmCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AlarmUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AlarmUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AlarmDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Alarm mutation op: %q", m.Op())
	}
}

// DeviceClient is a client for the Device schema.
type DeviceClient struct {
	config
}

// NewDeviceClient returns a client for the Device from the given config.
func NewDeviceClient(c config) *DeviceClient {
	return &DeviceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `device.Hooks(f(g(h())))`.
func (c *DeviceClient) Use(hooks ...Hook) {
	c.hooks.Device = append(c.hooks.Device, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `device.Intercept(f(g(h())))`.
func (c *DeviceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Device = append(c.inters.Device, interceptors...)
}

// Create returns a builder for creating a Device entity.
func (c *DeviceClient) Create() *DeviceCreate {
	mutation := newDeviceMutation(c.config, OpCreate)
	return &DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Device entities.
func (c *DeviceClient) CreateBulk(builders ...*DeviceCreate) *DeviceCreateBulk {
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceClient) MapCreateBulk(slice any, setFunc func(*DeviceCreate, int)) *DeviceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceCreateBulk{err: fmt.Errorf("calling to DeviceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Device.
func (c *DeviceClient) Update() *DeviceUpdate {
	mutation := newDeviceMutation(c.config, OpUpdate)
	return &DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceClient) UpdateOne(_m *Device) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDevice(_m))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceClient) UpdateOneID(id string) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDeviceID(id))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Device.
func (c *DeviceClient) Delete() *DeviceDelete {
	mutation := newDeviceMutation(c.config, OpDelete)
	return &DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceClient) DeleteOne(_m *Device) *DeviceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceClient) DeleteOneID(id string) *DeviceDeleteOne {
	builder := c.Delete().Where(device.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceDeleteOne{builder}
}

// Query returns a query builder for Device.
func (c *DeviceClient) Query() *DeviceQuery {
	return &DeviceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDevice},
		inters: c.Interceptors(),
	}
}

// Get returns a Device entity by its id.
func (c *DeviceClient) Get(ctx context.Context, id string) (*Device, error) {
	return c.Query().Where(device.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceClient) GetX(ctx context.Context, id string) *Device {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceClient) Hooks() []Hook {
	return c.hooks.Device
}

// Interceptors returns the client interceptors.
func (c *DeviceClient) Interceptors() []Interceptor {
	return c.inters.Device
}

func (c *DeviceClient) mutate(ctx context.Context, m *DeviceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Device mutation op: %q", m.Op())
	}
}

// NhRecordClient is a client for the NhRecord schema.
type NhRecordClient struct {
	config
}

// NewNhRecordClient returns a client for the NhRecord from the given config.
func NewNhRecordClient(c config) *NhRecordClient {
	return &NhRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `nhrecord.Hooks(f(g(h())))`.
func (c *NhRecordClient) Use(hooks ...Hook) {
	c.hooks.NhRecord = append(c.hooks.NhRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `nhrecord.Intercept(f(g(h())))`.
func (c *NhRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.NhRecord = append(c.inters.NhRecord, interceptors...)
}

// Create returns a builder for creating a NhRecord entity.
func (c *NhRecordClient) Create() *NhRecordCreate {
	mutation := newNhRecordMutation(c.config, OpCreate)
	return &NhRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NhRecord entities.
func (c *NhRecordClient) CreateBulk(builders ...*NhRecordCreate) *NhRecordCreateBulk {
	return &NhRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NhRecordClient) MapCreateBulk(slice any, setFunc func(*NhRecordCreate, int)) *NhRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NhRecordCreateBulk{err: fmt.Errorf("calling to NhRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NhRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NhRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NhRecord.
func (c *NhRecordClient) Update() *NhRecordUpdate {
	mutation := newNhRecordMutation(c.config, OpUpdate)
	return &NhRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NhRecordClient) UpdateOne(_m *NhRecord) *NhRecordUpdateOne {
	mutation := newNhRecordMutation(c.config, OpUpdateOne, withNhRecord(_m))
	return &NhRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NhRecordClient) UpdateOneID(id string) *NhRecordUpdateOne {
	mutation := newNhRecordMutation(c.config, OpUpdateOne, withNhRecordID(id))
	return &NhRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NhRecord.
func (c *NhRecordClient) Delete() *NhRecordDelete {
	mutation := newNhRecordMutation(c.config, OpDelete)
	return &NhRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NhRecordClient) DeleteOne(_m *NhRecord) *NhRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NhRecordClient) DeleteOneID(id string) *NhRecordDeleteOne {
	builder := c.Delete().Where(nhrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NhRecordDeleteOne{builder}
}

// Query returns a query builder for NhRecord.
func (c *NhRecordClient) Query() *NhRecordQuery {
	return &NhRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNhRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a NhRecord entity by its id.
func (c *NhRecordClient) Get(ctx context.Context, id string) (*NhRecord, error) {
	return c.Query().Where(nhrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NhRecordClient) GetX(ctx context.Context, id string) *NhRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NhRecordClient) Hooks() []Hook {
	return c.hooks.NhRecord
}

// Interceptors returns the client interceptors.
func (c *NhRecordClient) Interceptors() []Interceptor {
	return c.inters.NhRecord
}

func (c *NhRecordClient) mutate(ctx context.Context, m *NhRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NhRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NhRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NhRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NhRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NhRecord mutation op: %q", m.Op())
	}
}

// TopClient is a client for the Top schema.
type TopClient struct {
	config
}

// NewTopClient returns a client for the Top from the given config.
func NewTopClient(c config) *TopClient {
	return &TopClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `top.Hooks(f(g(h())))`.
func (c *TopClient) Use(hooks ...Hook) {
	c.hooks.Top = append(c.hooks.Top, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `top.Intercept(f(g(h())))`.
func (c *TopClient) Intercept(interceptors ...Interceptor) {
	c.inters.Top = append(c.inters.Top, interceptors...)
}

// Create returns a builder for creating a Top entity.
func (c *TopClient) Create() *TopCreate {
	mutation := newTopMutation(c.config, OpCreate)
	return &TopCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Top entities.
func (c *TopClient) CreateBulk(builders ...*TopCreate) *TopCreateBulk {
	return &TopCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TopClient) MapCreateBulk(slice any, setFunc func(*TopCreate, int)) *TopCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TopCreateBulk{err: fmt.Errorf("calling to TopClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TopCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TopCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Top.
func (c *TopClient) Update() *TopUpdate {
	mutation := newTopMutation(c.config, OpUpdate)
	return &TopUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TopClient) UpdateOne(_m *Top) *TopUpdateOne {
	mutation := newTopMutation(c.config, OpUpdateOne, withTop(_m))
	return &TopUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TopClient) UpdateOneID(id string) *TopUpdateOne {
	mutation := newTopMutation(c.config, OpUpdateOne, withTopID(id))
	return &TopUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Top.
func (c *TopClient) Delete() *TopDelete {
	mutation := newTopMutation(c.config, OpDelete)
	return &TopDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TopClient) DeleteOne(_m *Top) *TopDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TopClient) DeleteOneID(id string) *TopDeleteOne {
	builder := c.Delete().Where(top.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TopDeleteOne{builder}
}

// Query returns a query builder for Top.
func (c *TopClient) Query() *TopQuery {
	return &TopQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTop},
		inters: c.Interceptors(),
	}
}

// Get returns a Top entity by its id.
func (c *TopClient) Get(ctx context.Context, id string) (*Top, error) {
	return c.Query().Where(top.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TopClient) GetX(ctx context.Context, id string) *Top {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TopClient) Hooks() []Hook {
	return c.hooks.Top
}

// Interceptors returns the client interceptors.
func (c *TopClient) Interceptors() []Interceptor {
	return c.inters.Top
}

func (c *TopClient) mutate(ctx context.Context, m *TopMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TopCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TopUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TopUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TopDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Top mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Alarm, Device, NhRecord, Top []ent.Hook
	}
	inters struct {
		Alarm, Device, NhRecord, Top []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
