// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/twiglab/h2o/dbcli/ent/alarm"
	"github.com/twiglab/h2o/dbcli/ent/device"
	"github.com/twiglab/h2o/dbcli/ent/nhrecord"
	"github.com/twiglab/h2o/dbcli/ent/top"
	"github.com/twiglab/h2o/dbcli/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alarmFields := schema.Alarm{}.Fields()
	_ = alarmFields
	// alarmDescTopID is the schema descriptor for top_id field.
	alarmDescTopID := alarmFields[1].Descriptor()
	// alarm.TopIDValidator is a validator for the "top_id" field. It is called by the builders before save.
	alarm.TopIDValidator = alarmDescTopID.Validators[0].(func(string) error)
	// alarmDescTopCode is the schema descriptor for top_code field.
	alarmDescTopCode := alarmFields[2].Descriptor()
	// alarm.TopCodeValidator is a validator for the "top_code" field. It is called by the builders before save.
	alarm.TopCodeValidator = alarmDescTopCode.Validators[0].(func(string) error)
	// alarmDescAlarm1 is the schema descriptor for alarm_1 field.
	alarmDescAlarm1 := alarmFields[3].Descriptor()
	// alarm.DefaultAlarm1 holds the default value on creation for the alarm_1 field.
	alarm.DefaultAlarm1 = alarmDescAlarm1.Default.(int)
	// alarmDescAlarmStock1 is the schema descriptor for alarm_stock_1 field.
	alarmDescAlarmStock1 := alarmFields[5].Descriptor()
	// alarm.DefaultAlarmStock1 holds the default value on creation for the alarm_stock_1 field.
	alarm.DefaultAlarmStock1 = alarmDescAlarmStock1.Default.(int64)
	// alarmDescAlarm2 is the schema descriptor for alarm_2 field.
	alarmDescAlarm2 := alarmFields[6].Descriptor()
	// alarm.DefaultAlarm2 holds the default value on creation for the alarm_2 field.
	alarm.DefaultAlarm2 = alarmDescAlarm2.Default.(int)
	// alarmDescAlarmStock2 is the schema descriptor for alarm_stock_2 field.
	alarmDescAlarmStock2 := alarmFields[8].Descriptor()
	// alarm.DefaultAlarmStock2 holds the default value on creation for the alarm_stock_2 field.
	alarm.DefaultAlarmStock2 = alarmDescAlarmStock2.Default.(int64)
	// alarmDescAlarm3 is the schema descriptor for alarm_3 field.
	alarmDescAlarm3 := alarmFields[9].Descriptor()
	// alarm.DefaultAlarm3 holds the default value on creation for the alarm_3 field.
	alarm.DefaultAlarm3 = alarmDescAlarm3.Default.(int)
	// alarmDescAlarmStock3 is the schema descriptor for alarm_stock_3 field.
	alarmDescAlarmStock3 := alarmFields[11].Descriptor()
	// alarm.DefaultAlarmStock3 holds the default value on creation for the alarm_stock_3 field.
	alarm.DefaultAlarmStock3 = alarmDescAlarmStock3.Default.(int64)
	// alarmDescID is the schema descriptor for id field.
	alarmDescID := alarmFields[0].Descriptor()
	// alarm.DefaultID holds the default value on creation for the id field.
	alarm.DefaultID = alarmDescID.Default.(func() string)
	// alarm.IDValidator is a validator for the "id" field. It is called by the builders before save.
	alarm.IDValidator = alarmDescID.Validators[0].(func(string) error)
	deviceMixin := schema.Device{}.Mixin()
	deviceMixinFields0 := deviceMixin[0].Fields()
	_ = deviceMixinFields0
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescCreateTime is the schema descriptor for create_time field.
	deviceDescCreateTime := deviceMixinFields0[0].Descriptor()
	// device.DefaultCreateTime holds the default value on creation for the create_time field.
	device.DefaultCreateTime = deviceDescCreateTime.Default.(func() time.Time)
	// deviceDescUpdateTime is the schema descriptor for update_time field.
	deviceDescUpdateTime := deviceMixinFields0[1].Descriptor()
	// device.DefaultUpdateTime holds the default value on creation for the update_time field.
	device.DefaultUpdateTime = deviceDescUpdateTime.Default.(func() time.Time)
	// device.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	device.UpdateDefaultUpdateTime = deviceDescUpdateTime.UpdateDefault.(func() time.Time)
	// deviceDescDeviceCode is the schema descriptor for device_code field.
	deviceDescDeviceCode := deviceFields[1].Descriptor()
	// device.DeviceCodeValidator is a validator for the "device_code" field. It is called by the builders before save.
	device.DeviceCodeValidator = deviceDescDeviceCode.Validators[0].(func(string) error)
	// deviceDescDeviceType is the schema descriptor for device_type field.
	deviceDescDeviceType := deviceFields[2].Descriptor()
	// device.DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	device.DeviceTypeValidator = deviceDescDeviceType.Validators[0].(func(string) error)
	// deviceDescRate is the schema descriptor for rate field.
	deviceDescRate := deviceFields[6].Descriptor()
	// device.DefaultRate holds the default value on creation for the rate field.
	device.DefaultRate = deviceDescRate.Default.(int)
	// deviceDescProject is the schema descriptor for project field.
	deviceDescProject := deviceFields[7].Descriptor()
	// device.ProjectValidator is a validator for the "project" field. It is called by the builders before save.
	device.ProjectValidator = deviceDescProject.Validators[0].(func(string) error)
	// deviceDescStatus is the schema descriptor for status field.
	deviceDescStatus := deviceFields[11].Descriptor()
	// device.DefaultStatus holds the default value on creation for the status field.
	device.DefaultStatus = deviceDescStatus.Default.(int)
	// deviceDescIsDel is the schema descriptor for is_del field.
	deviceDescIsDel := deviceFields[13].Descriptor()
	// device.DefaultIsDel holds the default value on creation for the is_del field.
	device.DefaultIsDel = deviceDescIsDel.Default.(int)
	// deviceDescID is the schema descriptor for id field.
	deviceDescID := deviceFields[0].Descriptor()
	// device.DefaultID holds the default value on creation for the id field.
	device.DefaultID = deviceDescID.Default.(func() string)
	// device.IDValidator is a validator for the "id" field. It is called by the builders before save.
	device.IDValidator = deviceDescID.Validators[0].(func(string) error)
	nhrecordMixin := schema.NhRecord{}.Mixin()
	nhrecordMixinFields0 := nhrecordMixin[0].Fields()
	_ = nhrecordMixinFields0
	nhrecordFields := schema.NhRecord{}.Fields()
	_ = nhrecordFields
	// nhrecordDescCreateTime is the schema descriptor for create_time field.
	nhrecordDescCreateTime := nhrecordMixinFields0[0].Descriptor()
	// nhrecord.DefaultCreateTime holds the default value on creation for the create_time field.
	nhrecord.DefaultCreateTime = nhrecordDescCreateTime.Default.(func() time.Time)
	// nhrecordDescUpdateTime is the schema descriptor for update_time field.
	nhrecordDescUpdateTime := nhrecordMixinFields0[1].Descriptor()
	// nhrecord.DefaultUpdateTime holds the default value on creation for the update_time field.
	nhrecord.DefaultUpdateTime = nhrecordDescUpdateTime.Default.(func() time.Time)
	// nhrecord.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	nhrecord.UpdateDefaultUpdateTime = nhrecordDescUpdateTime.UpdateDefault.(func() time.Time)
	// nhrecordDescDeviceCode is the schema descriptor for device_code field.
	nhrecordDescDeviceCode := nhrecordFields[2].Descriptor()
	// nhrecord.DeviceCodeValidator is a validator for the "device_code" field. It is called by the builders before save.
	nhrecord.DeviceCodeValidator = nhrecordDescDeviceCode.Validators[0].(func(string) error)
	// nhrecordDescDeviceType is the schema descriptor for device_type field.
	nhrecordDescDeviceType := nhrecordFields[3].Descriptor()
	// nhrecord.DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	nhrecord.DeviceTypeValidator = nhrecordDescDeviceType.Validators[0].(func(string) error)
	// nhrecordDescDataValue is the schema descriptor for data_value field.
	nhrecordDescDataValue := nhrecordFields[4].Descriptor()
	// nhrecord.DefaultDataValue holds the default value on creation for the data_value field.
	nhrecord.DefaultDataValue = nhrecordDescDataValue.Default.(int64)
	// nhrecordDescDataCode is the schema descriptor for data_code field.
	nhrecordDescDataCode := nhrecordFields[5].Descriptor()
	// nhrecord.DataCodeValidator is a validator for the "data_code" field. It is called by the builders before save.
	nhrecord.DataCodeValidator = nhrecordDescDataCode.Validators[0].(func(string) error)
	// nhrecordDescDataTs is the schema descriptor for data_ts field.
	nhrecordDescDataTs := nhrecordFields[7].Descriptor()
	// nhrecord.DataTsValidator is a validator for the "data_ts" field. It is called by the builders before save.
	nhrecord.DataTsValidator = nhrecordDescDataTs.Validators[0].(func(string) error)
	// nhrecordDescProject is the schema descriptor for project field.
	nhrecordDescProject := nhrecordFields[8].Descriptor()
	// nhrecord.ProjectValidator is a validator for the "project" field. It is called by the builders before save.
	nhrecord.ProjectValidator = nhrecordDescProject.Validators[0].(func(string) error)
	// nhrecordDescID is the schema descriptor for id field.
	nhrecordDescID := nhrecordFields[0].Descriptor()
	// nhrecord.DefaultID holds the default value on creation for the id field.
	nhrecord.DefaultID = nhrecordDescID.Default.(func() string)
	// nhrecord.IDValidator is a validator for the "id" field. It is called by the builders before save.
	nhrecord.IDValidator = nhrecordDescID.Validators[0].(func(string) error)
	topMixin := schema.Top{}.Mixin()
	topMixinFields0 := topMixin[0].Fields()
	_ = topMixinFields0
	topFields := schema.Top{}.Fields()
	_ = topFields
	// topDescCreateTime is the schema descriptor for create_time field.
	topDescCreateTime := topMixinFields0[0].Descriptor()
	// top.DefaultCreateTime holds the default value on creation for the create_time field.
	top.DefaultCreateTime = topDescCreateTime.Default.(func() time.Time)
	// topDescUpdateTime is the schema descriptor for update_time field.
	topDescUpdateTime := topMixinFields0[1].Descriptor()
	// top.DefaultUpdateTime holds the default value on creation for the update_time field.
	top.DefaultUpdateTime = topDescUpdateTime.Default.(func() time.Time)
	// top.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	top.UpdateDefaultUpdateTime = topDescUpdateTime.UpdateDefault.(func() time.Time)
	// topDescCode is the schema descriptor for code field.
	topDescCode := topFields[1].Descriptor()
	// top.DefaultCode holds the default value on creation for the code field.
	top.DefaultCode = topDescCode.Default.(func() string)
	// top.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	top.CodeValidator = topDescCode.Validators[0].(func(string) error)
	// topDescDeviceCode is the schema descriptor for device_code field.
	topDescDeviceCode := topFields[3].Descriptor()
	// top.DeviceCodeValidator is a validator for the "device_code" field. It is called by the builders before save.
	top.DeviceCodeValidator = topDescDeviceCode.Validators[0].(func(string) error)
	// topDescDeviceType is the schema descriptor for device_type field.
	topDescDeviceType := topFields[4].Descriptor()
	// top.DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	top.DeviceTypeValidator = topDescDeviceType.Validators[0].(func(string) error)
	// topDescPosCode is the schema descriptor for pos_code field.
	topDescPosCode := topFields[5].Descriptor()
	// top.PosCodeValidator is a validator for the "pos_code" field. It is called by the builders before save.
	top.PosCodeValidator = topDescPosCode.Validators[0].(func(string) error)
	// topDescProject is the schema descriptor for project field.
	topDescProject := topFields[6].Descriptor()
	// top.ProjectValidator is a validator for the "project" field. It is called by the builders before save.
	top.ProjectValidator = topDescProject.Validators[0].(func(string) error)
	// topDescTop is the schema descriptor for top field.
	topDescTop := topFields[8].Descriptor()
	// top.DefaultTop holds the default value on creation for the top field.
	top.DefaultTop = topDescTop.Default.(int64)
	// topDescStock is the schema descriptor for stock field.
	topDescStock := topFields[9].Descriptor()
	// top.DefaultStock holds the default value on creation for the stock field.
	top.DefaultStock = topDescStock.Default.(int64)
	// topDescIncr is the schema descriptor for incr field.
	topDescIncr := topFields[10].Descriptor()
	// top.DefaultIncr holds the default value on creation for the incr field.
	top.DefaultIncr = topDescIncr.Default.(int64)
	// topDescAmount is the schema descriptor for amount field.
	topDescAmount := topFields[11].Descriptor()
	// top.DefaultAmount holds the default value on creation for the amount field.
	top.DefaultAmount = topDescAmount.Default.(int64)
	// topDescUnitPrice is the schema descriptor for unit_price field.
	topDescUnitPrice := topFields[12].Descriptor()
	// top.DefaultUnitPrice holds the default value on creation for the unit_price field.
	top.DefaultUnitPrice = topDescUnitPrice.Default.(int64)
	// topDescChargeTime is the schema descriptor for charge_time field.
	topDescChargeTime := topFields[13].Descriptor()
	// top.DefaultChargeTime holds the default value on creation for the charge_time field.
	top.DefaultChargeTime = topDescChargeTime.Default.(func() time.Time)
	// topDescAlarm is the schema descriptor for alarm field.
	topDescAlarm := topFields[14].Descriptor()
	// top.DefaultAlarm holds the default value on creation for the alarm field.
	top.DefaultAlarm = topDescAlarm.Default.(int)
	// topDescAlarmStock is the schema descriptor for alarm_stock field.
	topDescAlarmStock := topFields[16].Descriptor()
	// top.DefaultAlarmStock holds the default value on creation for the alarm_stock field.
	top.DefaultAlarmStock = topDescAlarmStock.Default.(int64)
	// topDescStatus is the schema descriptor for status field.
	topDescStatus := topFields[17].Descriptor()
	// top.DefaultStatus holds the default value on creation for the status field.
	top.DefaultStatus = topDescStatus.Default.(int)
	// topDescEndStock is the schema descriptor for end_stock field.
	topDescEndStock := topFields[19].Descriptor()
	// top.DefaultEndStock holds the default value on creation for the end_stock field.
	top.DefaultEndStock = topDescEndStock.Default.(int64)
	// topDescIsDel is the schema descriptor for is_del field.
	topDescIsDel := topFields[21].Descriptor()
	// top.DefaultIsDel holds the default value on creation for the is_del field.
	top.DefaultIsDel = topDescIsDel.Default.(int)
	// topDescID is the schema descriptor for id field.
	topDescID := topFields[0].Descriptor()
	// top.DefaultID holds the default value on creation for the id field.
	top.DefaultID = topDescID.Default.(func() string)
	// top.IDValidator is a validator for the "id" field. It is called by the builders before save.
	top.IDValidator = topDescID.Validators[0].(func(string) error)
}
