scalar Time
scalar Int64

type NhRecord {
  id: ID!

  deviceSn   : String!

  deviceCode : String!
  deviceType : String!

  deviceName : String!

  dataValue  : Int64!

  dataCode   : String!
  dataTime   : Time!
  dataTs     : String!

  posCode    : String!
  project    : String!
  owner      : String!
}

input RecordPageIn {
  posCode    : String!
  project    : String!
  deviceCode : String!

  start      : String!
  end        : String!

  last       : String!
  pageSize   : Int!
}

type NhRecordBeforeOut {
  result     : [NhRecord!]!

  deviceCode : String!
  dataTs     : String!
  pageSize   : Int!
}

input NhRecordBeforeIn {
  deviceCode : String!
  dataTs     : String!
  pageSize   : Int!
}

type Query {
  NhRecordBefore(input: NhRecordBeforeIn!) : NhRecordBeforeOut
}

