// Code generated by ent, DO NOT EDIT.

package electy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/h2o/vigil/orm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldUpdateTime, v))
}

// PCode applies equality check predicate on the "p_code" field. It's identical to PCodeEQ.
func PCode(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldPCode, v))
}

// DeviceSn applies equality check predicate on the "device_sn" field. It's identical to DeviceSnEQ.
func DeviceSn(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDeviceSn, v))
}

// DeviceCode applies equality check predicate on the "device_code" field. It's identical to DeviceCodeEQ.
func DeviceCode(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDeviceCode, v))
}

// DeviceType applies equality check predicate on the "device_type" field. It's identical to DeviceTypeEQ.
func DeviceType(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDeviceType, v))
}

// DeviceName applies equality check predicate on the "device_name" field. It's identical to DeviceNameEQ.
func DeviceName(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDeviceName, v))
}

// DataValue applies equality check predicate on the "data_value" field. It's identical to DataValueEQ.
func DataValue(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDataValue, v))
}

// XDataValue applies equality check predicate on the "x_data_value" field. It's identical to XDataValueEQ.
func XDataValue(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldXDataValue, v))
}

// Factor applies equality check predicate on the "factor" field. It's identical to FactorEQ.
func Factor(v int) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldFactor, v))
}

// DataCode applies equality check predicate on the "data_code" field. It's identical to DataCodeEQ.
func DataCode(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDataCode, v))
}

// DataTime applies equality check predicate on the "data_time" field. It's identical to DataTimeEQ.
func DataTime(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDataTime, v))
}

// DataTs applies equality check predicate on the "data_ts" field. It's identical to DataTsEQ.
func DataTs(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDataTs, v))
}

// PosCode applies equality check predicate on the "pos_code" field. It's identical to PosCodeEQ.
func PosCode(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldPosCode, v))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldProject, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldUpdateTime, v))
}

// PCodeEQ applies the EQ predicate on the "p_code" field.
func PCodeEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldPCode, v))
}

// PCodeNEQ applies the NEQ predicate on the "p_code" field.
func PCodeNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldPCode, v))
}

// PCodeIn applies the In predicate on the "p_code" field.
func PCodeIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldPCode, vs...))
}

// PCodeNotIn applies the NotIn predicate on the "p_code" field.
func PCodeNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldPCode, vs...))
}

// PCodeGT applies the GT predicate on the "p_code" field.
func PCodeGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldPCode, v))
}

// PCodeGTE applies the GTE predicate on the "p_code" field.
func PCodeGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldPCode, v))
}

// PCodeLT applies the LT predicate on the "p_code" field.
func PCodeLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldPCode, v))
}

// PCodeLTE applies the LTE predicate on the "p_code" field.
func PCodeLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldPCode, v))
}

// PCodeContains applies the Contains predicate on the "p_code" field.
func PCodeContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldPCode, v))
}

// PCodeHasPrefix applies the HasPrefix predicate on the "p_code" field.
func PCodeHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldPCode, v))
}

// PCodeHasSuffix applies the HasSuffix predicate on the "p_code" field.
func PCodeHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldPCode, v))
}

// PCodeEqualFold applies the EqualFold predicate on the "p_code" field.
func PCodeEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldPCode, v))
}

// PCodeContainsFold applies the ContainsFold predicate on the "p_code" field.
func PCodeContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldPCode, v))
}

// DeviceSnEQ applies the EQ predicate on the "device_sn" field.
func DeviceSnEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDeviceSn, v))
}

// DeviceSnNEQ applies the NEQ predicate on the "device_sn" field.
func DeviceSnNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldDeviceSn, v))
}

// DeviceSnIn applies the In predicate on the "device_sn" field.
func DeviceSnIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldDeviceSn, vs...))
}

// DeviceSnNotIn applies the NotIn predicate on the "device_sn" field.
func DeviceSnNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldDeviceSn, vs...))
}

// DeviceSnGT applies the GT predicate on the "device_sn" field.
func DeviceSnGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldDeviceSn, v))
}

// DeviceSnGTE applies the GTE predicate on the "device_sn" field.
func DeviceSnGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldDeviceSn, v))
}

// DeviceSnLT applies the LT predicate on the "device_sn" field.
func DeviceSnLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldDeviceSn, v))
}

// DeviceSnLTE applies the LTE predicate on the "device_sn" field.
func DeviceSnLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldDeviceSn, v))
}

// DeviceSnContains applies the Contains predicate on the "device_sn" field.
func DeviceSnContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldDeviceSn, v))
}

// DeviceSnHasPrefix applies the HasPrefix predicate on the "device_sn" field.
func DeviceSnHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldDeviceSn, v))
}

// DeviceSnHasSuffix applies the HasSuffix predicate on the "device_sn" field.
func DeviceSnHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldDeviceSn, v))
}

// DeviceSnIsNil applies the IsNil predicate on the "device_sn" field.
func DeviceSnIsNil() predicate.Electy {
	return predicate.Electy(sql.FieldIsNull(FieldDeviceSn))
}

// DeviceSnNotNil applies the NotNil predicate on the "device_sn" field.
func DeviceSnNotNil() predicate.Electy {
	return predicate.Electy(sql.FieldNotNull(FieldDeviceSn))
}

// DeviceSnEqualFold applies the EqualFold predicate on the "device_sn" field.
func DeviceSnEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldDeviceSn, v))
}

// DeviceSnContainsFold applies the ContainsFold predicate on the "device_sn" field.
func DeviceSnContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldDeviceSn, v))
}

// DeviceCodeEQ applies the EQ predicate on the "device_code" field.
func DeviceCodeEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDeviceCode, v))
}

// DeviceCodeNEQ applies the NEQ predicate on the "device_code" field.
func DeviceCodeNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldDeviceCode, v))
}

// DeviceCodeIn applies the In predicate on the "device_code" field.
func DeviceCodeIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldDeviceCode, vs...))
}

// DeviceCodeNotIn applies the NotIn predicate on the "device_code" field.
func DeviceCodeNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldDeviceCode, vs...))
}

// DeviceCodeGT applies the GT predicate on the "device_code" field.
func DeviceCodeGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldDeviceCode, v))
}

// DeviceCodeGTE applies the GTE predicate on the "device_code" field.
func DeviceCodeGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldDeviceCode, v))
}

// DeviceCodeLT applies the LT predicate on the "device_code" field.
func DeviceCodeLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldDeviceCode, v))
}

// DeviceCodeLTE applies the LTE predicate on the "device_code" field.
func DeviceCodeLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldDeviceCode, v))
}

// DeviceCodeContains applies the Contains predicate on the "device_code" field.
func DeviceCodeContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldDeviceCode, v))
}

// DeviceCodeHasPrefix applies the HasPrefix predicate on the "device_code" field.
func DeviceCodeHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldDeviceCode, v))
}

// DeviceCodeHasSuffix applies the HasSuffix predicate on the "device_code" field.
func DeviceCodeHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldDeviceCode, v))
}

// DeviceCodeEqualFold applies the EqualFold predicate on the "device_code" field.
func DeviceCodeEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldDeviceCode, v))
}

// DeviceCodeContainsFold applies the ContainsFold predicate on the "device_code" field.
func DeviceCodeContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldDeviceCode, v))
}

// DeviceTypeEQ applies the EQ predicate on the "device_type" field.
func DeviceTypeEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDeviceType, v))
}

// DeviceTypeNEQ applies the NEQ predicate on the "device_type" field.
func DeviceTypeNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldDeviceType, v))
}

// DeviceTypeIn applies the In predicate on the "device_type" field.
func DeviceTypeIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldDeviceType, vs...))
}

// DeviceTypeNotIn applies the NotIn predicate on the "device_type" field.
func DeviceTypeNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldDeviceType, vs...))
}

// DeviceTypeGT applies the GT predicate on the "device_type" field.
func DeviceTypeGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldDeviceType, v))
}

// DeviceTypeGTE applies the GTE predicate on the "device_type" field.
func DeviceTypeGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldDeviceType, v))
}

// DeviceTypeLT applies the LT predicate on the "device_type" field.
func DeviceTypeLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldDeviceType, v))
}

// DeviceTypeLTE applies the LTE predicate on the "device_type" field.
func DeviceTypeLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldDeviceType, v))
}

// DeviceTypeContains applies the Contains predicate on the "device_type" field.
func DeviceTypeContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldDeviceType, v))
}

// DeviceTypeHasPrefix applies the HasPrefix predicate on the "device_type" field.
func DeviceTypeHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldDeviceType, v))
}

// DeviceTypeHasSuffix applies the HasSuffix predicate on the "device_type" field.
func DeviceTypeHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldDeviceType, v))
}

// DeviceTypeEqualFold applies the EqualFold predicate on the "device_type" field.
func DeviceTypeEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldDeviceType, v))
}

// DeviceTypeContainsFold applies the ContainsFold predicate on the "device_type" field.
func DeviceTypeContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldDeviceType, v))
}

// DeviceNameEQ applies the EQ predicate on the "device_name" field.
func DeviceNameEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDeviceName, v))
}

// DeviceNameNEQ applies the NEQ predicate on the "device_name" field.
func DeviceNameNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldDeviceName, v))
}

// DeviceNameIn applies the In predicate on the "device_name" field.
func DeviceNameIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldDeviceName, vs...))
}

// DeviceNameNotIn applies the NotIn predicate on the "device_name" field.
func DeviceNameNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldDeviceName, vs...))
}

// DeviceNameGT applies the GT predicate on the "device_name" field.
func DeviceNameGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldDeviceName, v))
}

// DeviceNameGTE applies the GTE predicate on the "device_name" field.
func DeviceNameGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldDeviceName, v))
}

// DeviceNameLT applies the LT predicate on the "device_name" field.
func DeviceNameLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldDeviceName, v))
}

// DeviceNameLTE applies the LTE predicate on the "device_name" field.
func DeviceNameLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldDeviceName, v))
}

// DeviceNameContains applies the Contains predicate on the "device_name" field.
func DeviceNameContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldDeviceName, v))
}

// DeviceNameHasPrefix applies the HasPrefix predicate on the "device_name" field.
func DeviceNameHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldDeviceName, v))
}

// DeviceNameHasSuffix applies the HasSuffix predicate on the "device_name" field.
func DeviceNameHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldDeviceName, v))
}

// DeviceNameIsNil applies the IsNil predicate on the "device_name" field.
func DeviceNameIsNil() predicate.Electy {
	return predicate.Electy(sql.FieldIsNull(FieldDeviceName))
}

// DeviceNameNotNil applies the NotNil predicate on the "device_name" field.
func DeviceNameNotNil() predicate.Electy {
	return predicate.Electy(sql.FieldNotNull(FieldDeviceName))
}

// DeviceNameEqualFold applies the EqualFold predicate on the "device_name" field.
func DeviceNameEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldDeviceName, v))
}

// DeviceNameContainsFold applies the ContainsFold predicate on the "device_name" field.
func DeviceNameContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldDeviceName, v))
}

// DataValueEQ applies the EQ predicate on the "data_value" field.
func DataValueEQ(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDataValue, v))
}

// DataValueNEQ applies the NEQ predicate on the "data_value" field.
func DataValueNEQ(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldDataValue, v))
}

// DataValueIn applies the In predicate on the "data_value" field.
func DataValueIn(vs ...int64) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldDataValue, vs...))
}

// DataValueNotIn applies the NotIn predicate on the "data_value" field.
func DataValueNotIn(vs ...int64) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldDataValue, vs...))
}

// DataValueGT applies the GT predicate on the "data_value" field.
func DataValueGT(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldDataValue, v))
}

// DataValueGTE applies the GTE predicate on the "data_value" field.
func DataValueGTE(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldDataValue, v))
}

// DataValueLT applies the LT predicate on the "data_value" field.
func DataValueLT(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldDataValue, v))
}

// DataValueLTE applies the LTE predicate on the "data_value" field.
func DataValueLTE(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldDataValue, v))
}

// XDataValueEQ applies the EQ predicate on the "x_data_value" field.
func XDataValueEQ(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldXDataValue, v))
}

// XDataValueNEQ applies the NEQ predicate on the "x_data_value" field.
func XDataValueNEQ(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldXDataValue, v))
}

// XDataValueIn applies the In predicate on the "x_data_value" field.
func XDataValueIn(vs ...int64) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldXDataValue, vs...))
}

// XDataValueNotIn applies the NotIn predicate on the "x_data_value" field.
func XDataValueNotIn(vs ...int64) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldXDataValue, vs...))
}

// XDataValueGT applies the GT predicate on the "x_data_value" field.
func XDataValueGT(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldXDataValue, v))
}

// XDataValueGTE applies the GTE predicate on the "x_data_value" field.
func XDataValueGTE(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldXDataValue, v))
}

// XDataValueLT applies the LT predicate on the "x_data_value" field.
func XDataValueLT(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldXDataValue, v))
}

// XDataValueLTE applies the LTE predicate on the "x_data_value" field.
func XDataValueLTE(v int64) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldXDataValue, v))
}

// FactorEQ applies the EQ predicate on the "factor" field.
func FactorEQ(v int) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldFactor, v))
}

// FactorNEQ applies the NEQ predicate on the "factor" field.
func FactorNEQ(v int) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldFactor, v))
}

// FactorIn applies the In predicate on the "factor" field.
func FactorIn(vs ...int) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldFactor, vs...))
}

// FactorNotIn applies the NotIn predicate on the "factor" field.
func FactorNotIn(vs ...int) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldFactor, vs...))
}

// FactorGT applies the GT predicate on the "factor" field.
func FactorGT(v int) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldFactor, v))
}

// FactorGTE applies the GTE predicate on the "factor" field.
func FactorGTE(v int) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldFactor, v))
}

// FactorLT applies the LT predicate on the "factor" field.
func FactorLT(v int) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldFactor, v))
}

// FactorLTE applies the LTE predicate on the "factor" field.
func FactorLTE(v int) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldFactor, v))
}

// DataCodeEQ applies the EQ predicate on the "data_code" field.
func DataCodeEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDataCode, v))
}

// DataCodeNEQ applies the NEQ predicate on the "data_code" field.
func DataCodeNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldDataCode, v))
}

// DataCodeIn applies the In predicate on the "data_code" field.
func DataCodeIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldDataCode, vs...))
}

// DataCodeNotIn applies the NotIn predicate on the "data_code" field.
func DataCodeNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldDataCode, vs...))
}

// DataCodeGT applies the GT predicate on the "data_code" field.
func DataCodeGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldDataCode, v))
}

// DataCodeGTE applies the GTE predicate on the "data_code" field.
func DataCodeGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldDataCode, v))
}

// DataCodeLT applies the LT predicate on the "data_code" field.
func DataCodeLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldDataCode, v))
}

// DataCodeLTE applies the LTE predicate on the "data_code" field.
func DataCodeLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldDataCode, v))
}

// DataCodeContains applies the Contains predicate on the "data_code" field.
func DataCodeContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldDataCode, v))
}

// DataCodeHasPrefix applies the HasPrefix predicate on the "data_code" field.
func DataCodeHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldDataCode, v))
}

// DataCodeHasSuffix applies the HasSuffix predicate on the "data_code" field.
func DataCodeHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldDataCode, v))
}

// DataCodeEqualFold applies the EqualFold predicate on the "data_code" field.
func DataCodeEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldDataCode, v))
}

// DataCodeContainsFold applies the ContainsFold predicate on the "data_code" field.
func DataCodeContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldDataCode, v))
}

// DataTimeEQ applies the EQ predicate on the "data_time" field.
func DataTimeEQ(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDataTime, v))
}

// DataTimeNEQ applies the NEQ predicate on the "data_time" field.
func DataTimeNEQ(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldDataTime, v))
}

// DataTimeIn applies the In predicate on the "data_time" field.
func DataTimeIn(vs ...time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldDataTime, vs...))
}

// DataTimeNotIn applies the NotIn predicate on the "data_time" field.
func DataTimeNotIn(vs ...time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldDataTime, vs...))
}

// DataTimeGT applies the GT predicate on the "data_time" field.
func DataTimeGT(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldDataTime, v))
}

// DataTimeGTE applies the GTE predicate on the "data_time" field.
func DataTimeGTE(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldDataTime, v))
}

// DataTimeLT applies the LT predicate on the "data_time" field.
func DataTimeLT(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldDataTime, v))
}

// DataTimeLTE applies the LTE predicate on the "data_time" field.
func DataTimeLTE(v time.Time) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldDataTime, v))
}

// DataTsEQ applies the EQ predicate on the "data_ts" field.
func DataTsEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldDataTs, v))
}

// DataTsNEQ applies the NEQ predicate on the "data_ts" field.
func DataTsNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldDataTs, v))
}

// DataTsIn applies the In predicate on the "data_ts" field.
func DataTsIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldDataTs, vs...))
}

// DataTsNotIn applies the NotIn predicate on the "data_ts" field.
func DataTsNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldDataTs, vs...))
}

// DataTsGT applies the GT predicate on the "data_ts" field.
func DataTsGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldDataTs, v))
}

// DataTsGTE applies the GTE predicate on the "data_ts" field.
func DataTsGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldDataTs, v))
}

// DataTsLT applies the LT predicate on the "data_ts" field.
func DataTsLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldDataTs, v))
}

// DataTsLTE applies the LTE predicate on the "data_ts" field.
func DataTsLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldDataTs, v))
}

// DataTsContains applies the Contains predicate on the "data_ts" field.
func DataTsContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldDataTs, v))
}

// DataTsHasPrefix applies the HasPrefix predicate on the "data_ts" field.
func DataTsHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldDataTs, v))
}

// DataTsHasSuffix applies the HasSuffix predicate on the "data_ts" field.
func DataTsHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldDataTs, v))
}

// DataTsEqualFold applies the EqualFold predicate on the "data_ts" field.
func DataTsEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldDataTs, v))
}

// DataTsContainsFold applies the ContainsFold predicate on the "data_ts" field.
func DataTsContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldDataTs, v))
}

// PosCodeEQ applies the EQ predicate on the "pos_code" field.
func PosCodeEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldPosCode, v))
}

// PosCodeNEQ applies the NEQ predicate on the "pos_code" field.
func PosCodeNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldPosCode, v))
}

// PosCodeIn applies the In predicate on the "pos_code" field.
func PosCodeIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldPosCode, vs...))
}

// PosCodeNotIn applies the NotIn predicate on the "pos_code" field.
func PosCodeNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldPosCode, vs...))
}

// PosCodeGT applies the GT predicate on the "pos_code" field.
func PosCodeGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldPosCode, v))
}

// PosCodeGTE applies the GTE predicate on the "pos_code" field.
func PosCodeGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldPosCode, v))
}

// PosCodeLT applies the LT predicate on the "pos_code" field.
func PosCodeLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldPosCode, v))
}

// PosCodeLTE applies the LTE predicate on the "pos_code" field.
func PosCodeLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldPosCode, v))
}

// PosCodeContains applies the Contains predicate on the "pos_code" field.
func PosCodeContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldPosCode, v))
}

// PosCodeHasPrefix applies the HasPrefix predicate on the "pos_code" field.
func PosCodeHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldPosCode, v))
}

// PosCodeHasSuffix applies the HasSuffix predicate on the "pos_code" field.
func PosCodeHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldPosCode, v))
}

// PosCodeEqualFold applies the EqualFold predicate on the "pos_code" field.
func PosCodeEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldPosCode, v))
}

// PosCodeContainsFold applies the ContainsFold predicate on the "pos_code" field.
func PosCodeContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldPosCode, v))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.Electy {
	return predicate.Electy(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.Electy {
	return predicate.Electy(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.Electy {
	return predicate.Electy(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.Electy {
	return predicate.Electy(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.Electy {
	return predicate.Electy(sql.FieldContainsFold(FieldProject, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Electy) predicate.Electy {
	return predicate.Electy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Electy) predicate.Electy {
	return predicate.Electy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Electy) predicate.Electy {
	return predicate.Electy(sql.NotPredicates(p))
}
