// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/h2o/vigil/orm/ent/record"
)

// RecordCreate is the builder for creating a Record entity.
type RecordCreate struct {
	config
	mutation *RecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *RecordCreate) SetCreateTime(v time.Time) *RecordCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *RecordCreate) SetNillableCreateTime(v *time.Time) *RecordCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *RecordCreate) SetUpdateTime(v time.Time) *RecordCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *RecordCreate) SetNillableUpdateTime(v *time.Time) *RecordCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeviceCode sets the "device_code" field.
func (_c *RecordCreate) SetDeviceCode(v string) *RecordCreate {
	_c.mutation.SetDeviceCode(v)
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *RecordCreate) SetDeviceType(v string) *RecordCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetDataCode sets the "data_code" field.
func (_c *RecordCreate) SetDataCode(v string) *RecordCreate {
	_c.mutation.SetDataCode(v)
	return _c
}

// SetDataValue sets the "data_value" field.
func (_c *RecordCreate) SetDataValue(v int64) *RecordCreate {
	_c.mutation.SetDataValue(v)
	return _c
}

// SetNillableDataValue sets the "data_value" field if the given value is not nil.
func (_c *RecordCreate) SetNillableDataValue(v *int64) *RecordCreate {
	if v != nil {
		_c.SetDataValue(*v)
	}
	return _c
}

// SetDataTime sets the "data_time" field.
func (_c *RecordCreate) SetDataTime(v time.Time) *RecordCreate {
	_c.mutation.SetDataTime(v)
	return _c
}

// SetPosCode sets the "pos_code" field.
func (_c *RecordCreate) SetPosCode(v string) *RecordCreate {
	_c.mutation.SetPosCode(v)
	return _c
}

// SetProject sets the "project" field.
func (_c *RecordCreate) SetProject(v string) *RecordCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RecordCreate) SetID(v string) *RecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RecordCreate) SetNillableID(v *string) *RecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RecordMutation object of the builder.
func (_c *RecordCreate) Mutation() *RecordMutation {
	return _c.mutation
}

// Save creates the Record in the database.
func (_c *RecordCreate) Save(ctx context.Context) (*Record, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecordCreate) SaveX(ctx context.Context) *Record {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecordCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := record.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := record.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.DataValue(); !ok {
		v := record.DefaultDataValue
		_c.mutation.SetDataValue(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := record.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecordCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Record.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Record.update_time"`)}
	}
	if _, ok := _c.mutation.DeviceCode(); !ok {
		return &ValidationError{Name: "device_code", err: errors.New(`ent: missing required field "Record.device_code"`)}
	}
	if v, ok := _c.mutation.DeviceCode(); ok {
		if err := record.DeviceCodeValidator(v); err != nil {
			return &ValidationError{Name: "device_code", err: fmt.Errorf(`ent: validator failed for field "Record.device_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceType(); !ok {
		return &ValidationError{Name: "device_type", err: errors.New(`ent: missing required field "Record.device_type"`)}
	}
	if v, ok := _c.mutation.DeviceType(); ok {
		if err := record.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Record.device_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DataCode(); !ok {
		return &ValidationError{Name: "data_code", err: errors.New(`ent: missing required field "Record.data_code"`)}
	}
	if v, ok := _c.mutation.DataCode(); ok {
		if err := record.DataCodeValidator(v); err != nil {
			return &ValidationError{Name: "data_code", err: fmt.Errorf(`ent: validator failed for field "Record.data_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DataValue(); !ok {
		return &ValidationError{Name: "data_value", err: errors.New(`ent: missing required field "Record.data_value"`)}
	}
	if _, ok := _c.mutation.DataTime(); !ok {
		return &ValidationError{Name: "data_time", err: errors.New(`ent: missing required field "Record.data_time"`)}
	}
	if _, ok := _c.mutation.PosCode(); !ok {
		return &ValidationError{Name: "pos_code", err: errors.New(`ent: missing required field "Record.pos_code"`)}
	}
	if _, ok := _c.mutation.Project(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required field "Record.project"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := record.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Record.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RecordCreate) sqlSave(ctx context.Context) (*Record, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Record.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecordCreate) createSpec() (*Record, *sqlgraph.CreateSpec) {
	var (
		_node = &Record{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(record.Table, sqlgraph.NewFieldSpec(record.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(record.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(record.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.DeviceCode(); ok {
		_spec.SetField(record.FieldDeviceCode, field.TypeString, value)
		_node.DeviceCode = value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(record.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = value
	}
	if value, ok := _c.mutation.DataCode(); ok {
		_spec.SetField(record.FieldDataCode, field.TypeString, value)
		_node.DataCode = value
	}
	if value, ok := _c.mutation.DataValue(); ok {
		_spec.SetField(record.FieldDataValue, field.TypeInt64, value)
		_node.DataValue = value
	}
	if value, ok := _c.mutation.DataTime(); ok {
		_spec.SetField(record.FieldDataTime, field.TypeTime, value)
		_node.DataTime = value
	}
	if value, ok := _c.mutation.PosCode(); ok {
		_spec.SetField(record.FieldPosCode, field.TypeString, value)
		_node.PosCode = value
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(record.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Record.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecordUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *RecordCreate) OnConflict(opts ...sql.ConflictOption) *RecordUpsertOne {
	_c.conflict = opts
	return &RecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RecordCreate) OnConflictColumns(columns ...string) *RecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RecordUpsertOne{
		create: _c,
	}
}

type (
	// RecordUpsertOne is the builder for "upsert"-ing
	//  one Record node.
	RecordUpsertOne struct {
		create *RecordCreate
	}

	// RecordUpsert is the "OnConflict" setter.
	RecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *RecordUpsert) SetUpdateTime(v time.Time) *RecordUpsert {
	u.Set(record.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *RecordUpsert) UpdateUpdateTime() *RecordUpsert {
	u.SetExcluded(record.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(record.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RecordUpsertOne) UpdateNewValues() *RecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(record.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(record.FieldCreateTime)
		}
		if _, exists := u.create.mutation.DeviceCode(); exists {
			s.SetIgnore(record.FieldDeviceCode)
		}
		if _, exists := u.create.mutation.DeviceType(); exists {
			s.SetIgnore(record.FieldDeviceType)
		}
		if _, exists := u.create.mutation.DataCode(); exists {
			s.SetIgnore(record.FieldDataCode)
		}
		if _, exists := u.create.mutation.DataValue(); exists {
			s.SetIgnore(record.FieldDataValue)
		}
		if _, exists := u.create.mutation.DataTime(); exists {
			s.SetIgnore(record.FieldDataTime)
		}
		if _, exists := u.create.mutation.PosCode(); exists {
			s.SetIgnore(record.FieldPosCode)
		}
		if _, exists := u.create.mutation.Project(); exists {
			s.SetIgnore(record.FieldProject)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Record.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RecordUpsertOne) Ignore() *RecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecordUpsertOne) DoNothing() *RecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecordCreate.OnConflict
// documentation for more info.
func (u *RecordUpsertOne) Update(set func(*RecordUpsert)) *RecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *RecordUpsertOne) SetUpdateTime(v time.Time) *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *RecordUpsertOne) UpdateUpdateTime() *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *RecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RecordUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RecordUpsertOne.ID is not supported by MySQL driver. Use RecordUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RecordUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RecordCreateBulk is the builder for creating many Record entities in bulk.
type RecordCreateBulk struct {
	config
	err      error
	builders []*RecordCreate
	conflict []sql.ConflictOption
}

// Save creates the Record entities in the database.
func (_c *RecordCreateBulk) Save(ctx context.Context) ([]*Record, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Record, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecordCreateBulk) SaveX(ctx context.Context) []*Record {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Record.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecordUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *RecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *RecordUpsertBulk {
	_c.conflict = opts
	return &RecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RecordCreateBulk) OnConflictColumns(columns ...string) *RecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RecordUpsertBulk{
		create: _c,
	}
}

// RecordUpsertBulk is the builder for "upsert"-ing
// a bulk of Record nodes.
type RecordUpsertBulk struct {
	create *RecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(record.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RecordUpsertBulk) UpdateNewValues() *RecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(record.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(record.FieldCreateTime)
			}
			if _, exists := b.mutation.DeviceCode(); exists {
				s.SetIgnore(record.FieldDeviceCode)
			}
			if _, exists := b.mutation.DeviceType(); exists {
				s.SetIgnore(record.FieldDeviceType)
			}
			if _, exists := b.mutation.DataCode(); exists {
				s.SetIgnore(record.FieldDataCode)
			}
			if _, exists := b.mutation.DataValue(); exists {
				s.SetIgnore(record.FieldDataValue)
			}
			if _, exists := b.mutation.DataTime(); exists {
				s.SetIgnore(record.FieldDataTime)
			}
			if _, exists := b.mutation.PosCode(); exists {
				s.SetIgnore(record.FieldPosCode)
			}
			if _, exists := b.mutation.Project(); exists {
				s.SetIgnore(record.FieldProject)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RecordUpsertBulk) Ignore() *RecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecordUpsertBulk) DoNothing() *RecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecordCreateBulk.OnConflict
// documentation for more info.
func (u *RecordUpsertBulk) Update(set func(*RecordUpsert)) *RecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *RecordUpsertBulk) SetUpdateTime(v time.Time) *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *RecordUpsertBulk) UpdateUpdateTime() *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *RecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
