// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/h2o/vigil/orm/ent/water"
)

// WaterCreate is the builder for creating a Water entity.
type WaterCreate struct {
	config
	mutation *WaterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *WaterCreate) SetCreateTime(v time.Time) *WaterCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *WaterCreate) SetNillableCreateTime(v *time.Time) *WaterCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *WaterCreate) SetUpdateTime(v time.Time) *WaterCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *WaterCreate) SetNillableUpdateTime(v *time.Time) *WaterCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetPCode sets the "p_code" field.
func (_c *WaterCreate) SetPCode(v string) *WaterCreate {
	_c.mutation.SetPCode(v)
	return _c
}

// SetDeviceSn sets the "device_sn" field.
func (_c *WaterCreate) SetDeviceSn(v string) *WaterCreate {
	_c.mutation.SetDeviceSn(v)
	return _c
}

// SetNillableDeviceSn sets the "device_sn" field if the given value is not nil.
func (_c *WaterCreate) SetNillableDeviceSn(v *string) *WaterCreate {
	if v != nil {
		_c.SetDeviceSn(*v)
	}
	return _c
}

// SetDeviceCode sets the "device_code" field.
func (_c *WaterCreate) SetDeviceCode(v string) *WaterCreate {
	_c.mutation.SetDeviceCode(v)
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *WaterCreate) SetDeviceType(v string) *WaterCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *WaterCreate) SetDeviceName(v string) *WaterCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *WaterCreate) SetNillableDeviceName(v *string) *WaterCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetDataValue sets the "data_value" field.
func (_c *WaterCreate) SetDataValue(v int64) *WaterCreate {
	_c.mutation.SetDataValue(v)
	return _c
}

// SetNillableDataValue sets the "data_value" field if the given value is not nil.
func (_c *WaterCreate) SetNillableDataValue(v *int64) *WaterCreate {
	if v != nil {
		_c.SetDataValue(*v)
	}
	return _c
}

// SetDataCode sets the "data_code" field.
func (_c *WaterCreate) SetDataCode(v string) *WaterCreate {
	_c.mutation.SetDataCode(v)
	return _c
}

// SetDataTime sets the "data_time" field.
func (_c *WaterCreate) SetDataTime(v time.Time) *WaterCreate {
	_c.mutation.SetDataTime(v)
	return _c
}

// SetDataTs sets the "data_ts" field.
func (_c *WaterCreate) SetDataTs(v string) *WaterCreate {
	_c.mutation.SetDataTs(v)
	return _c
}

// SetPosCode sets the "pos_code" field.
func (_c *WaterCreate) SetPosCode(v string) *WaterCreate {
	_c.mutation.SetPosCode(v)
	return _c
}

// SetProject sets the "project" field.
func (_c *WaterCreate) SetProject(v string) *WaterCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetOwner sets the "owner" field.
func (_c *WaterCreate) SetOwner(v string) *WaterCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_c *WaterCreate) SetNillableOwner(v *string) *WaterCreate {
	if v != nil {
		_c.SetOwner(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WaterCreate) SetID(v string) *WaterCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WaterCreate) SetNillableID(v *string) *WaterCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the WaterMutation object of the builder.
func (_c *WaterCreate) Mutation() *WaterMutation {
	return _c.mutation
}

// Save creates the Water in the database.
func (_c *WaterCreate) Save(ctx context.Context) (*Water, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WaterCreate) SaveX(ctx context.Context) *Water {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WaterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WaterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WaterCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := water.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := water.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.DataValue(); !ok {
		v := water.DefaultDataValue
		_c.mutation.SetDataValue(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := water.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WaterCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Water.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Water.update_time"`)}
	}
	if _, ok := _c.mutation.PCode(); !ok {
		return &ValidationError{Name: "p_code", err: errors.New(`ent: missing required field "Water.p_code"`)}
	}
	if v, ok := _c.mutation.PCode(); ok {
		if err := water.PCodeValidator(v); err != nil {
			return &ValidationError{Name: "p_code", err: fmt.Errorf(`ent: validator failed for field "Water.p_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceCode(); !ok {
		return &ValidationError{Name: "device_code", err: errors.New(`ent: missing required field "Water.device_code"`)}
	}
	if v, ok := _c.mutation.DeviceCode(); ok {
		if err := water.DeviceCodeValidator(v); err != nil {
			return &ValidationError{Name: "device_code", err: fmt.Errorf(`ent: validator failed for field "Water.device_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceType(); !ok {
		return &ValidationError{Name: "device_type", err: errors.New(`ent: missing required field "Water.device_type"`)}
	}
	if v, ok := _c.mutation.DeviceType(); ok {
		if err := water.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Water.device_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DataValue(); !ok {
		return &ValidationError{Name: "data_value", err: errors.New(`ent: missing required field "Water.data_value"`)}
	}
	if _, ok := _c.mutation.DataCode(); !ok {
		return &ValidationError{Name: "data_code", err: errors.New(`ent: missing required field "Water.data_code"`)}
	}
	if v, ok := _c.mutation.DataCode(); ok {
		if err := water.DataCodeValidator(v); err != nil {
			return &ValidationError{Name: "data_code", err: fmt.Errorf(`ent: validator failed for field "Water.data_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DataTime(); !ok {
		return &ValidationError{Name: "data_time", err: errors.New(`ent: missing required field "Water.data_time"`)}
	}
	if _, ok := _c.mutation.DataTs(); !ok {
		return &ValidationError{Name: "data_ts", err: errors.New(`ent: missing required field "Water.data_ts"`)}
	}
	if v, ok := _c.mutation.DataTs(); ok {
		if err := water.DataTsValidator(v); err != nil {
			return &ValidationError{Name: "data_ts", err: fmt.Errorf(`ent: validator failed for field "Water.data_ts": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PosCode(); !ok {
		return &ValidationError{Name: "pos_code", err: errors.New(`ent: missing required field "Water.pos_code"`)}
	}
	if _, ok := _c.mutation.Project(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required field "Water.project"`)}
	}
	if v, ok := _c.mutation.Project(); ok {
		if err := water.ProjectValidator(v); err != nil {
			return &ValidationError{Name: "project", err: fmt.Errorf(`ent: validator failed for field "Water.project": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := water.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Water.id": %w`, err)}
		}
	}
	return nil
}

func (_c *WaterCreate) sqlSave(ctx context.Context) (*Water, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Water.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WaterCreate) createSpec() (*Water, *sqlgraph.CreateSpec) {
	var (
		_node = &Water{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(water.Table, sqlgraph.NewFieldSpec(water.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(water.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(water.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.PCode(); ok {
		_spec.SetField(water.FieldPCode, field.TypeString, value)
		_node.PCode = value
	}
	if value, ok := _c.mutation.DeviceSn(); ok {
		_spec.SetField(water.FieldDeviceSn, field.TypeString, value)
		_node.DeviceSn = value
	}
	if value, ok := _c.mutation.DeviceCode(); ok {
		_spec.SetField(water.FieldDeviceCode, field.TypeString, value)
		_node.DeviceCode = value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(water.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(water.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.DataValue(); ok {
		_spec.SetField(water.FieldDataValue, field.TypeInt64, value)
		_node.DataValue = value
	}
	if value, ok := _c.mutation.DataCode(); ok {
		_spec.SetField(water.FieldDataCode, field.TypeString, value)
		_node.DataCode = value
	}
	if value, ok := _c.mutation.DataTime(); ok {
		_spec.SetField(water.FieldDataTime, field.TypeTime, value)
		_node.DataTime = value
	}
	if value, ok := _c.mutation.DataTs(); ok {
		_spec.SetField(water.FieldDataTs, field.TypeString, value)
		_node.DataTs = value
	}
	if value, ok := _c.mutation.PosCode(); ok {
		_spec.SetField(water.FieldPosCode, field.TypeString, value)
		_node.PosCode = value
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(water.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(water.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Water.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WaterUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *WaterCreate) OnConflict(opts ...sql.ConflictOption) *WaterUpsertOne {
	_c.conflict = opts
	return &WaterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Water.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WaterCreate) OnConflictColumns(columns ...string) *WaterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WaterUpsertOne{
		create: _c,
	}
}

type (
	// WaterUpsertOne is the builder for "upsert"-ing
	//  one Water node.
	WaterUpsertOne struct {
		create *WaterCreate
	}

	// WaterUpsert is the "OnConflict" setter.
	WaterUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *WaterUpsert) SetUpdateTime(v time.Time) *WaterUpsert {
	u.Set(water.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *WaterUpsert) UpdateUpdateTime() *WaterUpsert {
	u.SetExcluded(water.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Water.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(water.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WaterUpsertOne) UpdateNewValues() *WaterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(water.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(water.FieldCreateTime)
		}
		if _, exists := u.create.mutation.PCode(); exists {
			s.SetIgnore(water.FieldPCode)
		}
		if _, exists := u.create.mutation.DeviceSn(); exists {
			s.SetIgnore(water.FieldDeviceSn)
		}
		if _, exists := u.create.mutation.DeviceCode(); exists {
			s.SetIgnore(water.FieldDeviceCode)
		}
		if _, exists := u.create.mutation.DeviceType(); exists {
			s.SetIgnore(water.FieldDeviceType)
		}
		if _, exists := u.create.mutation.DeviceName(); exists {
			s.SetIgnore(water.FieldDeviceName)
		}
		if _, exists := u.create.mutation.DataValue(); exists {
			s.SetIgnore(water.FieldDataValue)
		}
		if _, exists := u.create.mutation.DataCode(); exists {
			s.SetIgnore(water.FieldDataCode)
		}
		if _, exists := u.create.mutation.DataTime(); exists {
			s.SetIgnore(water.FieldDataTime)
		}
		if _, exists := u.create.mutation.DataTs(); exists {
			s.SetIgnore(water.FieldDataTs)
		}
		if _, exists := u.create.mutation.PosCode(); exists {
			s.SetIgnore(water.FieldPosCode)
		}
		if _, exists := u.create.mutation.Project(); exists {
			s.SetIgnore(water.FieldProject)
		}
		if _, exists := u.create.mutation.Owner(); exists {
			s.SetIgnore(water.FieldOwner)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Water.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WaterUpsertOne) Ignore() *WaterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WaterUpsertOne) DoNothing() *WaterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WaterCreate.OnConflict
// documentation for more info.
func (u *WaterUpsertOne) Update(set func(*WaterUpsert)) *WaterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WaterUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *WaterUpsertOne) SetUpdateTime(v time.Time) *WaterUpsertOne {
	return u.Update(func(s *WaterUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *WaterUpsertOne) UpdateUpdateTime() *WaterUpsertOne {
	return u.Update(func(s *WaterUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *WaterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WaterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WaterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WaterUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WaterUpsertOne.ID is not supported by MySQL driver. Use WaterUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WaterUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WaterCreateBulk is the builder for creating many Water entities in bulk.
type WaterCreateBulk struct {
	config
	err      error
	builders []*WaterCreate
	conflict []sql.ConflictOption
}

// Save creates the Water entities in the database.
func (_c *WaterCreateBulk) Save(ctx context.Context) ([]*Water, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Water, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WaterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WaterCreateBulk) SaveX(ctx context.Context) []*Water {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WaterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WaterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Water.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WaterUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *WaterCreateBulk) OnConflict(opts ...sql.ConflictOption) *WaterUpsertBulk {
	_c.conflict = opts
	return &WaterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Water.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WaterCreateBulk) OnConflictColumns(columns ...string) *WaterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WaterUpsertBulk{
		create: _c,
	}
}

// WaterUpsertBulk is the builder for "upsert"-ing
// a bulk of Water nodes.
type WaterUpsertBulk struct {
	create *WaterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Water.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(water.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WaterUpsertBulk) UpdateNewValues() *WaterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(water.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(water.FieldCreateTime)
			}
			if _, exists := b.mutation.PCode(); exists {
				s.SetIgnore(water.FieldPCode)
			}
			if _, exists := b.mutation.DeviceSn(); exists {
				s.SetIgnore(water.FieldDeviceSn)
			}
			if _, exists := b.mutation.DeviceCode(); exists {
				s.SetIgnore(water.FieldDeviceCode)
			}
			if _, exists := b.mutation.DeviceType(); exists {
				s.SetIgnore(water.FieldDeviceType)
			}
			if _, exists := b.mutation.DeviceName(); exists {
				s.SetIgnore(water.FieldDeviceName)
			}
			if _, exists := b.mutation.DataValue(); exists {
				s.SetIgnore(water.FieldDataValue)
			}
			if _, exists := b.mutation.DataCode(); exists {
				s.SetIgnore(water.FieldDataCode)
			}
			if _, exists := b.mutation.DataTime(); exists {
				s.SetIgnore(water.FieldDataTime)
			}
			if _, exists := b.mutation.DataTs(); exists {
				s.SetIgnore(water.FieldDataTs)
			}
			if _, exists := b.mutation.PosCode(); exists {
				s.SetIgnore(water.FieldPosCode)
			}
			if _, exists := b.mutation.Project(); exists {
				s.SetIgnore(water.FieldProject)
			}
			if _, exists := b.mutation.Owner(); exists {
				s.SetIgnore(water.FieldOwner)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Water.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WaterUpsertBulk) Ignore() *WaterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WaterUpsertBulk) DoNothing() *WaterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WaterCreateBulk.OnConflict
// documentation for more info.
func (u *WaterUpsertBulk) Update(set func(*WaterUpsert)) *WaterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WaterUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *WaterUpsertBulk) SetUpdateTime(v time.Time) *WaterUpsertBulk {
	return u.Update(func(s *WaterUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *WaterUpsertBulk) UpdateUpdateTime() *WaterUpsertBulk {
	return u.Update(func(s *WaterUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *WaterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WaterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WaterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WaterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
