// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/h2o/archon/orm/ent/device"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *DeviceCreate) SetCreateTime(v time.Time) *DeviceCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableCreateTime(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *DeviceCreate) SetUpdateTime(v time.Time) *DeviceCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableUpdateTime(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeviceSn sets the "device_sn" field.
func (_c *DeviceCreate) SetDeviceSn(v string) *DeviceCreate {
	_c.mutation.SetDeviceSn(v)
	return _c
}

// SetNillableDeviceSn sets the "device_sn" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDeviceSn(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDeviceSn(*v)
	}
	return _c
}

// SetDeviceCode sets the "device_code" field.
func (_c *DeviceCreate) SetDeviceCode(v string) *DeviceCreate {
	_c.mutation.SetDeviceCode(v)
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *DeviceCreate) SetDeviceType(v string) *DeviceCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *DeviceCreate) SetDeviceName(v string) *DeviceCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDeviceName(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetRate sets the "rate" field.
func (_c *DeviceCreate) SetRate(v int) *DeviceCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableRate(v *int) *DeviceCreate {
	if v != nil {
		_c.SetRate(*v)
	}
	return _c
}

// SetPosCode sets the "pos_code" field.
func (_c *DeviceCreate) SetPosCode(v string) *DeviceCreate {
	_c.mutation.SetPosCode(v)
	return _c
}

// SetNillablePosCode sets the "pos_code" field if the given value is not nil.
func (_c *DeviceCreate) SetNillablePosCode(v *string) *DeviceCreate {
	if v != nil {
		_c.SetPosCode(*v)
	}
	return _c
}

// SetAreaCode sets the "area_code" field.
func (_c *DeviceCreate) SetAreaCode(v string) *DeviceCreate {
	_c.mutation.SetAreaCode(v)
	return _c
}

// SetNillableAreaCode sets the "area_code" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableAreaCode(v *string) *DeviceCreate {
	if v != nil {
		_c.SetAreaCode(*v)
	}
	return _c
}

// SetProject sets the "project" field.
func (_c *DeviceCreate) SetProject(v string) *DeviceCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableProject(v *string) *DeviceCreate {
	if v != nil {
		_c.SetProject(*v)
	}
	return _c
}

// SetPcode sets the "pcode" field.
func (_c *DeviceCreate) SetPcode(v string) *DeviceCreate {
	_c.mutation.SetPcode(v)
	return _c
}

// SetNillablePcode sets the "pcode" field if the given value is not nil.
func (_c *DeviceCreate) SetNillablePcode(v *string) *DeviceCreate {
	if v != nil {
		_c.SetPcode(*v)
	}
	return _c
}

// SetMemo sets the "memo" field.
func (_c *DeviceCreate) SetMemo(v string) *DeviceCreate {
	_c.mutation.SetMemo(v)
	return _c
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableMemo(v *string) *DeviceCreate {
	if v != nil {
		_c.SetMemo(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceCreate) SetID(v string) *DeviceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableID(v *string) *DeviceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DeviceMutation object of the builder.
func (_c *DeviceCreate) Mutation() *DeviceMutation {
	return _c.mutation
}

// Save creates the Device in the database.
func (_c *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := device.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := device.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Rate(); !ok {
		v := device.DefaultRate
		_c.mutation.SetRate(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := device.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Device.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Device.update_time"`)}
	}
	if _, ok := _c.mutation.DeviceCode(); !ok {
		return &ValidationError{Name: "device_code", err: errors.New(`ent: missing required field "Device.device_code"`)}
	}
	if v, ok := _c.mutation.DeviceCode(); ok {
		if err := device.DeviceCodeValidator(v); err != nil {
			return &ValidationError{Name: "device_code", err: fmt.Errorf(`ent: validator failed for field "Device.device_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceType(); !ok {
		return &ValidationError{Name: "device_type", err: errors.New(`ent: missing required field "Device.device_type"`)}
	}
	if v, ok := _c.mutation.DeviceType(); ok {
		if err := device.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "Device.device_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "Device.rate"`)}
	}
	if v, ok := _c.mutation.Project(); ok {
		if err := device.ProjectValidator(v); err != nil {
			return &ValidationError{Name: "project", err: fmt.Errorf(`ent: validator failed for field "Device.project": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := device.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Device.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Device.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		_node = &Device{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(device.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(device.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.DeviceSn(); ok {
		_spec.SetField(device.FieldDeviceSn, field.TypeString, value)
		_node.DeviceSn = value
	}
	if value, ok := _c.mutation.DeviceCode(); ok {
		_spec.SetField(device.FieldDeviceCode, field.TypeString, value)
		_node.DeviceCode = value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(device.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(device.FieldRate, field.TypeInt, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.PosCode(); ok {
		_spec.SetField(device.FieldPosCode, field.TypeString, value)
		_node.PosCode = value
	}
	if value, ok := _c.mutation.AreaCode(); ok {
		_spec.SetField(device.FieldAreaCode, field.TypeString, value)
		_node.AreaCode = value
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(device.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	if value, ok := _c.mutation.Pcode(); ok {
		_spec.SetField(device.FieldPcode, field.TypeString, value)
		_node.Pcode = value
	}
	if value, ok := _c.mutation.Memo(); ok {
		_spec.SetField(device.FieldMemo, field.TypeString, value)
		_node.Memo = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Device.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceCreate) OnConflict(opts ...sql.ConflictOption) *DeviceUpsertOne {
	_c.conflict = opts
	return &DeviceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceCreate) OnConflictColumns(columns ...string) *DeviceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceUpsertOne{
		create: _c,
	}
}

type (
	// DeviceUpsertOne is the builder for "upsert"-ing
	//  one Device node.
	DeviceUpsertOne struct {
		create *DeviceCreate
	}

	// DeviceUpsert is the "OnConflict" setter.
	DeviceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *DeviceUpsert) SetUpdateTime(v time.Time) *DeviceUpsert {
	u.Set(device.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateUpdateTime() *DeviceUpsert {
	u.SetExcluded(device.FieldUpdateTime)
	return u
}

// SetDeviceSn sets the "device_sn" field.
func (u *DeviceUpsert) SetDeviceSn(v string) *DeviceUpsert {
	u.Set(device.FieldDeviceSn, v)
	return u
}

// UpdateDeviceSn sets the "device_sn" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateDeviceSn() *DeviceUpsert {
	u.SetExcluded(device.FieldDeviceSn)
	return u
}

// ClearDeviceSn clears the value of the "device_sn" field.
func (u *DeviceUpsert) ClearDeviceSn() *DeviceUpsert {
	u.SetNull(device.FieldDeviceSn)
	return u
}

// SetDeviceCode sets the "device_code" field.
func (u *DeviceUpsert) SetDeviceCode(v string) *DeviceUpsert {
	u.Set(device.FieldDeviceCode, v)
	return u
}

// UpdateDeviceCode sets the "device_code" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateDeviceCode() *DeviceUpsert {
	u.SetExcluded(device.FieldDeviceCode)
	return u
}

// SetDeviceType sets the "device_type" field.
func (u *DeviceUpsert) SetDeviceType(v string) *DeviceUpsert {
	u.Set(device.FieldDeviceType, v)
	return u
}

// UpdateDeviceType sets the "device_type" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateDeviceType() *DeviceUpsert {
	u.SetExcluded(device.FieldDeviceType)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *DeviceUpsert) SetDeviceName(v string) *DeviceUpsert {
	u.Set(device.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateDeviceName() *DeviceUpsert {
	u.SetExcluded(device.FieldDeviceName)
	return u
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *DeviceUpsert) ClearDeviceName() *DeviceUpsert {
	u.SetNull(device.FieldDeviceName)
	return u
}

// SetRate sets the "rate" field.
func (u *DeviceUpsert) SetRate(v int) *DeviceUpsert {
	u.Set(device.FieldRate, v)
	return u
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateRate() *DeviceUpsert {
	u.SetExcluded(device.FieldRate)
	return u
}

// AddRate adds v to the "rate" field.
func (u *DeviceUpsert) AddRate(v int) *DeviceUpsert {
	u.Add(device.FieldRate, v)
	return u
}

// SetPosCode sets the "pos_code" field.
func (u *DeviceUpsert) SetPosCode(v string) *DeviceUpsert {
	u.Set(device.FieldPosCode, v)
	return u
}

// UpdatePosCode sets the "pos_code" field to the value that was provided on create.
func (u *DeviceUpsert) UpdatePosCode() *DeviceUpsert {
	u.SetExcluded(device.FieldPosCode)
	return u
}

// ClearPosCode clears the value of the "pos_code" field.
func (u *DeviceUpsert) ClearPosCode() *DeviceUpsert {
	u.SetNull(device.FieldPosCode)
	return u
}

// SetAreaCode sets the "area_code" field.
func (u *DeviceUpsert) SetAreaCode(v string) *DeviceUpsert {
	u.Set(device.FieldAreaCode, v)
	return u
}

// UpdateAreaCode sets the "area_code" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateAreaCode() *DeviceUpsert {
	u.SetExcluded(device.FieldAreaCode)
	return u
}

// ClearAreaCode clears the value of the "area_code" field.
func (u *DeviceUpsert) ClearAreaCode() *DeviceUpsert {
	u.SetNull(device.FieldAreaCode)
	return u
}

// SetProject sets the "project" field.
func (u *DeviceUpsert) SetProject(v string) *DeviceUpsert {
	u.Set(device.FieldProject, v)
	return u
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateProject() *DeviceUpsert {
	u.SetExcluded(device.FieldProject)
	return u
}

// ClearProject clears the value of the "project" field.
func (u *DeviceUpsert) ClearProject() *DeviceUpsert {
	u.SetNull(device.FieldProject)
	return u
}

// SetPcode sets the "pcode" field.
func (u *DeviceUpsert) SetPcode(v string) *DeviceUpsert {
	u.Set(device.FieldPcode, v)
	return u
}

// UpdatePcode sets the "pcode" field to the value that was provided on create.
func (u *DeviceUpsert) UpdatePcode() *DeviceUpsert {
	u.SetExcluded(device.FieldPcode)
	return u
}

// ClearPcode clears the value of the "pcode" field.
func (u *DeviceUpsert) ClearPcode() *DeviceUpsert {
	u.SetNull(device.FieldPcode)
	return u
}

// SetMemo sets the "memo" field.
func (u *DeviceUpsert) SetMemo(v string) *DeviceUpsert {
	u.Set(device.FieldMemo, v)
	return u
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *DeviceUpsert) UpdateMemo() *DeviceUpsert {
	u.SetExcluded(device.FieldMemo)
	return u
}

// ClearMemo clears the value of the "memo" field.
func (u *DeviceUpsert) ClearMemo() *DeviceUpsert {
	u.SetNull(device.FieldMemo)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(device.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceUpsertOne) UpdateNewValues() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(device.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(device.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeviceUpsertOne) Ignore() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceUpsertOne) DoNothing() *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceCreate.OnConflict
// documentation for more info.
func (u *DeviceUpsertOne) Update(set func(*DeviceUpsert)) *DeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DeviceUpsertOne) SetUpdateTime(v time.Time) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateUpdateTime() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetDeviceSn sets the "device_sn" field.
func (u *DeviceUpsertOne) SetDeviceSn(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceSn(v)
	})
}

// UpdateDeviceSn sets the "device_sn" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateDeviceSn() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceSn()
	})
}

// ClearDeviceSn clears the value of the "device_sn" field.
func (u *DeviceUpsertOne) ClearDeviceSn() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearDeviceSn()
	})
}

// SetDeviceCode sets the "device_code" field.
func (u *DeviceUpsertOne) SetDeviceCode(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceCode(v)
	})
}

// UpdateDeviceCode sets the "device_code" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateDeviceCode() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceCode()
	})
}

// SetDeviceType sets the "device_type" field.
func (u *DeviceUpsertOne) SetDeviceType(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceType(v)
	})
}

// UpdateDeviceType sets the "device_type" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateDeviceType() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceType()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *DeviceUpsertOne) SetDeviceName(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateDeviceName() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *DeviceUpsertOne) ClearDeviceName() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearDeviceName()
	})
}

// SetRate sets the "rate" field.
func (u *DeviceUpsertOne) SetRate(v int) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *DeviceUpsertOne) AddRate(v int) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateRate() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateRate()
	})
}

// SetPosCode sets the "pos_code" field.
func (u *DeviceUpsertOne) SetPosCode(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetPosCode(v)
	})
}

// UpdatePosCode sets the "pos_code" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdatePosCode() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdatePosCode()
	})
}

// ClearPosCode clears the value of the "pos_code" field.
func (u *DeviceUpsertOne) ClearPosCode() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearPosCode()
	})
}

// SetAreaCode sets the "area_code" field.
func (u *DeviceUpsertOne) SetAreaCode(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetAreaCode(v)
	})
}

// UpdateAreaCode sets the "area_code" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateAreaCode() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateAreaCode()
	})
}

// ClearAreaCode clears the value of the "area_code" field.
func (u *DeviceUpsertOne) ClearAreaCode() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearAreaCode()
	})
}

// SetProject sets the "project" field.
func (u *DeviceUpsertOne) SetProject(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetProject(v)
	})
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateProject() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateProject()
	})
}

// ClearProject clears the value of the "project" field.
func (u *DeviceUpsertOne) ClearProject() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearProject()
	})
}

// SetPcode sets the "pcode" field.
func (u *DeviceUpsertOne) SetPcode(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetPcode(v)
	})
}

// UpdatePcode sets the "pcode" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdatePcode() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdatePcode()
	})
}

// ClearPcode clears the value of the "pcode" field.
func (u *DeviceUpsertOne) ClearPcode() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearPcode()
	})
}

// SetMemo sets the "memo" field.
func (u *DeviceUpsertOne) SetMemo(v string) *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *DeviceUpsertOne) UpdateMemo() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *DeviceUpsertOne) ClearMemo() *DeviceUpsertOne {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearMemo()
	})
}

// Exec executes the query.
func (u *DeviceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeviceUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeviceUpsertOne.ID is not supported by MySQL driver. Use DeviceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeviceUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeviceCreateBulk is the builder for creating many Device entities in bulk.
type DeviceCreateBulk struct {
	config
	err      error
	builders []*DeviceCreate
	conflict []sql.ConflictOption
}

// Save creates the Device entities in the database.
func (_c *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Device, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Device.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeviceUpsertBulk {
	_c.conflict = opts
	return &DeviceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceCreateBulk) OnConflictColumns(columns ...string) *DeviceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceUpsertBulk{
		create: _c,
	}
}

// DeviceUpsertBulk is the builder for "upsert"-ing
// a bulk of Device nodes.
type DeviceUpsertBulk struct {
	create *DeviceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(device.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceUpsertBulk) UpdateNewValues() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(device.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(device.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Device.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeviceUpsertBulk) Ignore() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceUpsertBulk) DoNothing() *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceCreateBulk.OnConflict
// documentation for more info.
func (u *DeviceUpsertBulk) Update(set func(*DeviceUpsert)) *DeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DeviceUpsertBulk) SetUpdateTime(v time.Time) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateUpdateTime() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetDeviceSn sets the "device_sn" field.
func (u *DeviceUpsertBulk) SetDeviceSn(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceSn(v)
	})
}

// UpdateDeviceSn sets the "device_sn" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateDeviceSn() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceSn()
	})
}

// ClearDeviceSn clears the value of the "device_sn" field.
func (u *DeviceUpsertBulk) ClearDeviceSn() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearDeviceSn()
	})
}

// SetDeviceCode sets the "device_code" field.
func (u *DeviceUpsertBulk) SetDeviceCode(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceCode(v)
	})
}

// UpdateDeviceCode sets the "device_code" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateDeviceCode() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceCode()
	})
}

// SetDeviceType sets the "device_type" field.
func (u *DeviceUpsertBulk) SetDeviceType(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceType(v)
	})
}

// UpdateDeviceType sets the "device_type" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateDeviceType() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceType()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *DeviceUpsertBulk) SetDeviceName(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateDeviceName() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *DeviceUpsertBulk) ClearDeviceName() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearDeviceName()
	})
}

// SetRate sets the "rate" field.
func (u *DeviceUpsertBulk) SetRate(v int) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *DeviceUpsertBulk) AddRate(v int) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateRate() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateRate()
	})
}

// SetPosCode sets the "pos_code" field.
func (u *DeviceUpsertBulk) SetPosCode(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetPosCode(v)
	})
}

// UpdatePosCode sets the "pos_code" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdatePosCode() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdatePosCode()
	})
}

// ClearPosCode clears the value of the "pos_code" field.
func (u *DeviceUpsertBulk) ClearPosCode() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearPosCode()
	})
}

// SetAreaCode sets the "area_code" field.
func (u *DeviceUpsertBulk) SetAreaCode(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetAreaCode(v)
	})
}

// UpdateAreaCode sets the "area_code" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateAreaCode() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateAreaCode()
	})
}

// ClearAreaCode clears the value of the "area_code" field.
func (u *DeviceUpsertBulk) ClearAreaCode() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearAreaCode()
	})
}

// SetProject sets the "project" field.
func (u *DeviceUpsertBulk) SetProject(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetProject(v)
	})
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateProject() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateProject()
	})
}

// ClearProject clears the value of the "project" field.
func (u *DeviceUpsertBulk) ClearProject() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearProject()
	})
}

// SetPcode sets the "pcode" field.
func (u *DeviceUpsertBulk) SetPcode(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetPcode(v)
	})
}

// UpdatePcode sets the "pcode" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdatePcode() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdatePcode()
	})
}

// ClearPcode clears the value of the "pcode" field.
func (u *DeviceUpsertBulk) ClearPcode() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearPcode()
	})
}

// SetMemo sets the "memo" field.
func (u *DeviceUpsertBulk) SetMemo(v string) *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *DeviceUpsertBulk) UpdateMemo() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *DeviceUpsertBulk) ClearMemo() *DeviceUpsertBulk {
	return u.Update(func(s *DeviceUpsert) {
		s.ClearMemo()
	})
}

// Exec executes the query.
func (u *DeviceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeviceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
