// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/h2o/archon/orm/ent/device"
)

// Device is the model entity for the Device schema.
type Device struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// 设备序列号
	DeviceSn string `json:"device_sn,omitempty"`
	// 设备号
	DeviceCode string `json:"device_code,omitempty"`
	// 设备类型
	DeviceType string `json:"device_type,omitempty"`
	// 设备名称
	DeviceName string `json:"device_name,omitempty"`
	// 当前倍率
	Rate int `json:"rate,omitempty"`
	// 位置编号
	PosCode string `json:"pos_code,omitempty"`
	// 区域编号
	AreaCode string `json:"area_code,omitempty"`
	// 项目编号
	Project string `json:"project,omitempty"`
	// 对外位置编号
	Pcode string `json:"pcode,omitempty"`
	// 备注
	Memo         string `json:"memo,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Device) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case device.FieldRate:
			values[i] = new(sql.NullInt64)
		case device.FieldID, device.FieldDeviceSn, device.FieldDeviceCode, device.FieldDeviceType, device.FieldDeviceName, device.FieldPosCode, device.FieldAreaCode, device.FieldProject, device.FieldPcode, device.FieldMemo:
			values[i] = new(sql.NullString)
		case device.FieldCreateTime, device.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Device fields.
func (_m *Device) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case device.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case device.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case device.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case device.FieldDeviceSn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_sn", values[i])
			} else if value.Valid {
				_m.DeviceSn = value.String
			}
		case device.FieldDeviceCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_code", values[i])
			} else if value.Valid {
				_m.DeviceCode = value.String
			}
		case device.FieldDeviceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_type", values[i])
			} else if value.Valid {
				_m.DeviceType = value.String
			}
		case device.FieldDeviceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_name", values[i])
			} else if value.Valid {
				_m.DeviceName = value.String
			}
		case device.FieldRate:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				_m.Rate = int(value.Int64)
			}
		case device.FieldPosCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pos_code", values[i])
			} else if value.Valid {
				_m.PosCode = value.String
			}
		case device.FieldAreaCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field area_code", values[i])
			} else if value.Valid {
				_m.AreaCode = value.String
			}
		case device.FieldProject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project", values[i])
			} else if value.Valid {
				_m.Project = value.String
			}
		case device.FieldPcode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pcode", values[i])
			} else if value.Valid {
				_m.Pcode = value.String
			}
		case device.FieldMemo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field memo", values[i])
			} else if value.Valid {
				_m.Memo = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Device.
// This includes values selected through modifiers, order, etc.
func (_m *Device) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Device.
// Note that you need to call Device.Unwrap() before calling this method if this Device
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Device) Update() *DeviceUpdateOne {
	return NewDeviceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Device entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Device) Unwrap() *Device {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Device is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Device) String() string {
	var builder strings.Builder
	builder.WriteString("Device(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("device_sn=")
	builder.WriteString(_m.DeviceSn)
	builder.WriteString(", ")
	builder.WriteString("device_code=")
	builder.WriteString(_m.DeviceCode)
	builder.WriteString(", ")
	builder.WriteString("device_type=")
	builder.WriteString(_m.DeviceType)
	builder.WriteString(", ")
	builder.WriteString("device_name=")
	builder.WriteString(_m.DeviceName)
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rate))
	builder.WriteString(", ")
	builder.WriteString("pos_code=")
	builder.WriteString(_m.PosCode)
	builder.WriteString(", ")
	builder.WriteString("area_code=")
	builder.WriteString(_m.AreaCode)
	builder.WriteString(", ")
	builder.WriteString("project=")
	builder.WriteString(_m.Project)
	builder.WriteString(", ")
	builder.WriteString("pcode=")
	builder.WriteString(_m.Pcode)
	builder.WriteString(", ")
	builder.WriteString("memo=")
	builder.WriteString(_m.Memo)
	builder.WriteByte(')')
	return builder.String()
}

// Devices is a parsable slice of Device.
type Devices []*Device
