// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/h2o/archon/orm/ent/viewrecord"
)

// ViewRecordCreate is the builder for creating a ViewRecord entity.
type ViewRecordCreate struct {
	config
	mutation *ViewRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeviceCode sets the "device_code" field.
func (_c *ViewRecordCreate) SetDeviceCode(v string) *ViewRecordCreate {
	_c.mutation.SetDeviceCode(v)
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *ViewRecordCreate) SetDeviceType(v string) *ViewRecordCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetDataValue sets the "data_value" field.
func (_c *ViewRecordCreate) SetDataValue(v int64) *ViewRecordCreate {
	_c.mutation.SetDataValue(v)
	return _c
}

// SetDataTime sets the "data_time" field.
func (_c *ViewRecordCreate) SetDataTime(v time.Time) *ViewRecordCreate {
	_c.mutation.SetDataTime(v)
	return _c
}

// SetDataTs sets the "data_ts" field.
func (_c *ViewRecordCreate) SetDataTs(v string) *ViewRecordCreate {
	_c.mutation.SetDataTs(v)
	return _c
}

// SetDeviceSn sets the "device_sn" field.
func (_c *ViewRecordCreate) SetDeviceSn(v string) *ViewRecordCreate {
	_c.mutation.SetDeviceSn(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *ViewRecordCreate) SetDeviceName(v string) *ViewRecordCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetRate sets the "rate" field.
func (_c *ViewRecordCreate) SetRate(v int) *ViewRecordCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetProject sets the "project" field.
func (_c *ViewRecordCreate) SetProject(v string) *ViewRecordCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetPosCode sets the "pos_code" field.
func (_c *ViewRecordCreate) SetPosCode(v string) *ViewRecordCreate {
	_c.mutation.SetPosCode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ViewRecordCreate) SetStatus(v int) *ViewRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetMemo sets the "memo" field.
func (_c *ViewRecordCreate) SetMemo(v string) *ViewRecordCreate {
	_c.mutation.SetMemo(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ViewRecordCreate) SetID(v string) *ViewRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ViewRecordMutation object of the builder.
func (_c *ViewRecordCreate) Mutation() *ViewRecordMutation {
	return _c.mutation
}

// Save creates the ViewRecord in the database.
func (_c *ViewRecordCreate) Save(ctx context.Context) (*ViewRecord, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ViewRecordCreate) SaveX(ctx context.Context) *ViewRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ViewRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ViewRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ViewRecordCreate) check() error {
	if _, ok := _c.mutation.DeviceCode(); !ok {
		return &ValidationError{Name: "device_code", err: errors.New(`ent: missing required field "ViewRecord.device_code"`)}
	}
	if _, ok := _c.mutation.DeviceType(); !ok {
		return &ValidationError{Name: "device_type", err: errors.New(`ent: missing required field "ViewRecord.device_type"`)}
	}
	if _, ok := _c.mutation.DataValue(); !ok {
		return &ValidationError{Name: "data_value", err: errors.New(`ent: missing required field "ViewRecord.data_value"`)}
	}
	if _, ok := _c.mutation.DataTime(); !ok {
		return &ValidationError{Name: "data_time", err: errors.New(`ent: missing required field "ViewRecord.data_time"`)}
	}
	if _, ok := _c.mutation.DataTs(); !ok {
		return &ValidationError{Name: "data_ts", err: errors.New(`ent: missing required field "ViewRecord.data_ts"`)}
	}
	if _, ok := _c.mutation.DeviceSn(); !ok {
		return &ValidationError{Name: "device_sn", err: errors.New(`ent: missing required field "ViewRecord.device_sn"`)}
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`ent: missing required field "ViewRecord.device_name"`)}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "ViewRecord.rate"`)}
	}
	if _, ok := _c.mutation.Project(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required field "ViewRecord.project"`)}
	}
	if _, ok := _c.mutation.PosCode(); !ok {
		return &ValidationError{Name: "pos_code", err: errors.New(`ent: missing required field "ViewRecord.pos_code"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ViewRecord.status"`)}
	}
	if _, ok := _c.mutation.Memo(); !ok {
		return &ValidationError{Name: "memo", err: errors.New(`ent: missing required field "ViewRecord.memo"`)}
	}
	return nil
}

func (_c *ViewRecordCreate) sqlSave(ctx context.Context) (*ViewRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ViewRecord.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ViewRecordCreate) createSpec() (*ViewRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &ViewRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(viewrecord.Table, sqlgraph.NewFieldSpec(viewrecord.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeviceCode(); ok {
		_spec.SetField(viewrecord.FieldDeviceCode, field.TypeString, value)
		_node.DeviceCode = value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(viewrecord.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = value
	}
	if value, ok := _c.mutation.DataValue(); ok {
		_spec.SetField(viewrecord.FieldDataValue, field.TypeInt64, value)
		_node.DataValue = value
	}
	if value, ok := _c.mutation.DataTime(); ok {
		_spec.SetField(viewrecord.FieldDataTime, field.TypeTime, value)
		_node.DataTime = value
	}
	if value, ok := _c.mutation.DataTs(); ok {
		_spec.SetField(viewrecord.FieldDataTs, field.TypeString, value)
		_node.DataTs = value
	}
	if value, ok := _c.mutation.DeviceSn(); ok {
		_spec.SetField(viewrecord.FieldDeviceSn, field.TypeString, value)
		_node.DeviceSn = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(viewrecord.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(viewrecord.FieldRate, field.TypeInt, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(viewrecord.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	if value, ok := _c.mutation.PosCode(); ok {
		_spec.SetField(viewrecord.FieldPosCode, field.TypeString, value)
		_node.PosCode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(viewrecord.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Memo(); ok {
		_spec.SetField(viewrecord.FieldMemo, field.TypeString, value)
		_node.Memo = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ViewRecord.Create().
//		SetDeviceCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ViewRecordUpsert) {
//			SetDeviceCode(v+v).
//		}).
//		Exec(ctx)
func (_c *ViewRecordCreate) OnConflict(opts ...sql.ConflictOption) *ViewRecordUpsertOne {
	_c.conflict = opts
	return &ViewRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ViewRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ViewRecordCreate) OnConflictColumns(columns ...string) *ViewRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ViewRecordUpsertOne{
		create: _c,
	}
}

type (
	// ViewRecordUpsertOne is the builder for "upsert"-ing
	//  one ViewRecord node.
	ViewRecordUpsertOne struct {
		create *ViewRecordCreate
	}

	// ViewRecordUpsert is the "OnConflict" setter.
	ViewRecordUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ViewRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(viewrecord.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ViewRecordUpsertOne) UpdateNewValues() *ViewRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(viewrecord.FieldID)
		}
		if _, exists := u.create.mutation.DeviceCode(); exists {
			s.SetIgnore(viewrecord.FieldDeviceCode)
		}
		if _, exists := u.create.mutation.DeviceType(); exists {
			s.SetIgnore(viewrecord.FieldDeviceType)
		}
		if _, exists := u.create.mutation.DataValue(); exists {
			s.SetIgnore(viewrecord.FieldDataValue)
		}
		if _, exists := u.create.mutation.DataTime(); exists {
			s.SetIgnore(viewrecord.FieldDataTime)
		}
		if _, exists := u.create.mutation.DataTs(); exists {
			s.SetIgnore(viewrecord.FieldDataTs)
		}
		if _, exists := u.create.mutation.DeviceSn(); exists {
			s.SetIgnore(viewrecord.FieldDeviceSn)
		}
		if _, exists := u.create.mutation.DeviceName(); exists {
			s.SetIgnore(viewrecord.FieldDeviceName)
		}
		if _, exists := u.create.mutation.Rate(); exists {
			s.SetIgnore(viewrecord.FieldRate)
		}
		if _, exists := u.create.mutation.Project(); exists {
			s.SetIgnore(viewrecord.FieldProject)
		}
		if _, exists := u.create.mutation.PosCode(); exists {
			s.SetIgnore(viewrecord.FieldPosCode)
		}
		if _, exists := u.create.mutation.Status(); exists {
			s.SetIgnore(viewrecord.FieldStatus)
		}
		if _, exists := u.create.mutation.Memo(); exists {
			s.SetIgnore(viewrecord.FieldMemo)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ViewRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ViewRecordUpsertOne) Ignore() *ViewRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ViewRecordUpsertOne) DoNothing() *ViewRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ViewRecordCreate.OnConflict
// documentation for more info.
func (u *ViewRecordUpsertOne) Update(set func(*ViewRecordUpsert)) *ViewRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ViewRecordUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ViewRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ViewRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ViewRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ViewRecordUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ViewRecordUpsertOne.ID is not supported by MySQL driver. Use ViewRecordUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ViewRecordUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ViewRecordCreateBulk is the builder for creating many ViewRecord entities in bulk.
type ViewRecordCreateBulk struct {
	config
	err      error
	builders []*ViewRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the ViewRecord entities in the database.
func (_c *ViewRecordCreateBulk) Save(ctx context.Context) ([]*ViewRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ViewRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ViewRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ViewRecordCreateBulk) SaveX(ctx context.Context) []*ViewRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ViewRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ViewRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ViewRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ViewRecordUpsert) {
//			SetDeviceCode(v+v).
//		}).
//		Exec(ctx)
func (_c *ViewRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *ViewRecordUpsertBulk {
	_c.conflict = opts
	return &ViewRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ViewRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ViewRecordCreateBulk) OnConflictColumns(columns ...string) *ViewRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ViewRecordUpsertBulk{
		create: _c,
	}
}

// ViewRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of ViewRecord nodes.
type ViewRecordUpsertBulk struct {
	create *ViewRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ViewRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(viewrecord.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ViewRecordUpsertBulk) UpdateNewValues() *ViewRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(viewrecord.FieldID)
			}
			if _, exists := b.mutation.DeviceCode(); exists {
				s.SetIgnore(viewrecord.FieldDeviceCode)
			}
			if _, exists := b.mutation.DeviceType(); exists {
				s.SetIgnore(viewrecord.FieldDeviceType)
			}
			if _, exists := b.mutation.DataValue(); exists {
				s.SetIgnore(viewrecord.FieldDataValue)
			}
			if _, exists := b.mutation.DataTime(); exists {
				s.SetIgnore(viewrecord.FieldDataTime)
			}
			if _, exists := b.mutation.DataTs(); exists {
				s.SetIgnore(viewrecord.FieldDataTs)
			}
			if _, exists := b.mutation.DeviceSn(); exists {
				s.SetIgnore(viewrecord.FieldDeviceSn)
			}
			if _, exists := b.mutation.DeviceName(); exists {
				s.SetIgnore(viewrecord.FieldDeviceName)
			}
			if _, exists := b.mutation.Rate(); exists {
				s.SetIgnore(viewrecord.FieldRate)
			}
			if _, exists := b.mutation.Project(); exists {
				s.SetIgnore(viewrecord.FieldProject)
			}
			if _, exists := b.mutation.PosCode(); exists {
				s.SetIgnore(viewrecord.FieldPosCode)
			}
			if _, exists := b.mutation.Status(); exists {
				s.SetIgnore(viewrecord.FieldStatus)
			}
			if _, exists := b.mutation.Memo(); exists {
				s.SetIgnore(viewrecord.FieldMemo)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ViewRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ViewRecordUpsertBulk) Ignore() *ViewRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ViewRecordUpsertBulk) DoNothing() *ViewRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ViewRecordCreateBulk.OnConflict
// documentation for more info.
func (u *ViewRecordUpsertBulk) Update(set func(*ViewRecordUpsert)) *ViewRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ViewRecordUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ViewRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ViewRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ViewRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ViewRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
