// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ValueCharge is the predicate function for valuecharge builders.
type ValueCharge func(*sql.Selector)
