// Code generated by ent, DO NOT EDIT.

package alarm

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the alarm type in the database.
	Label = "alarm"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTopID holds the string denoting the top_id field in the database.
	FieldTopID = "top_id"
	// FieldTopCode holds the string denoting the top_code field in the database.
	FieldTopCode = "top_code"
	// FieldAlarm1 holds the string denoting the alarm_1 field in the database.
	FieldAlarm1 = "alarm_1"
	// FieldAlarmTime1 holds the string denoting the alarm_time_1 field in the database.
	FieldAlarmTime1 = "alarm_time_1"
	// FieldAlarmStock1 holds the string denoting the alarm_stock_1 field in the database.
	FieldAlarmStock1 = "alarm_stock_1"
	// FieldAlarm2 holds the string denoting the alarm_2 field in the database.
	FieldAlarm2 = "alarm_2"
	// FieldAlarmTime2 holds the string denoting the alarm_time_2 field in the database.
	FieldAlarmTime2 = "alarm_time_2"
	// FieldAlarmStock2 holds the string denoting the alarm_stock_2 field in the database.
	FieldAlarmStock2 = "alarm_stock_2"
	// FieldAlarm3 holds the string denoting the alarm_3 field in the database.
	FieldAlarm3 = "alarm_3"
	// FieldAlarmTime3 holds the string denoting the alarm_time_3 field in the database.
	FieldAlarmTime3 = "alarm_time_3"
	// FieldAlarmStock3 holds the string denoting the alarm_stock_3 field in the database.
	FieldAlarmStock3 = "alarm_stock_3"
	// Table holds the table name of the alarm in the database.
	Table = "mdna_alarm"
)

// Columns holds all SQL columns for alarm fields.
var Columns = []string{
	FieldID,
	FieldTopID,
	FieldTopCode,
	FieldAlarm1,
	FieldAlarmTime1,
	FieldAlarmStock1,
	FieldAlarm2,
	FieldAlarmTime2,
	FieldAlarmStock2,
	FieldAlarm3,
	FieldAlarmTime3,
	FieldAlarmStock3,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TopIDValidator is a validator for the "top_id" field. It is called by the builders before save.
	TopIDValidator func(string) error
	// TopCodeValidator is a validator for the "top_code" field. It is called by the builders before save.
	TopCodeValidator func(string) error
	// DefaultAlarm1 holds the default value on creation for the "alarm_1" field.
	DefaultAlarm1 int
	// DefaultAlarmStock1 holds the default value on creation for the "alarm_stock_1" field.
	DefaultAlarmStock1 int64
	// DefaultAlarm2 holds the default value on creation for the "alarm_2" field.
	DefaultAlarm2 int
	// DefaultAlarmStock2 holds the default value on creation for the "alarm_stock_2" field.
	DefaultAlarmStock2 int64
	// DefaultAlarm3 holds the default value on creation for the "alarm_3" field.
	DefaultAlarm3 int
	// DefaultAlarmStock3 holds the default value on creation for the "alarm_stock_3" field.
	DefaultAlarmStock3 int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Alarm queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTopID orders the results by the top_id field.
func ByTopID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopID, opts...).ToFunc()
}

// ByTopCode orders the results by the top_code field.
func ByTopCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopCode, opts...).ToFunc()
}

// ByAlarm1 orders the results by the alarm_1 field.
func ByAlarm1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarm1, opts...).ToFunc()
}

// ByAlarmTime1 orders the results by the alarm_time_1 field.
func ByAlarmTime1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarmTime1, opts...).ToFunc()
}

// ByAlarmStock1 orders the results by the alarm_stock_1 field.
func ByAlarmStock1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarmStock1, opts...).ToFunc()
}

// ByAlarm2 orders the results by the alarm_2 field.
func ByAlarm2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarm2, opts...).ToFunc()
}

// ByAlarmTime2 orders the results by the alarm_time_2 field.
func ByAlarmTime2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarmTime2, opts...).ToFunc()
}

// ByAlarmStock2 orders the results by the alarm_stock_2 field.
func ByAlarmStock2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarmStock2, opts...).ToFunc()
}

// ByAlarm3 orders the results by the alarm_3 field.
func ByAlarm3(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarm3, opts...).ToFunc()
}

// ByAlarmTime3 orders the results by the alarm_time_3 field.
func ByAlarmTime3(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarmTime3, opts...).ToFunc()
}

// ByAlarmStock3 orders the results by the alarm_stock_3 field.
func ByAlarmStock3(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlarmStock3, opts...).ToFunc()
}
