// Code generated by ent, DO NOT EDIT.

package cdr

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cdr type in the database.
	Label = "cdr"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeviceCode holds the string denoting the device_code field in the database.
	FieldDeviceCode = "device_code"
	// FieldDeviceType holds the string denoting the device_type field in the database.
	FieldDeviceType = "device_type"
	// FieldLastDataValue holds the string denoting the last_data_value field in the database.
	FieldLastDataValue = "last_data_value"
	// FieldDataValue holds the string denoting the data_value field in the database.
	FieldDataValue = "data_value"
	// FieldLastDataCode holds the string denoting the last_data_code field in the database.
	FieldLastDataCode = "last_data_code"
	// FieldDataCode holds the string denoting the data_code field in the database.
	FieldDataCode = "data_code"
	// FieldLastDataTime holds the string denoting the last_data_time field in the database.
	FieldLastDataTime = "last_data_time"
	// FieldDataTime holds the string denoting the data_time field in the database.
	FieldDataTime = "data_time"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldRuleType holds the string denoting the rule_type field in the database.
	FieldRuleType = "rule_type"
	// FieldRuleCtg holds the string denoting the rule_ctg field in the database.
	FieldRuleCtg = "rule_ctg"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldUnitFeeFen holds the string denoting the unit_fee_fen field in the database.
	FieldUnitFeeFen = "unit_fee_fen"
	// FieldFeeFen holds the string denoting the fee_fen field in the database.
	FieldFeeFen = "fee_fen"
	// FieldPosCode holds the string denoting the pos_code field in the database.
	FieldPosCode = "pos_code"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// FieldMemo holds the string denoting the memo field in the database.
	FieldMemo = "memo"
	// Table holds the table name of the cdr in the database.
	Table = "t_nh_cdr"
)

// Columns holds all SQL columns for cdr fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeviceCode,
	FieldDeviceType,
	FieldLastDataValue,
	FieldDataValue,
	FieldLastDataCode,
	FieldDataCode,
	FieldLastDataTime,
	FieldDataTime,
	FieldRuleID,
	FieldRuleType,
	FieldRuleCtg,
	FieldValue,
	FieldUnitFeeFen,
	FieldFeeFen,
	FieldPosCode,
	FieldProject,
	FieldMemo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DeviceCodeValidator is a validator for the "device_code" field. It is called by the builders before save.
	DeviceCodeValidator func(string) error
	// DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	DeviceTypeValidator func(string) error
	// DefaultLastDataValue holds the default value on creation for the "last_data_value" field.
	DefaultLastDataValue int64
	// DefaultDataValue holds the default value on creation for the "data_value" field.
	DefaultDataValue int64
	// DataCodeValidator is a validator for the "data_code" field. It is called by the builders before save.
	DataCodeValidator func(string) error
	// RuleIDValidator is a validator for the "rule_id" field. It is called by the builders before save.
	RuleIDValidator func(string) error
	// RuleTypeValidator is a validator for the "rule_type" field. It is called by the builders before save.
	RuleTypeValidator func(string) error
	// RuleCtgValidator is a validator for the "rule_ctg" field. It is called by the builders before save.
	RuleCtgValidator func(string) error
	// DefaultValue holds the default value on creation for the "value" field.
	DefaultValue int64
	// DefaultUnitFeeFen holds the default value on creation for the "unit_fee_fen" field.
	DefaultUnitFeeFen int64
	// DefaultFeeFen holds the default value on creation for the "fee_fen" field.
	DefaultFeeFen int64
	// PosCodeValidator is a validator for the "pos_code" field. It is called by the builders before save.
	PosCodeValidator func(string) error
	// ProjectValidator is a validator for the "project" field. It is called by the builders before save.
	ProjectValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the CDR queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeviceCode orders the results by the device_code field.
func ByDeviceCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceCode, opts...).ToFunc()
}

// ByDeviceType orders the results by the device_type field.
func ByDeviceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceType, opts...).ToFunc()
}

// ByLastDataValue orders the results by the last_data_value field.
func ByLastDataValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDataValue, opts...).ToFunc()
}

// ByDataValue orders the results by the data_value field.
func ByDataValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataValue, opts...).ToFunc()
}

// ByLastDataCode orders the results by the last_data_code field.
func ByLastDataCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDataCode, opts...).ToFunc()
}

// ByDataCode orders the results by the data_code field.
func ByDataCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataCode, opts...).ToFunc()
}

// ByLastDataTime orders the results by the last_data_time field.
func ByLastDataTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDataTime, opts...).ToFunc()
}

// ByDataTime orders the results by the data_time field.
func ByDataTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataTime, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByRuleType orders the results by the rule_type field.
func ByRuleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleType, opts...).ToFunc()
}

// ByRuleCtg orders the results by the rule_ctg field.
func ByRuleCtg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleCtg, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByUnitFeeFen orders the results by the unit_fee_fen field.
func ByUnitFeeFen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitFeeFen, opts...).ToFunc()
}

// ByFeeFen orders the results by the fee_fen field.
func ByFeeFen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeFen, opts...).ToFunc()
}

// ByPosCode orders the results by the pos_code field.
func ByPosCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosCode, opts...).ToFunc()
}

// ByProject orders the results by the project field.
func ByProject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProject, opts...).ToFunc()
}

// ByMemo orders the results by the memo field.
func ByMemo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemo, opts...).ToFunc()
}
