// Code generated by ent, DO NOT EDIT.

package cdr

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/h2o/chrgg/orm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldUpdateTime, v))
}

// DeviceCode applies equality check predicate on the "device_code" field. It's identical to DeviceCodeEQ.
func DeviceCode(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDeviceCode, v))
}

// DeviceType applies equality check predicate on the "device_type" field. It's identical to DeviceTypeEQ.
func DeviceType(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDeviceType, v))
}

// LastDataValue applies equality check predicate on the "last_data_value" field. It's identical to LastDataValueEQ.
func LastDataValue(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldLastDataValue, v))
}

// DataValue applies equality check predicate on the "data_value" field. It's identical to DataValueEQ.
func DataValue(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDataValue, v))
}

// LastDataCode applies equality check predicate on the "last_data_code" field. It's identical to LastDataCodeEQ.
func LastDataCode(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldLastDataCode, v))
}

// DataCode applies equality check predicate on the "data_code" field. It's identical to DataCodeEQ.
func DataCode(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDataCode, v))
}

// LastDataTime applies equality check predicate on the "last_data_time" field. It's identical to LastDataTimeEQ.
func LastDataTime(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldLastDataTime, v))
}

// DataTime applies equality check predicate on the "data_time" field. It's identical to DataTimeEQ.
func DataTime(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDataTime, v))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldRuleID, v))
}

// RuleType applies equality check predicate on the "rule_type" field. It's identical to RuleTypeEQ.
func RuleType(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldRuleType, v))
}

// RuleCtg applies equality check predicate on the "rule_ctg" field. It's identical to RuleCtgEQ.
func RuleCtg(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldRuleCtg, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldValue, v))
}

// UnitFeeFen applies equality check predicate on the "unit_fee_fen" field. It's identical to UnitFeeFenEQ.
func UnitFeeFen(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldUnitFeeFen, v))
}

// FeeFen applies equality check predicate on the "fee_fen" field. It's identical to FeeFenEQ.
func FeeFen(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldFeeFen, v))
}

// PosCode applies equality check predicate on the "pos_code" field. It's identical to PosCodeEQ.
func PosCode(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldPosCode, v))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldProject, v))
}

// Memo applies equality check predicate on the "memo" field. It's identical to MemoEQ.
func Memo(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldMemo, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldUpdateTime, v))
}

// DeviceCodeEQ applies the EQ predicate on the "device_code" field.
func DeviceCodeEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDeviceCode, v))
}

// DeviceCodeNEQ applies the NEQ predicate on the "device_code" field.
func DeviceCodeNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldDeviceCode, v))
}

// DeviceCodeIn applies the In predicate on the "device_code" field.
func DeviceCodeIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldDeviceCode, vs...))
}

// DeviceCodeNotIn applies the NotIn predicate on the "device_code" field.
func DeviceCodeNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldDeviceCode, vs...))
}

// DeviceCodeGT applies the GT predicate on the "device_code" field.
func DeviceCodeGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldDeviceCode, v))
}

// DeviceCodeGTE applies the GTE predicate on the "device_code" field.
func DeviceCodeGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldDeviceCode, v))
}

// DeviceCodeLT applies the LT predicate on the "device_code" field.
func DeviceCodeLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldDeviceCode, v))
}

// DeviceCodeLTE applies the LTE predicate on the "device_code" field.
func DeviceCodeLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldDeviceCode, v))
}

// DeviceCodeContains applies the Contains predicate on the "device_code" field.
func DeviceCodeContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldDeviceCode, v))
}

// DeviceCodeHasPrefix applies the HasPrefix predicate on the "device_code" field.
func DeviceCodeHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldDeviceCode, v))
}

// DeviceCodeHasSuffix applies the HasSuffix predicate on the "device_code" field.
func DeviceCodeHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldDeviceCode, v))
}

// DeviceCodeEqualFold applies the EqualFold predicate on the "device_code" field.
func DeviceCodeEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldDeviceCode, v))
}

// DeviceCodeContainsFold applies the ContainsFold predicate on the "device_code" field.
func DeviceCodeContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldDeviceCode, v))
}

// DeviceTypeEQ applies the EQ predicate on the "device_type" field.
func DeviceTypeEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDeviceType, v))
}

// DeviceTypeNEQ applies the NEQ predicate on the "device_type" field.
func DeviceTypeNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldDeviceType, v))
}

// DeviceTypeIn applies the In predicate on the "device_type" field.
func DeviceTypeIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldDeviceType, vs...))
}

// DeviceTypeNotIn applies the NotIn predicate on the "device_type" field.
func DeviceTypeNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldDeviceType, vs...))
}

// DeviceTypeGT applies the GT predicate on the "device_type" field.
func DeviceTypeGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldDeviceType, v))
}

// DeviceTypeGTE applies the GTE predicate on the "device_type" field.
func DeviceTypeGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldDeviceType, v))
}

// DeviceTypeLT applies the LT predicate on the "device_type" field.
func DeviceTypeLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldDeviceType, v))
}

// DeviceTypeLTE applies the LTE predicate on the "device_type" field.
func DeviceTypeLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldDeviceType, v))
}

// DeviceTypeContains applies the Contains predicate on the "device_type" field.
func DeviceTypeContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldDeviceType, v))
}

// DeviceTypeHasPrefix applies the HasPrefix predicate on the "device_type" field.
func DeviceTypeHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldDeviceType, v))
}

// DeviceTypeHasSuffix applies the HasSuffix predicate on the "device_type" field.
func DeviceTypeHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldDeviceType, v))
}

// DeviceTypeEqualFold applies the EqualFold predicate on the "device_type" field.
func DeviceTypeEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldDeviceType, v))
}

// DeviceTypeContainsFold applies the ContainsFold predicate on the "device_type" field.
func DeviceTypeContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldDeviceType, v))
}

// LastDataValueEQ applies the EQ predicate on the "last_data_value" field.
func LastDataValueEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldLastDataValue, v))
}

// LastDataValueNEQ applies the NEQ predicate on the "last_data_value" field.
func LastDataValueNEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldLastDataValue, v))
}

// LastDataValueIn applies the In predicate on the "last_data_value" field.
func LastDataValueIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldLastDataValue, vs...))
}

// LastDataValueNotIn applies the NotIn predicate on the "last_data_value" field.
func LastDataValueNotIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldLastDataValue, vs...))
}

// LastDataValueGT applies the GT predicate on the "last_data_value" field.
func LastDataValueGT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldLastDataValue, v))
}

// LastDataValueGTE applies the GTE predicate on the "last_data_value" field.
func LastDataValueGTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldLastDataValue, v))
}

// LastDataValueLT applies the LT predicate on the "last_data_value" field.
func LastDataValueLT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldLastDataValue, v))
}

// LastDataValueLTE applies the LTE predicate on the "last_data_value" field.
func LastDataValueLTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldLastDataValue, v))
}

// DataValueEQ applies the EQ predicate on the "data_value" field.
func DataValueEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDataValue, v))
}

// DataValueNEQ applies the NEQ predicate on the "data_value" field.
func DataValueNEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldDataValue, v))
}

// DataValueIn applies the In predicate on the "data_value" field.
func DataValueIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldDataValue, vs...))
}

// DataValueNotIn applies the NotIn predicate on the "data_value" field.
func DataValueNotIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldDataValue, vs...))
}

// DataValueGT applies the GT predicate on the "data_value" field.
func DataValueGT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldDataValue, v))
}

// DataValueGTE applies the GTE predicate on the "data_value" field.
func DataValueGTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldDataValue, v))
}

// DataValueLT applies the LT predicate on the "data_value" field.
func DataValueLT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldDataValue, v))
}

// DataValueLTE applies the LTE predicate on the "data_value" field.
func DataValueLTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldDataValue, v))
}

// LastDataCodeEQ applies the EQ predicate on the "last_data_code" field.
func LastDataCodeEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldLastDataCode, v))
}

// LastDataCodeNEQ applies the NEQ predicate on the "last_data_code" field.
func LastDataCodeNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldLastDataCode, v))
}

// LastDataCodeIn applies the In predicate on the "last_data_code" field.
func LastDataCodeIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldLastDataCode, vs...))
}

// LastDataCodeNotIn applies the NotIn predicate on the "last_data_code" field.
func LastDataCodeNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldLastDataCode, vs...))
}

// LastDataCodeGT applies the GT predicate on the "last_data_code" field.
func LastDataCodeGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldLastDataCode, v))
}

// LastDataCodeGTE applies the GTE predicate on the "last_data_code" field.
func LastDataCodeGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldLastDataCode, v))
}

// LastDataCodeLT applies the LT predicate on the "last_data_code" field.
func LastDataCodeLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldLastDataCode, v))
}

// LastDataCodeLTE applies the LTE predicate on the "last_data_code" field.
func LastDataCodeLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldLastDataCode, v))
}

// LastDataCodeContains applies the Contains predicate on the "last_data_code" field.
func LastDataCodeContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldLastDataCode, v))
}

// LastDataCodeHasPrefix applies the HasPrefix predicate on the "last_data_code" field.
func LastDataCodeHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldLastDataCode, v))
}

// LastDataCodeHasSuffix applies the HasSuffix predicate on the "last_data_code" field.
func LastDataCodeHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldLastDataCode, v))
}

// LastDataCodeEqualFold applies the EqualFold predicate on the "last_data_code" field.
func LastDataCodeEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldLastDataCode, v))
}

// LastDataCodeContainsFold applies the ContainsFold predicate on the "last_data_code" field.
func LastDataCodeContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldLastDataCode, v))
}

// DataCodeEQ applies the EQ predicate on the "data_code" field.
func DataCodeEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDataCode, v))
}

// DataCodeNEQ applies the NEQ predicate on the "data_code" field.
func DataCodeNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldDataCode, v))
}

// DataCodeIn applies the In predicate on the "data_code" field.
func DataCodeIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldDataCode, vs...))
}

// DataCodeNotIn applies the NotIn predicate on the "data_code" field.
func DataCodeNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldDataCode, vs...))
}

// DataCodeGT applies the GT predicate on the "data_code" field.
func DataCodeGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldDataCode, v))
}

// DataCodeGTE applies the GTE predicate on the "data_code" field.
func DataCodeGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldDataCode, v))
}

// DataCodeLT applies the LT predicate on the "data_code" field.
func DataCodeLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldDataCode, v))
}

// DataCodeLTE applies the LTE predicate on the "data_code" field.
func DataCodeLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldDataCode, v))
}

// DataCodeContains applies the Contains predicate on the "data_code" field.
func DataCodeContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldDataCode, v))
}

// DataCodeHasPrefix applies the HasPrefix predicate on the "data_code" field.
func DataCodeHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldDataCode, v))
}

// DataCodeHasSuffix applies the HasSuffix predicate on the "data_code" field.
func DataCodeHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldDataCode, v))
}

// DataCodeEqualFold applies the EqualFold predicate on the "data_code" field.
func DataCodeEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldDataCode, v))
}

// DataCodeContainsFold applies the ContainsFold predicate on the "data_code" field.
func DataCodeContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldDataCode, v))
}

// LastDataTimeEQ applies the EQ predicate on the "last_data_time" field.
func LastDataTimeEQ(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldLastDataTime, v))
}

// LastDataTimeNEQ applies the NEQ predicate on the "last_data_time" field.
func LastDataTimeNEQ(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldLastDataTime, v))
}

// LastDataTimeIn applies the In predicate on the "last_data_time" field.
func LastDataTimeIn(vs ...time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldLastDataTime, vs...))
}

// LastDataTimeNotIn applies the NotIn predicate on the "last_data_time" field.
func LastDataTimeNotIn(vs ...time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldLastDataTime, vs...))
}

// LastDataTimeGT applies the GT predicate on the "last_data_time" field.
func LastDataTimeGT(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldLastDataTime, v))
}

// LastDataTimeGTE applies the GTE predicate on the "last_data_time" field.
func LastDataTimeGTE(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldLastDataTime, v))
}

// LastDataTimeLT applies the LT predicate on the "last_data_time" field.
func LastDataTimeLT(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldLastDataTime, v))
}

// LastDataTimeLTE applies the LTE predicate on the "last_data_time" field.
func LastDataTimeLTE(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldLastDataTime, v))
}

// DataTimeEQ applies the EQ predicate on the "data_time" field.
func DataTimeEQ(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldDataTime, v))
}

// DataTimeNEQ applies the NEQ predicate on the "data_time" field.
func DataTimeNEQ(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldDataTime, v))
}

// DataTimeIn applies the In predicate on the "data_time" field.
func DataTimeIn(vs ...time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldDataTime, vs...))
}

// DataTimeNotIn applies the NotIn predicate on the "data_time" field.
func DataTimeNotIn(vs ...time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldDataTime, vs...))
}

// DataTimeGT applies the GT predicate on the "data_time" field.
func DataTimeGT(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldDataTime, v))
}

// DataTimeGTE applies the GTE predicate on the "data_time" field.
func DataTimeGTE(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldDataTime, v))
}

// DataTimeLT applies the LT predicate on the "data_time" field.
func DataTimeLT(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldDataTime, v))
}

// DataTimeLTE applies the LTE predicate on the "data_time" field.
func DataTimeLTE(v time.Time) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldDataTime, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDGT applies the GT predicate on the "rule_id" field.
func RuleIDGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldRuleID, v))
}

// RuleIDGTE applies the GTE predicate on the "rule_id" field.
func RuleIDGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldRuleID, v))
}

// RuleIDLT applies the LT predicate on the "rule_id" field.
func RuleIDLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldRuleID, v))
}

// RuleIDLTE applies the LTE predicate on the "rule_id" field.
func RuleIDLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldRuleID, v))
}

// RuleIDContains applies the Contains predicate on the "rule_id" field.
func RuleIDContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldRuleID, v))
}

// RuleIDHasPrefix applies the HasPrefix predicate on the "rule_id" field.
func RuleIDHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldRuleID, v))
}

// RuleIDHasSuffix applies the HasSuffix predicate on the "rule_id" field.
func RuleIDHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldRuleID, v))
}

// RuleIDEqualFold applies the EqualFold predicate on the "rule_id" field.
func RuleIDEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldRuleID, v))
}

// RuleIDContainsFold applies the ContainsFold predicate on the "rule_id" field.
func RuleIDContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldRuleID, v))
}

// RuleTypeEQ applies the EQ predicate on the "rule_type" field.
func RuleTypeEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldRuleType, v))
}

// RuleTypeNEQ applies the NEQ predicate on the "rule_type" field.
func RuleTypeNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldRuleType, v))
}

// RuleTypeIn applies the In predicate on the "rule_type" field.
func RuleTypeIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldRuleType, vs...))
}

// RuleTypeNotIn applies the NotIn predicate on the "rule_type" field.
func RuleTypeNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldRuleType, vs...))
}

// RuleTypeGT applies the GT predicate on the "rule_type" field.
func RuleTypeGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldRuleType, v))
}

// RuleTypeGTE applies the GTE predicate on the "rule_type" field.
func RuleTypeGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldRuleType, v))
}

// RuleTypeLT applies the LT predicate on the "rule_type" field.
func RuleTypeLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldRuleType, v))
}

// RuleTypeLTE applies the LTE predicate on the "rule_type" field.
func RuleTypeLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldRuleType, v))
}

// RuleTypeContains applies the Contains predicate on the "rule_type" field.
func RuleTypeContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldRuleType, v))
}

// RuleTypeHasPrefix applies the HasPrefix predicate on the "rule_type" field.
func RuleTypeHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldRuleType, v))
}

// RuleTypeHasSuffix applies the HasSuffix predicate on the "rule_type" field.
func RuleTypeHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldRuleType, v))
}

// RuleTypeEqualFold applies the EqualFold predicate on the "rule_type" field.
func RuleTypeEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldRuleType, v))
}

// RuleTypeContainsFold applies the ContainsFold predicate on the "rule_type" field.
func RuleTypeContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldRuleType, v))
}

// RuleCtgEQ applies the EQ predicate on the "rule_ctg" field.
func RuleCtgEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldRuleCtg, v))
}

// RuleCtgNEQ applies the NEQ predicate on the "rule_ctg" field.
func RuleCtgNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldRuleCtg, v))
}

// RuleCtgIn applies the In predicate on the "rule_ctg" field.
func RuleCtgIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldRuleCtg, vs...))
}

// RuleCtgNotIn applies the NotIn predicate on the "rule_ctg" field.
func RuleCtgNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldRuleCtg, vs...))
}

// RuleCtgGT applies the GT predicate on the "rule_ctg" field.
func RuleCtgGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldRuleCtg, v))
}

// RuleCtgGTE applies the GTE predicate on the "rule_ctg" field.
func RuleCtgGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldRuleCtg, v))
}

// RuleCtgLT applies the LT predicate on the "rule_ctg" field.
func RuleCtgLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldRuleCtg, v))
}

// RuleCtgLTE applies the LTE predicate on the "rule_ctg" field.
func RuleCtgLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldRuleCtg, v))
}

// RuleCtgContains applies the Contains predicate on the "rule_ctg" field.
func RuleCtgContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldRuleCtg, v))
}

// RuleCtgHasPrefix applies the HasPrefix predicate on the "rule_ctg" field.
func RuleCtgHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldRuleCtg, v))
}

// RuleCtgHasSuffix applies the HasSuffix predicate on the "rule_ctg" field.
func RuleCtgHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldRuleCtg, v))
}

// RuleCtgEqualFold applies the EqualFold predicate on the "rule_ctg" field.
func RuleCtgEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldRuleCtg, v))
}

// RuleCtgContainsFold applies the ContainsFold predicate on the "rule_ctg" field.
func RuleCtgContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldRuleCtg, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldValue, v))
}

// UnitFeeFenEQ applies the EQ predicate on the "unit_fee_fen" field.
func UnitFeeFenEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldUnitFeeFen, v))
}

// UnitFeeFenNEQ applies the NEQ predicate on the "unit_fee_fen" field.
func UnitFeeFenNEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldUnitFeeFen, v))
}

// UnitFeeFenIn applies the In predicate on the "unit_fee_fen" field.
func UnitFeeFenIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldUnitFeeFen, vs...))
}

// UnitFeeFenNotIn applies the NotIn predicate on the "unit_fee_fen" field.
func UnitFeeFenNotIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldUnitFeeFen, vs...))
}

// UnitFeeFenGT applies the GT predicate on the "unit_fee_fen" field.
func UnitFeeFenGT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldUnitFeeFen, v))
}

// UnitFeeFenGTE applies the GTE predicate on the "unit_fee_fen" field.
func UnitFeeFenGTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldUnitFeeFen, v))
}

// UnitFeeFenLT applies the LT predicate on the "unit_fee_fen" field.
func UnitFeeFenLT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldUnitFeeFen, v))
}

// UnitFeeFenLTE applies the LTE predicate on the "unit_fee_fen" field.
func UnitFeeFenLTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldUnitFeeFen, v))
}

// FeeFenEQ applies the EQ predicate on the "fee_fen" field.
func FeeFenEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldFeeFen, v))
}

// FeeFenNEQ applies the NEQ predicate on the "fee_fen" field.
func FeeFenNEQ(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldFeeFen, v))
}

// FeeFenIn applies the In predicate on the "fee_fen" field.
func FeeFenIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldFeeFen, vs...))
}

// FeeFenNotIn applies the NotIn predicate on the "fee_fen" field.
func FeeFenNotIn(vs ...int64) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldFeeFen, vs...))
}

// FeeFenGT applies the GT predicate on the "fee_fen" field.
func FeeFenGT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldFeeFen, v))
}

// FeeFenGTE applies the GTE predicate on the "fee_fen" field.
func FeeFenGTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldFeeFen, v))
}

// FeeFenLT applies the LT predicate on the "fee_fen" field.
func FeeFenLT(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldFeeFen, v))
}

// FeeFenLTE applies the LTE predicate on the "fee_fen" field.
func FeeFenLTE(v int64) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldFeeFen, v))
}

// PosCodeEQ applies the EQ predicate on the "pos_code" field.
func PosCodeEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldPosCode, v))
}

// PosCodeNEQ applies the NEQ predicate on the "pos_code" field.
func PosCodeNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldPosCode, v))
}

// PosCodeIn applies the In predicate on the "pos_code" field.
func PosCodeIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldPosCode, vs...))
}

// PosCodeNotIn applies the NotIn predicate on the "pos_code" field.
func PosCodeNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldPosCode, vs...))
}

// PosCodeGT applies the GT predicate on the "pos_code" field.
func PosCodeGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldPosCode, v))
}

// PosCodeGTE applies the GTE predicate on the "pos_code" field.
func PosCodeGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldPosCode, v))
}

// PosCodeLT applies the LT predicate on the "pos_code" field.
func PosCodeLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldPosCode, v))
}

// PosCodeLTE applies the LTE predicate on the "pos_code" field.
func PosCodeLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldPosCode, v))
}

// PosCodeContains applies the Contains predicate on the "pos_code" field.
func PosCodeContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldPosCode, v))
}

// PosCodeHasPrefix applies the HasPrefix predicate on the "pos_code" field.
func PosCodeHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldPosCode, v))
}

// PosCodeHasSuffix applies the HasSuffix predicate on the "pos_code" field.
func PosCodeHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldPosCode, v))
}

// PosCodeEqualFold applies the EqualFold predicate on the "pos_code" field.
func PosCodeEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldPosCode, v))
}

// PosCodeContainsFold applies the ContainsFold predicate on the "pos_code" field.
func PosCodeContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldPosCode, v))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldProject, v))
}

// MemoEQ applies the EQ predicate on the "memo" field.
func MemoEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEQ(FieldMemo, v))
}

// MemoNEQ applies the NEQ predicate on the "memo" field.
func MemoNEQ(v string) predicate.CDR {
	return predicate.CDR(sql.FieldNEQ(FieldMemo, v))
}

// MemoIn applies the In predicate on the "memo" field.
func MemoIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldIn(FieldMemo, vs...))
}

// MemoNotIn applies the NotIn predicate on the "memo" field.
func MemoNotIn(vs ...string) predicate.CDR {
	return predicate.CDR(sql.FieldNotIn(FieldMemo, vs...))
}

// MemoGT applies the GT predicate on the "memo" field.
func MemoGT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGT(FieldMemo, v))
}

// MemoGTE applies the GTE predicate on the "memo" field.
func MemoGTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldGTE(FieldMemo, v))
}

// MemoLT applies the LT predicate on the "memo" field.
func MemoLT(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLT(FieldMemo, v))
}

// MemoLTE applies the LTE predicate on the "memo" field.
func MemoLTE(v string) predicate.CDR {
	return predicate.CDR(sql.FieldLTE(FieldMemo, v))
}

// MemoContains applies the Contains predicate on the "memo" field.
func MemoContains(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContains(FieldMemo, v))
}

// MemoHasPrefix applies the HasPrefix predicate on the "memo" field.
func MemoHasPrefix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasPrefix(FieldMemo, v))
}

// MemoHasSuffix applies the HasSuffix predicate on the "memo" field.
func MemoHasSuffix(v string) predicate.CDR {
	return predicate.CDR(sql.FieldHasSuffix(FieldMemo, v))
}

// MemoEqualFold applies the EqualFold predicate on the "memo" field.
func MemoEqualFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldEqualFold(FieldMemo, v))
}

// MemoContainsFold applies the ContainsFold predicate on the "memo" field.
func MemoContainsFold(v string) predicate.CDR {
	return predicate.CDR(sql.FieldContainsFold(FieldMemo, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CDR) predicate.CDR {
	return predicate.CDR(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CDR) predicate.CDR {
	return predicate.CDR(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CDR) predicate.CDR {
	return predicate.CDR(sql.NotPredicates(p))
}
