// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/h2o/chrgg/orm/ent/cdr"
)

// CDRCreate is the builder for creating a CDR entity.
type CDRCreate struct {
	config
	mutation *CDRMutation
	hooks    []Hook
}

// SetDeviceCode sets the "device_code" field.
func (_c *CDRCreate) SetDeviceCode(v string) *CDRCreate {
	_c.mutation.SetDeviceCode(v)
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *CDRCreate) SetDeviceType(v string) *CDRCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetLastDataValue sets the "last_data_value" field.
func (_c *CDRCreate) SetLastDataValue(v int64) *CDRCreate {
	_c.mutation.SetLastDataValue(v)
	return _c
}

// SetDataValue sets the "data_value" field.
func (_c *CDRCreate) SetDataValue(v int64) *CDRCreate {
	_c.mutation.SetDataValue(v)
	return _c
}

// SetLastDataCode sets the "last_data_code" field.
func (_c *CDRCreate) SetLastDataCode(v string) *CDRCreate {
	_c.mutation.SetLastDataCode(v)
	return _c
}

// SetDataCode sets the "data_code" field.
func (_c *CDRCreate) SetDataCode(v string) *CDRCreate {
	_c.mutation.SetDataCode(v)
	return _c
}

// SetLastDataTime sets the "last_data_time" field.
func (_c *CDRCreate) SetLastDataTime(v time.Time) *CDRCreate {
	_c.mutation.SetLastDataTime(v)
	return _c
}

// SetDataTime sets the "data_time" field.
func (_c *CDRCreate) SetDataTime(v time.Time) *CDRCreate {
	_c.mutation.SetDataTime(v)
	return _c
}

// SetPloyID sets the "ploy_id" field.
func (_c *CDRCreate) SetPloyID(v string) *CDRCreate {
	_c.mutation.SetPloyID(v)
	return _c
}

// SetRuleID sets the "rule_id" field.
func (_c *CDRCreate) SetRuleID(v string) *CDRCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *CDRCreate) SetValue(v int64) *CDRCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetUnitFee sets the "unit_fee" field.
func (_c *CDRCreate) SetUnitFee(v int64) *CDRCreate {
	_c.mutation.SetUnitFee(v)
	return _c
}

// SetFee sets the "fee" field.
func (_c *CDRCreate) SetFee(v int64) *CDRCreate {
	_c.mutation.SetFee(v)
	return _c
}

// SetRemark sets the "remark" field.
func (_c *CDRCreate) SetRemark(v string) *CDRCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *CDRCreate) SetNillableRemark(v *string) *CDRCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CDRCreate) SetID(v string) *CDRCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CDRMutation object of the builder.
func (_c *CDRCreate) Mutation() *CDRMutation {
	return _c.mutation
}

// Save creates the CDR in the database.
func (_c *CDRCreate) Save(ctx context.Context) (*CDR, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CDRCreate) SaveX(ctx context.Context) *CDR {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CDRCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CDRCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CDRCreate) defaults() {
	if _, ok := _c.mutation.Remark(); !ok {
		v := cdr.DefaultRemark
		_c.mutation.SetRemark(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CDRCreate) check() error {
	if _, ok := _c.mutation.DeviceCode(); !ok {
		return &ValidationError{Name: "device_code", err: errors.New(`ent: missing required field "CDR.device_code"`)}
	}
	if _, ok := _c.mutation.DeviceType(); !ok {
		return &ValidationError{Name: "device_type", err: errors.New(`ent: missing required field "CDR.device_type"`)}
	}
	if _, ok := _c.mutation.LastDataValue(); !ok {
		return &ValidationError{Name: "last_data_value", err: errors.New(`ent: missing required field "CDR.last_data_value"`)}
	}
	if _, ok := _c.mutation.DataValue(); !ok {
		return &ValidationError{Name: "data_value", err: errors.New(`ent: missing required field "CDR.data_value"`)}
	}
	if _, ok := _c.mutation.LastDataCode(); !ok {
		return &ValidationError{Name: "last_data_code", err: errors.New(`ent: missing required field "CDR.last_data_code"`)}
	}
	if _, ok := _c.mutation.DataCode(); !ok {
		return &ValidationError{Name: "data_code", err: errors.New(`ent: missing required field "CDR.data_code"`)}
	}
	if _, ok := _c.mutation.LastDataTime(); !ok {
		return &ValidationError{Name: "last_data_time", err: errors.New(`ent: missing required field "CDR.last_data_time"`)}
	}
	if _, ok := _c.mutation.DataTime(); !ok {
		return &ValidationError{Name: "data_time", err: errors.New(`ent: missing required field "CDR.data_time"`)}
	}
	if _, ok := _c.mutation.PloyID(); !ok {
		return &ValidationError{Name: "ploy_id", err: errors.New(`ent: missing required field "CDR.ploy_id"`)}
	}
	if _, ok := _c.mutation.RuleID(); !ok {
		return &ValidationError{Name: "rule_id", err: errors.New(`ent: missing required field "CDR.rule_id"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "CDR.value"`)}
	}
	if _, ok := _c.mutation.UnitFee(); !ok {
		return &ValidationError{Name: "unit_fee", err: errors.New(`ent: missing required field "CDR.unit_fee"`)}
	}
	if _, ok := _c.mutation.Fee(); !ok {
		return &ValidationError{Name: "fee", err: errors.New(`ent: missing required field "CDR.fee"`)}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "CDR.remark"`)}
	}
	return nil
}

func (_c *CDRCreate) sqlSave(ctx context.Context) (*CDR, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CDR.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CDRCreate) createSpec() (*CDR, *sqlgraph.CreateSpec) {
	var (
		_node = &CDR{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cdr.Table, sqlgraph.NewFieldSpec(cdr.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeviceCode(); ok {
		_spec.SetField(cdr.FieldDeviceCode, field.TypeString, value)
		_node.DeviceCode = value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(cdr.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = value
	}
	if value, ok := _c.mutation.LastDataValue(); ok {
		_spec.SetField(cdr.FieldLastDataValue, field.TypeInt64, value)
		_node.LastDataValue = value
	}
	if value, ok := _c.mutation.DataValue(); ok {
		_spec.SetField(cdr.FieldDataValue, field.TypeInt64, value)
		_node.DataValue = value
	}
	if value, ok := _c.mutation.LastDataCode(); ok {
		_spec.SetField(cdr.FieldLastDataCode, field.TypeString, value)
		_node.LastDataCode = value
	}
	if value, ok := _c.mutation.DataCode(); ok {
		_spec.SetField(cdr.FieldDataCode, field.TypeString, value)
		_node.DataCode = value
	}
	if value, ok := _c.mutation.LastDataTime(); ok {
		_spec.SetField(cdr.FieldLastDataTime, field.TypeTime, value)
		_node.LastDataTime = value
	}
	if value, ok := _c.mutation.DataTime(); ok {
		_spec.SetField(cdr.FieldDataTime, field.TypeTime, value)
		_node.DataTime = value
	}
	if value, ok := _c.mutation.PloyID(); ok {
		_spec.SetField(cdr.FieldPloyID, field.TypeString, value)
		_node.PloyID = value
	}
	if value, ok := _c.mutation.RuleID(); ok {
		_spec.SetField(cdr.FieldRuleID, field.TypeString, value)
		_node.RuleID = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(cdr.FieldValue, field.TypeInt64, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.UnitFee(); ok {
		_spec.SetField(cdr.FieldUnitFee, field.TypeInt64, value)
		_node.UnitFee = value
	}
	if value, ok := _c.mutation.Fee(); ok {
		_spec.SetField(cdr.FieldFee, field.TypeInt64, value)
		_node.Fee = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(cdr.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	return _node, _spec
}

// CDRCreateBulk is the builder for creating many CDR entities in bulk.
type CDRCreateBulk struct {
	config
	err      error
	builders []*CDRCreate
}

// Save creates the CDR entities in the database.
func (_c *CDRCreateBulk) Save(ctx context.Context) ([]*CDR, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CDR, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CDRMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CDRCreateBulk) SaveX(ctx context.Context) []*CDR {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CDRCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CDRCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
