// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/h2o/chrgg/orm/ent/cdr"
	"github.com/twiglab/h2o/chrgg/orm/ent/predicate"
)

// CDRUpdate is the builder for updating CDR entities.
type CDRUpdate struct {
	config
	hooks    []Hook
	mutation *CDRMutation
}

// Where appends a list predicates to the CDRUpdate builder.
func (_u *CDRUpdate) Where(ps ...predicate.CDR) *CDRUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *CDRUpdate) SetUpdateTime(v time.Time) *CDRUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetDeviceCode sets the "device_code" field.
func (_u *CDRUpdate) SetDeviceCode(v string) *CDRUpdate {
	_u.mutation.SetDeviceCode(v)
	return _u
}

// SetNillableDeviceCode sets the "device_code" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableDeviceCode(v *string) *CDRUpdate {
	if v != nil {
		_u.SetDeviceCode(*v)
	}
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *CDRUpdate) SetDeviceType(v string) *CDRUpdate {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableDeviceType(v *string) *CDRUpdate {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// SetLastDataValue sets the "last_data_value" field.
func (_u *CDRUpdate) SetLastDataValue(v int64) *CDRUpdate {
	_u.mutation.ResetLastDataValue()
	_u.mutation.SetLastDataValue(v)
	return _u
}

// SetNillableLastDataValue sets the "last_data_value" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableLastDataValue(v *int64) *CDRUpdate {
	if v != nil {
		_u.SetLastDataValue(*v)
	}
	return _u
}

// AddLastDataValue adds value to the "last_data_value" field.
func (_u *CDRUpdate) AddLastDataValue(v int64) *CDRUpdate {
	_u.mutation.AddLastDataValue(v)
	return _u
}

// SetDataValue sets the "data_value" field.
func (_u *CDRUpdate) SetDataValue(v int64) *CDRUpdate {
	_u.mutation.ResetDataValue()
	_u.mutation.SetDataValue(v)
	return _u
}

// SetNillableDataValue sets the "data_value" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableDataValue(v *int64) *CDRUpdate {
	if v != nil {
		_u.SetDataValue(*v)
	}
	return _u
}

// AddDataValue adds value to the "data_value" field.
func (_u *CDRUpdate) AddDataValue(v int64) *CDRUpdate {
	_u.mutation.AddDataValue(v)
	return _u
}

// SetLastDataCode sets the "last_data_code" field.
func (_u *CDRUpdate) SetLastDataCode(v string) *CDRUpdate {
	_u.mutation.SetLastDataCode(v)
	return _u
}

// SetNillableLastDataCode sets the "last_data_code" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableLastDataCode(v *string) *CDRUpdate {
	if v != nil {
		_u.SetLastDataCode(*v)
	}
	return _u
}

// SetDataCode sets the "data_code" field.
func (_u *CDRUpdate) SetDataCode(v string) *CDRUpdate {
	_u.mutation.SetDataCode(v)
	return _u
}

// SetNillableDataCode sets the "data_code" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableDataCode(v *string) *CDRUpdate {
	if v != nil {
		_u.SetDataCode(*v)
	}
	return _u
}

// SetLastDataTime sets the "last_data_time" field.
func (_u *CDRUpdate) SetLastDataTime(v time.Time) *CDRUpdate {
	_u.mutation.SetLastDataTime(v)
	return _u
}

// SetNillableLastDataTime sets the "last_data_time" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableLastDataTime(v *time.Time) *CDRUpdate {
	if v != nil {
		_u.SetLastDataTime(*v)
	}
	return _u
}

// SetDataTime sets the "data_time" field.
func (_u *CDRUpdate) SetDataTime(v time.Time) *CDRUpdate {
	_u.mutation.SetDataTime(v)
	return _u
}

// SetNillableDataTime sets the "data_time" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableDataTime(v *time.Time) *CDRUpdate {
	if v != nil {
		_u.SetDataTime(*v)
	}
	return _u
}

// SetPloyID sets the "ploy_id" field.
func (_u *CDRUpdate) SetPloyID(v string) *CDRUpdate {
	_u.mutation.SetPloyID(v)
	return _u
}

// SetNillablePloyID sets the "ploy_id" field if the given value is not nil.
func (_u *CDRUpdate) SetNillablePloyID(v *string) *CDRUpdate {
	if v != nil {
		_u.SetPloyID(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *CDRUpdate) SetRuleID(v string) *CDRUpdate {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableRuleID(v *string) *CDRUpdate {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *CDRUpdate) SetValue(v int64) *CDRUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableValue(v *int64) *CDRUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *CDRUpdate) AddValue(v int64) *CDRUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetUnitFee sets the "unit_fee" field.
func (_u *CDRUpdate) SetUnitFee(v int64) *CDRUpdate {
	_u.mutation.ResetUnitFee()
	_u.mutation.SetUnitFee(v)
	return _u
}

// SetNillableUnitFee sets the "unit_fee" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableUnitFee(v *int64) *CDRUpdate {
	if v != nil {
		_u.SetUnitFee(*v)
	}
	return _u
}

// AddUnitFee adds value to the "unit_fee" field.
func (_u *CDRUpdate) AddUnitFee(v int64) *CDRUpdate {
	_u.mutation.AddUnitFee(v)
	return _u
}

// SetFee sets the "fee" field.
func (_u *CDRUpdate) SetFee(v int64) *CDRUpdate {
	_u.mutation.ResetFee()
	_u.mutation.SetFee(v)
	return _u
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableFee(v *int64) *CDRUpdate {
	if v != nil {
		_u.SetFee(*v)
	}
	return _u
}

// AddFee adds value to the "fee" field.
func (_u *CDRUpdate) AddFee(v int64) *CDRUpdate {
	_u.mutation.AddFee(v)
	return _u
}

// SetPosCode sets the "pos_code" field.
func (_u *CDRUpdate) SetPosCode(v string) *CDRUpdate {
	_u.mutation.SetPosCode(v)
	return _u
}

// SetNillablePosCode sets the "pos_code" field if the given value is not nil.
func (_u *CDRUpdate) SetNillablePosCode(v *string) *CDRUpdate {
	if v != nil {
		_u.SetPosCode(*v)
	}
	return _u
}

// SetProject sets the "project" field.
func (_u *CDRUpdate) SetProject(v string) *CDRUpdate {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableProject(v *string) *CDRUpdate {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// SetTime sets the "time" field.
func (_u *CDRUpdate) SetTime(v time.Time) *CDRUpdate {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableTime(v *time.Time) *CDRUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *CDRUpdate) SetRemark(v string) *CDRUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *CDRUpdate) SetNillableRemark(v *string) *CDRUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// Mutation returns the CDRMutation object of the builder.
func (_u *CDRUpdate) Mutation() *CDRMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CDRUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CDRUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CDRUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CDRUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CDRUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := cdr.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *CDRUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cdr.Table, cdr.Columns, sqlgraph.NewFieldSpec(cdr.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(cdr.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeviceCode(); ok {
		_spec.SetField(cdr.FieldDeviceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(cdr.FieldDeviceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastDataValue(); ok {
		_spec.SetField(cdr.FieldLastDataValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastDataValue(); ok {
		_spec.AddField(cdr.FieldLastDataValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DataValue(); ok {
		_spec.SetField(cdr.FieldDataValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDataValue(); ok {
		_spec.AddField(cdr.FieldDataValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastDataCode(); ok {
		_spec.SetField(cdr.FieldLastDataCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataCode(); ok {
		_spec.SetField(cdr.FieldDataCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastDataTime(); ok {
		_spec.SetField(cdr.FieldLastDataTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DataTime(); ok {
		_spec.SetField(cdr.FieldDataTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PloyID(); ok {
		_spec.SetField(cdr.FieldPloyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(cdr.FieldRuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(cdr.FieldValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(cdr.FieldValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UnitFee(); ok {
		_spec.SetField(cdr.FieldUnitFee, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnitFee(); ok {
		_spec.AddField(cdr.FieldUnitFee, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Fee(); ok {
		_spec.SetField(cdr.FieldFee, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFee(); ok {
		_spec.AddField(cdr.FieldFee, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PosCode(); ok {
		_spec.SetField(cdr.FieldPosCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(cdr.FieldProject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(cdr.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(cdr.FieldRemark, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cdr.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CDRUpdateOne is the builder for updating a single CDR entity.
type CDRUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CDRMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *CDRUpdateOne) SetUpdateTime(v time.Time) *CDRUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetDeviceCode sets the "device_code" field.
func (_u *CDRUpdateOne) SetDeviceCode(v string) *CDRUpdateOne {
	_u.mutation.SetDeviceCode(v)
	return _u
}

// SetNillableDeviceCode sets the "device_code" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableDeviceCode(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetDeviceCode(*v)
	}
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *CDRUpdateOne) SetDeviceType(v string) *CDRUpdateOne {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableDeviceType(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// SetLastDataValue sets the "last_data_value" field.
func (_u *CDRUpdateOne) SetLastDataValue(v int64) *CDRUpdateOne {
	_u.mutation.ResetLastDataValue()
	_u.mutation.SetLastDataValue(v)
	return _u
}

// SetNillableLastDataValue sets the "last_data_value" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableLastDataValue(v *int64) *CDRUpdateOne {
	if v != nil {
		_u.SetLastDataValue(*v)
	}
	return _u
}

// AddLastDataValue adds value to the "last_data_value" field.
func (_u *CDRUpdateOne) AddLastDataValue(v int64) *CDRUpdateOne {
	_u.mutation.AddLastDataValue(v)
	return _u
}

// SetDataValue sets the "data_value" field.
func (_u *CDRUpdateOne) SetDataValue(v int64) *CDRUpdateOne {
	_u.mutation.ResetDataValue()
	_u.mutation.SetDataValue(v)
	return _u
}

// SetNillableDataValue sets the "data_value" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableDataValue(v *int64) *CDRUpdateOne {
	if v != nil {
		_u.SetDataValue(*v)
	}
	return _u
}

// AddDataValue adds value to the "data_value" field.
func (_u *CDRUpdateOne) AddDataValue(v int64) *CDRUpdateOne {
	_u.mutation.AddDataValue(v)
	return _u
}

// SetLastDataCode sets the "last_data_code" field.
func (_u *CDRUpdateOne) SetLastDataCode(v string) *CDRUpdateOne {
	_u.mutation.SetLastDataCode(v)
	return _u
}

// SetNillableLastDataCode sets the "last_data_code" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableLastDataCode(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetLastDataCode(*v)
	}
	return _u
}

// SetDataCode sets the "data_code" field.
func (_u *CDRUpdateOne) SetDataCode(v string) *CDRUpdateOne {
	_u.mutation.SetDataCode(v)
	return _u
}

// SetNillableDataCode sets the "data_code" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableDataCode(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetDataCode(*v)
	}
	return _u
}

// SetLastDataTime sets the "last_data_time" field.
func (_u *CDRUpdateOne) SetLastDataTime(v time.Time) *CDRUpdateOne {
	_u.mutation.SetLastDataTime(v)
	return _u
}

// SetNillableLastDataTime sets the "last_data_time" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableLastDataTime(v *time.Time) *CDRUpdateOne {
	if v != nil {
		_u.SetLastDataTime(*v)
	}
	return _u
}

// SetDataTime sets the "data_time" field.
func (_u *CDRUpdateOne) SetDataTime(v time.Time) *CDRUpdateOne {
	_u.mutation.SetDataTime(v)
	return _u
}

// SetNillableDataTime sets the "data_time" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableDataTime(v *time.Time) *CDRUpdateOne {
	if v != nil {
		_u.SetDataTime(*v)
	}
	return _u
}

// SetPloyID sets the "ploy_id" field.
func (_u *CDRUpdateOne) SetPloyID(v string) *CDRUpdateOne {
	_u.mutation.SetPloyID(v)
	return _u
}

// SetNillablePloyID sets the "ploy_id" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillablePloyID(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetPloyID(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *CDRUpdateOne) SetRuleID(v string) *CDRUpdateOne {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableRuleID(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *CDRUpdateOne) SetValue(v int64) *CDRUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableValue(v *int64) *CDRUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *CDRUpdateOne) AddValue(v int64) *CDRUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetUnitFee sets the "unit_fee" field.
func (_u *CDRUpdateOne) SetUnitFee(v int64) *CDRUpdateOne {
	_u.mutation.ResetUnitFee()
	_u.mutation.SetUnitFee(v)
	return _u
}

// SetNillableUnitFee sets the "unit_fee" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableUnitFee(v *int64) *CDRUpdateOne {
	if v != nil {
		_u.SetUnitFee(*v)
	}
	return _u
}

// AddUnitFee adds value to the "unit_fee" field.
func (_u *CDRUpdateOne) AddUnitFee(v int64) *CDRUpdateOne {
	_u.mutation.AddUnitFee(v)
	return _u
}

// SetFee sets the "fee" field.
func (_u *CDRUpdateOne) SetFee(v int64) *CDRUpdateOne {
	_u.mutation.ResetFee()
	_u.mutation.SetFee(v)
	return _u
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableFee(v *int64) *CDRUpdateOne {
	if v != nil {
		_u.SetFee(*v)
	}
	return _u
}

// AddFee adds value to the "fee" field.
func (_u *CDRUpdateOne) AddFee(v int64) *CDRUpdateOne {
	_u.mutation.AddFee(v)
	return _u
}

// SetPosCode sets the "pos_code" field.
func (_u *CDRUpdateOne) SetPosCode(v string) *CDRUpdateOne {
	_u.mutation.SetPosCode(v)
	return _u
}

// SetNillablePosCode sets the "pos_code" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillablePosCode(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetPosCode(*v)
	}
	return _u
}

// SetProject sets the "project" field.
func (_u *CDRUpdateOne) SetProject(v string) *CDRUpdateOne {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableProject(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// SetTime sets the "time" field.
func (_u *CDRUpdateOne) SetTime(v time.Time) *CDRUpdateOne {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableTime(v *time.Time) *CDRUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *CDRUpdateOne) SetRemark(v string) *CDRUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *CDRUpdateOne) SetNillableRemark(v *string) *CDRUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// Mutation returns the CDRMutation object of the builder.
func (_u *CDRUpdateOne) Mutation() *CDRMutation {
	return _u.mutation
}

// Where appends a list predicates to the CDRUpdate builder.
func (_u *CDRUpdateOne) Where(ps ...predicate.CDR) *CDRUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CDRUpdateOne) Select(field string, fields ...string) *CDRUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CDR entity.
func (_u *CDRUpdateOne) Save(ctx context.Context) (*CDR, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CDRUpdateOne) SaveX(ctx context.Context) *CDR {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CDRUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CDRUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CDRUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := cdr.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *CDRUpdateOne) sqlSave(ctx context.Context) (_node *CDR, err error) {
	_spec := sqlgraph.NewUpdateSpec(cdr.Table, cdr.Columns, sqlgraph.NewFieldSpec(cdr.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CDR.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cdr.FieldID)
		for _, f := range fields {
			if !cdr.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cdr.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(cdr.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeviceCode(); ok {
		_spec.SetField(cdr.FieldDeviceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(cdr.FieldDeviceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastDataValue(); ok {
		_spec.SetField(cdr.FieldLastDataValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastDataValue(); ok {
		_spec.AddField(cdr.FieldLastDataValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DataValue(); ok {
		_spec.SetField(cdr.FieldDataValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDataValue(); ok {
		_spec.AddField(cdr.FieldDataValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastDataCode(); ok {
		_spec.SetField(cdr.FieldLastDataCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataCode(); ok {
		_spec.SetField(cdr.FieldDataCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastDataTime(); ok {
		_spec.SetField(cdr.FieldLastDataTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DataTime(); ok {
		_spec.SetField(cdr.FieldDataTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PloyID(); ok {
		_spec.SetField(cdr.FieldPloyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(cdr.FieldRuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(cdr.FieldValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(cdr.FieldValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UnitFee(); ok {
		_spec.SetField(cdr.FieldUnitFee, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnitFee(); ok {
		_spec.AddField(cdr.FieldUnitFee, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Fee(); ok {
		_spec.SetField(cdr.FieldFee, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFee(); ok {
		_spec.AddField(cdr.FieldFee, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PosCode(); ok {
		_spec.SetField(cdr.FieldPosCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(cdr.FieldProject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(cdr.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(cdr.FieldRemark, field.TypeString, value)
	}
	_node = &CDR{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cdr.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
