// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/twiglab/h2o/chrgg/orm/ent/cdr"
	"github.com/twiglab/h2o/chrgg/orm/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cdrFields := schema.CDR{}.Fields()
	_ = cdrFields
	// cdrDescRemark is the schema descriptor for remark field.
	cdrDescRemark := cdrFields[14].Descriptor()
	// cdr.DefaultRemark holds the default value on creation for the remark field.
	cdr.DefaultRemark = cdrDescRemark.Default.(string)
}
