// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/h2o/chrgg/orm/ent/valuecharge"
)

// ValueChargeCreate is the builder for creating a ValueCharge entity.
type ValueChargeCreate struct {
	config
	mutation *ValueChargeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *ValueChargeCreate) SetCreateTime(v time.Time) *ValueChargeCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableCreateTime(v *time.Time) *ValueChargeCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ValueChargeCreate) SetUpdateTime(v time.Time) *ValueChargeCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableUpdateTime(v *time.Time) *ValueChargeCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *ValueChargeCreate) SetCode(v string) *ValueChargeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDeviceCode sets the "device_code" field.
func (_c *ValueChargeCreate) SetDeviceCode(v string) *ValueChargeCreate {
	_c.mutation.SetDeviceCode(v)
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *ValueChargeCreate) SetDeviceType(v string) *ValueChargeCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetPosCode sets the "pos_code" field.
func (_c *ValueChargeCreate) SetPosCode(v string) *ValueChargeCreate {
	_c.mutation.SetPosCode(v)
	return _c
}

// SetProject sets the "project" field.
func (_c *ValueChargeCreate) SetProject(v string) *ValueChargeCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetOwner sets the "owner" field.
func (_c *ValueChargeCreate) SetOwner(v string) *ValueChargeCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableOwner(v *string) *ValueChargeCreate {
	if v != nil {
		_c.SetOwner(*v)
	}
	return _c
}

// SetTop sets the "top" field.
func (_c *ValueChargeCreate) SetTop(v int64) *ValueChargeCreate {
	_c.mutation.SetTop(v)
	return _c
}

// SetNillableTop sets the "top" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableTop(v *int64) *ValueChargeCreate {
	if v != nil {
		_c.SetTop(*v)
	}
	return _c
}

// SetStock sets the "stock" field.
func (_c *ValueChargeCreate) SetStock(v int64) *ValueChargeCreate {
	_c.mutation.SetStock(v)
	return _c
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableStock(v *int64) *ValueChargeCreate {
	if v != nil {
		_c.SetStock(*v)
	}
	return _c
}

// SetIncr sets the "incr" field.
func (_c *ValueChargeCreate) SetIncr(v int64) *ValueChargeCreate {
	_c.mutation.SetIncr(v)
	return _c
}

// SetNillableIncr sets the "incr" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableIncr(v *int64) *ValueChargeCreate {
	if v != nil {
		_c.SetIncr(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ValueChargeCreate) SetAmount(v int64) *ValueChargeCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableAmount(v *int64) *ValueChargeCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetUnitPrice sets the "unit_price" field.
func (_c *ValueChargeCreate) SetUnitPrice(v int64) *ValueChargeCreate {
	_c.mutation.SetUnitPrice(v)
	return _c
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableUnitPrice(v *int64) *ValueChargeCreate {
	if v != nil {
		_c.SetUnitPrice(*v)
	}
	return _c
}

// SetChargeTime sets the "charge_time" field.
func (_c *ValueChargeCreate) SetChargeTime(v time.Time) *ValueChargeCreate {
	_c.mutation.SetChargeTime(v)
	return _c
}

// SetChargeTs sets the "charge_ts" field.
func (_c *ValueChargeCreate) SetChargeTs(v string) *ValueChargeCreate {
	_c.mutation.SetChargeTs(v)
	return _c
}

// SetAlarm1 sets the "alarm1" field.
func (_c *ValueChargeCreate) SetAlarm1(v int) *ValueChargeCreate {
	_c.mutation.SetAlarm1(v)
	return _c
}

// SetNillableAlarm1 sets the "alarm1" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableAlarm1(v *int) *ValueChargeCreate {
	if v != nil {
		_c.SetAlarm1(*v)
	}
	return _c
}

// SetAlarm2 sets the "alarm2" field.
func (_c *ValueChargeCreate) SetAlarm2(v int) *ValueChargeCreate {
	_c.mutation.SetAlarm2(v)
	return _c
}

// SetNillableAlarm2 sets the "alarm2" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableAlarm2(v *int) *ValueChargeCreate {
	if v != nil {
		_c.SetAlarm2(*v)
	}
	return _c
}

// SetAlarm3 sets the "alarm3" field.
func (_c *ValueChargeCreate) SetAlarm3(v int) *ValueChargeCreate {
	_c.mutation.SetAlarm3(v)
	return _c
}

// SetNillableAlarm3 sets the "alarm3" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableAlarm3(v *int) *ValueChargeCreate {
	if v != nil {
		_c.SetAlarm3(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ValueChargeCreate) SetStatus(v int) *ValueChargeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableStatus(v *int) *ValueChargeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMemo sets the "memo" field.
func (_c *ValueChargeCreate) SetMemo(v string) *ValueChargeCreate {
	_c.mutation.SetMemo(v)
	return _c
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableMemo(v *string) *ValueChargeCreate {
	if v != nil {
		_c.SetMemo(*v)
	}
	return _c
}

// SetIsDel sets the "is_del" field.
func (_c *ValueChargeCreate) SetIsDel(v int) *ValueChargeCreate {
	_c.mutation.SetIsDel(v)
	return _c
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableIsDel(v *int) *ValueChargeCreate {
	if v != nil {
		_c.SetIsDel(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ValueChargeCreate) SetID(v string) *ValueChargeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ValueChargeCreate) SetNillableID(v *string) *ValueChargeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ValueChargeMutation object of the builder.
func (_c *ValueChargeCreate) Mutation() *ValueChargeMutation {
	return _c.mutation
}

// Save creates the ValueCharge in the database.
func (_c *ValueChargeCreate) Save(ctx context.Context) (*ValueCharge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ValueChargeCreate) SaveX(ctx context.Context) *ValueCharge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ValueChargeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ValueChargeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ValueChargeCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := valuecharge.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := valuecharge.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Top(); !ok {
		v := valuecharge.DefaultTop
		_c.mutation.SetTop(v)
	}
	if _, ok := _c.mutation.Stock(); !ok {
		v := valuecharge.DefaultStock
		_c.mutation.SetStock(v)
	}
	if _, ok := _c.mutation.Incr(); !ok {
		v := valuecharge.DefaultIncr
		_c.mutation.SetIncr(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := valuecharge.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		v := valuecharge.DefaultUnitPrice
		_c.mutation.SetUnitPrice(v)
	}
	if _, ok := _c.mutation.Alarm1(); !ok {
		v := valuecharge.DefaultAlarm1
		_c.mutation.SetAlarm1(v)
	}
	if _, ok := _c.mutation.Alarm2(); !ok {
		v := valuecharge.DefaultAlarm2
		_c.mutation.SetAlarm2(v)
	}
	if _, ok := _c.mutation.Alarm3(); !ok {
		v := valuecharge.DefaultAlarm3
		_c.mutation.SetAlarm3(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := valuecharge.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsDel(); !ok {
		v := valuecharge.DefaultIsDel
		_c.mutation.SetIsDel(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := valuecharge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ValueChargeCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "ValueCharge.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "ValueCharge.update_time"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ValueCharge.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := valuecharge.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ValueCharge.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceCode(); !ok {
		return &ValidationError{Name: "device_code", err: errors.New(`ent: missing required field "ValueCharge.device_code"`)}
	}
	if v, ok := _c.mutation.DeviceCode(); ok {
		if err := valuecharge.DeviceCodeValidator(v); err != nil {
			return &ValidationError{Name: "device_code", err: fmt.Errorf(`ent: validator failed for field "ValueCharge.device_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceType(); !ok {
		return &ValidationError{Name: "device_type", err: errors.New(`ent: missing required field "ValueCharge.device_type"`)}
	}
	if v, ok := _c.mutation.DeviceType(); ok {
		if err := valuecharge.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "ValueCharge.device_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PosCode(); !ok {
		return &ValidationError{Name: "pos_code", err: errors.New(`ent: missing required field "ValueCharge.pos_code"`)}
	}
	if v, ok := _c.mutation.PosCode(); ok {
		if err := valuecharge.PosCodeValidator(v); err != nil {
			return &ValidationError{Name: "pos_code", err: fmt.Errorf(`ent: validator failed for field "ValueCharge.pos_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Project(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required field "ValueCharge.project"`)}
	}
	if v, ok := _c.mutation.Project(); ok {
		if err := valuecharge.ProjectValidator(v); err != nil {
			return &ValidationError{Name: "project", err: fmt.Errorf(`ent: validator failed for field "ValueCharge.project": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Top(); !ok {
		return &ValidationError{Name: "top", err: errors.New(`ent: missing required field "ValueCharge.top"`)}
	}
	if _, ok := _c.mutation.Stock(); !ok {
		return &ValidationError{Name: "stock", err: errors.New(`ent: missing required field "ValueCharge.stock"`)}
	}
	if _, ok := _c.mutation.Incr(); !ok {
		return &ValidationError{Name: "incr", err: errors.New(`ent: missing required field "ValueCharge.incr"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ValueCharge.amount"`)}
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "ValueCharge.unit_price"`)}
	}
	if _, ok := _c.mutation.ChargeTime(); !ok {
		return &ValidationError{Name: "charge_time", err: errors.New(`ent: missing required field "ValueCharge.charge_time"`)}
	}
	if _, ok := _c.mutation.ChargeTs(); !ok {
		return &ValidationError{Name: "charge_ts", err: errors.New(`ent: missing required field "ValueCharge.charge_ts"`)}
	}
	if v, ok := _c.mutation.ChargeTs(); ok {
		if err := valuecharge.ChargeTsValidator(v); err != nil {
			return &ValidationError{Name: "charge_ts", err: fmt.Errorf(`ent: validator failed for field "ValueCharge.charge_ts": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Alarm1(); !ok {
		return &ValidationError{Name: "alarm1", err: errors.New(`ent: missing required field "ValueCharge.alarm1"`)}
	}
	if _, ok := _c.mutation.Alarm2(); !ok {
		return &ValidationError{Name: "alarm2", err: errors.New(`ent: missing required field "ValueCharge.alarm2"`)}
	}
	if _, ok := _c.mutation.Alarm3(); !ok {
		return &ValidationError{Name: "alarm3", err: errors.New(`ent: missing required field "ValueCharge.alarm3"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ValueCharge.status"`)}
	}
	if _, ok := _c.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "ValueCharge.is_del"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := valuecharge.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ValueCharge.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ValueChargeCreate) sqlSave(ctx context.Context) (*ValueCharge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ValueCharge.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ValueChargeCreate) createSpec() (*ValueCharge, *sqlgraph.CreateSpec) {
	var (
		_node = &ValueCharge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(valuecharge.Table, sqlgraph.NewFieldSpec(valuecharge.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(valuecharge.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(valuecharge.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(valuecharge.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.DeviceCode(); ok {
		_spec.SetField(valuecharge.FieldDeviceCode, field.TypeString, value)
		_node.DeviceCode = value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(valuecharge.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = value
	}
	if value, ok := _c.mutation.PosCode(); ok {
		_spec.SetField(valuecharge.FieldPosCode, field.TypeString, value)
		_node.PosCode = value
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(valuecharge.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(valuecharge.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.Top(); ok {
		_spec.SetField(valuecharge.FieldTop, field.TypeInt64, value)
		_node.Top = value
	}
	if value, ok := _c.mutation.Stock(); ok {
		_spec.SetField(valuecharge.FieldStock, field.TypeInt64, value)
		_node.Stock = value
	}
	if value, ok := _c.mutation.Incr(); ok {
		_spec.SetField(valuecharge.FieldIncr, field.TypeInt64, value)
		_node.Incr = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(valuecharge.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.UnitPrice(); ok {
		_spec.SetField(valuecharge.FieldUnitPrice, field.TypeInt64, value)
		_node.UnitPrice = value
	}
	if value, ok := _c.mutation.ChargeTime(); ok {
		_spec.SetField(valuecharge.FieldChargeTime, field.TypeTime, value)
		_node.ChargeTime = value
	}
	if value, ok := _c.mutation.ChargeTs(); ok {
		_spec.SetField(valuecharge.FieldChargeTs, field.TypeString, value)
		_node.ChargeTs = value
	}
	if value, ok := _c.mutation.Alarm1(); ok {
		_spec.SetField(valuecharge.FieldAlarm1, field.TypeInt, value)
		_node.Alarm1 = value
	}
	if value, ok := _c.mutation.Alarm2(); ok {
		_spec.SetField(valuecharge.FieldAlarm2, field.TypeInt, value)
		_node.Alarm2 = value
	}
	if value, ok := _c.mutation.Alarm3(); ok {
		_spec.SetField(valuecharge.FieldAlarm3, field.TypeInt, value)
		_node.Alarm3 = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(valuecharge.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Memo(); ok {
		_spec.SetField(valuecharge.FieldMemo, field.TypeString, value)
		_node.Memo = value
	}
	if value, ok := _c.mutation.IsDel(); ok {
		_spec.SetField(valuecharge.FieldIsDel, field.TypeInt, value)
		_node.IsDel = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ValueCharge.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ValueChargeUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *ValueChargeCreate) OnConflict(opts ...sql.ConflictOption) *ValueChargeUpsertOne {
	_c.conflict = opts
	return &ValueChargeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ValueCharge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ValueChargeCreate) OnConflictColumns(columns ...string) *ValueChargeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ValueChargeUpsertOne{
		create: _c,
	}
}

type (
	// ValueChargeUpsertOne is the builder for "upsert"-ing
	//  one ValueCharge node.
	ValueChargeUpsertOne struct {
		create *ValueChargeCreate
	}

	// ValueChargeUpsert is the "OnConflict" setter.
	ValueChargeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *ValueChargeUpsert) SetUpdateTime(v time.Time) *ValueChargeUpsert {
	u.Set(valuecharge.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ValueChargeUpsert) UpdateUpdateTime() *ValueChargeUpsert {
	u.SetExcluded(valuecharge.FieldUpdateTime)
	return u
}

// SetAlarm1 sets the "alarm1" field.
func (u *ValueChargeUpsert) SetAlarm1(v int) *ValueChargeUpsert {
	u.Set(valuecharge.FieldAlarm1, v)
	return u
}

// UpdateAlarm1 sets the "alarm1" field to the value that was provided on create.
func (u *ValueChargeUpsert) UpdateAlarm1() *ValueChargeUpsert {
	u.SetExcluded(valuecharge.FieldAlarm1)
	return u
}

// AddAlarm1 adds v to the "alarm1" field.
func (u *ValueChargeUpsert) AddAlarm1(v int) *ValueChargeUpsert {
	u.Add(valuecharge.FieldAlarm1, v)
	return u
}

// SetAlarm2 sets the "alarm2" field.
func (u *ValueChargeUpsert) SetAlarm2(v int) *ValueChargeUpsert {
	u.Set(valuecharge.FieldAlarm2, v)
	return u
}

// UpdateAlarm2 sets the "alarm2" field to the value that was provided on create.
func (u *ValueChargeUpsert) UpdateAlarm2() *ValueChargeUpsert {
	u.SetExcluded(valuecharge.FieldAlarm2)
	return u
}

// AddAlarm2 adds v to the "alarm2" field.
func (u *ValueChargeUpsert) AddAlarm2(v int) *ValueChargeUpsert {
	u.Add(valuecharge.FieldAlarm2, v)
	return u
}

// SetAlarm3 sets the "alarm3" field.
func (u *ValueChargeUpsert) SetAlarm3(v int) *ValueChargeUpsert {
	u.Set(valuecharge.FieldAlarm3, v)
	return u
}

// UpdateAlarm3 sets the "alarm3" field to the value that was provided on create.
func (u *ValueChargeUpsert) UpdateAlarm3() *ValueChargeUpsert {
	u.SetExcluded(valuecharge.FieldAlarm3)
	return u
}

// AddAlarm3 adds v to the "alarm3" field.
func (u *ValueChargeUpsert) AddAlarm3(v int) *ValueChargeUpsert {
	u.Add(valuecharge.FieldAlarm3, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ValueChargeUpsert) SetStatus(v int) *ValueChargeUpsert {
	u.Set(valuecharge.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ValueChargeUpsert) UpdateStatus() *ValueChargeUpsert {
	u.SetExcluded(valuecharge.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *ValueChargeUpsert) AddStatus(v int) *ValueChargeUpsert {
	u.Add(valuecharge.FieldStatus, v)
	return u
}

// SetMemo sets the "memo" field.
func (u *ValueChargeUpsert) SetMemo(v string) *ValueChargeUpsert {
	u.Set(valuecharge.FieldMemo, v)
	return u
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *ValueChargeUpsert) UpdateMemo() *ValueChargeUpsert {
	u.SetExcluded(valuecharge.FieldMemo)
	return u
}

// ClearMemo clears the value of the "memo" field.
func (u *ValueChargeUpsert) ClearMemo() *ValueChargeUpsert {
	u.SetNull(valuecharge.FieldMemo)
	return u
}

// SetIsDel sets the "is_del" field.
func (u *ValueChargeUpsert) SetIsDel(v int) *ValueChargeUpsert {
	u.Set(valuecharge.FieldIsDel, v)
	return u
}

// UpdateIsDel sets the "is_del" field to the value that was provided on create.
func (u *ValueChargeUpsert) UpdateIsDel() *ValueChargeUpsert {
	u.SetExcluded(valuecharge.FieldIsDel)
	return u
}

// AddIsDel adds v to the "is_del" field.
func (u *ValueChargeUpsert) AddIsDel(v int) *ValueChargeUpsert {
	u.Add(valuecharge.FieldIsDel, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ValueCharge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(valuecharge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ValueChargeUpsertOne) UpdateNewValues() *ValueChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(valuecharge.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(valuecharge.FieldCreateTime)
		}
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(valuecharge.FieldCode)
		}
		if _, exists := u.create.mutation.DeviceCode(); exists {
			s.SetIgnore(valuecharge.FieldDeviceCode)
		}
		if _, exists := u.create.mutation.DeviceType(); exists {
			s.SetIgnore(valuecharge.FieldDeviceType)
		}
		if _, exists := u.create.mutation.PosCode(); exists {
			s.SetIgnore(valuecharge.FieldPosCode)
		}
		if _, exists := u.create.mutation.Project(); exists {
			s.SetIgnore(valuecharge.FieldProject)
		}
		if _, exists := u.create.mutation.Owner(); exists {
			s.SetIgnore(valuecharge.FieldOwner)
		}
		if _, exists := u.create.mutation.Top(); exists {
			s.SetIgnore(valuecharge.FieldTop)
		}
		if _, exists := u.create.mutation.Stock(); exists {
			s.SetIgnore(valuecharge.FieldStock)
		}
		if _, exists := u.create.mutation.Incr(); exists {
			s.SetIgnore(valuecharge.FieldIncr)
		}
		if _, exists := u.create.mutation.Amount(); exists {
			s.SetIgnore(valuecharge.FieldAmount)
		}
		if _, exists := u.create.mutation.UnitPrice(); exists {
			s.SetIgnore(valuecharge.FieldUnitPrice)
		}
		if _, exists := u.create.mutation.ChargeTime(); exists {
			s.SetIgnore(valuecharge.FieldChargeTime)
		}
		if _, exists := u.create.mutation.ChargeTs(); exists {
			s.SetIgnore(valuecharge.FieldChargeTs)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ValueCharge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ValueChargeUpsertOne) Ignore() *ValueChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ValueChargeUpsertOne) DoNothing() *ValueChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ValueChargeCreate.OnConflict
// documentation for more info.
func (u *ValueChargeUpsertOne) Update(set func(*ValueChargeUpsert)) *ValueChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ValueChargeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ValueChargeUpsertOne) SetUpdateTime(v time.Time) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ValueChargeUpsertOne) UpdateUpdateTime() *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetAlarm1 sets the "alarm1" field.
func (u *ValueChargeUpsertOne) SetAlarm1(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetAlarm1(v)
	})
}

// AddAlarm1 adds v to the "alarm1" field.
func (u *ValueChargeUpsertOne) AddAlarm1(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddAlarm1(v)
	})
}

// UpdateAlarm1 sets the "alarm1" field to the value that was provided on create.
func (u *ValueChargeUpsertOne) UpdateAlarm1() *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateAlarm1()
	})
}

// SetAlarm2 sets the "alarm2" field.
func (u *ValueChargeUpsertOne) SetAlarm2(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetAlarm2(v)
	})
}

// AddAlarm2 adds v to the "alarm2" field.
func (u *ValueChargeUpsertOne) AddAlarm2(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddAlarm2(v)
	})
}

// UpdateAlarm2 sets the "alarm2" field to the value that was provided on create.
func (u *ValueChargeUpsertOne) UpdateAlarm2() *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateAlarm2()
	})
}

// SetAlarm3 sets the "alarm3" field.
func (u *ValueChargeUpsertOne) SetAlarm3(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetAlarm3(v)
	})
}

// AddAlarm3 adds v to the "alarm3" field.
func (u *ValueChargeUpsertOne) AddAlarm3(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddAlarm3(v)
	})
}

// UpdateAlarm3 sets the "alarm3" field to the value that was provided on create.
func (u *ValueChargeUpsertOne) UpdateAlarm3() *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateAlarm3()
	})
}

// SetStatus sets the "status" field.
func (u *ValueChargeUpsertOne) SetStatus(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *ValueChargeUpsertOne) AddStatus(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ValueChargeUpsertOne) UpdateStatus() *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateStatus()
	})
}

// SetMemo sets the "memo" field.
func (u *ValueChargeUpsertOne) SetMemo(v string) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *ValueChargeUpsertOne) UpdateMemo() *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *ValueChargeUpsertOne) ClearMemo() *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.ClearMemo()
	})
}

// SetIsDel sets the "is_del" field.
func (u *ValueChargeUpsertOne) SetIsDel(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetIsDel(v)
	})
}

// AddIsDel adds v to the "is_del" field.
func (u *ValueChargeUpsertOne) AddIsDel(v int) *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddIsDel(v)
	})
}

// UpdateIsDel sets the "is_del" field to the value that was provided on create.
func (u *ValueChargeUpsertOne) UpdateIsDel() *ValueChargeUpsertOne {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateIsDel()
	})
}

// Exec executes the query.
func (u *ValueChargeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ValueChargeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ValueChargeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ValueChargeUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ValueChargeUpsertOne.ID is not supported by MySQL driver. Use ValueChargeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ValueChargeUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ValueChargeCreateBulk is the builder for creating many ValueCharge entities in bulk.
type ValueChargeCreateBulk struct {
	config
	err      error
	builders []*ValueChargeCreate
	conflict []sql.ConflictOption
}

// Save creates the ValueCharge entities in the database.
func (_c *ValueChargeCreateBulk) Save(ctx context.Context) ([]*ValueCharge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ValueCharge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ValueChargeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ValueChargeCreateBulk) SaveX(ctx context.Context) []*ValueCharge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ValueChargeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ValueChargeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ValueCharge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ValueChargeUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *ValueChargeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ValueChargeUpsertBulk {
	_c.conflict = opts
	return &ValueChargeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ValueCharge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ValueChargeCreateBulk) OnConflictColumns(columns ...string) *ValueChargeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ValueChargeUpsertBulk{
		create: _c,
	}
}

// ValueChargeUpsertBulk is the builder for "upsert"-ing
// a bulk of ValueCharge nodes.
type ValueChargeUpsertBulk struct {
	create *ValueChargeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ValueCharge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(valuecharge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ValueChargeUpsertBulk) UpdateNewValues() *ValueChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(valuecharge.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(valuecharge.FieldCreateTime)
			}
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(valuecharge.FieldCode)
			}
			if _, exists := b.mutation.DeviceCode(); exists {
				s.SetIgnore(valuecharge.FieldDeviceCode)
			}
			if _, exists := b.mutation.DeviceType(); exists {
				s.SetIgnore(valuecharge.FieldDeviceType)
			}
			if _, exists := b.mutation.PosCode(); exists {
				s.SetIgnore(valuecharge.FieldPosCode)
			}
			if _, exists := b.mutation.Project(); exists {
				s.SetIgnore(valuecharge.FieldProject)
			}
			if _, exists := b.mutation.Owner(); exists {
				s.SetIgnore(valuecharge.FieldOwner)
			}
			if _, exists := b.mutation.Top(); exists {
				s.SetIgnore(valuecharge.FieldTop)
			}
			if _, exists := b.mutation.Stock(); exists {
				s.SetIgnore(valuecharge.FieldStock)
			}
			if _, exists := b.mutation.Incr(); exists {
				s.SetIgnore(valuecharge.FieldIncr)
			}
			if _, exists := b.mutation.Amount(); exists {
				s.SetIgnore(valuecharge.FieldAmount)
			}
			if _, exists := b.mutation.UnitPrice(); exists {
				s.SetIgnore(valuecharge.FieldUnitPrice)
			}
			if _, exists := b.mutation.ChargeTime(); exists {
				s.SetIgnore(valuecharge.FieldChargeTime)
			}
			if _, exists := b.mutation.ChargeTs(); exists {
				s.SetIgnore(valuecharge.FieldChargeTs)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ValueCharge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ValueChargeUpsertBulk) Ignore() *ValueChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ValueChargeUpsertBulk) DoNothing() *ValueChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ValueChargeCreateBulk.OnConflict
// documentation for more info.
func (u *ValueChargeUpsertBulk) Update(set func(*ValueChargeUpsert)) *ValueChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ValueChargeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ValueChargeUpsertBulk) SetUpdateTime(v time.Time) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ValueChargeUpsertBulk) UpdateUpdateTime() *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetAlarm1 sets the "alarm1" field.
func (u *ValueChargeUpsertBulk) SetAlarm1(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetAlarm1(v)
	})
}

// AddAlarm1 adds v to the "alarm1" field.
func (u *ValueChargeUpsertBulk) AddAlarm1(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddAlarm1(v)
	})
}

// UpdateAlarm1 sets the "alarm1" field to the value that was provided on create.
func (u *ValueChargeUpsertBulk) UpdateAlarm1() *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateAlarm1()
	})
}

// SetAlarm2 sets the "alarm2" field.
func (u *ValueChargeUpsertBulk) SetAlarm2(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetAlarm2(v)
	})
}

// AddAlarm2 adds v to the "alarm2" field.
func (u *ValueChargeUpsertBulk) AddAlarm2(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddAlarm2(v)
	})
}

// UpdateAlarm2 sets the "alarm2" field to the value that was provided on create.
func (u *ValueChargeUpsertBulk) UpdateAlarm2() *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateAlarm2()
	})
}

// SetAlarm3 sets the "alarm3" field.
func (u *ValueChargeUpsertBulk) SetAlarm3(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetAlarm3(v)
	})
}

// AddAlarm3 adds v to the "alarm3" field.
func (u *ValueChargeUpsertBulk) AddAlarm3(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddAlarm3(v)
	})
}

// UpdateAlarm3 sets the "alarm3" field to the value that was provided on create.
func (u *ValueChargeUpsertBulk) UpdateAlarm3() *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateAlarm3()
	})
}

// SetStatus sets the "status" field.
func (u *ValueChargeUpsertBulk) SetStatus(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *ValueChargeUpsertBulk) AddStatus(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ValueChargeUpsertBulk) UpdateStatus() *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateStatus()
	})
}

// SetMemo sets the "memo" field.
func (u *ValueChargeUpsertBulk) SetMemo(v string) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *ValueChargeUpsertBulk) UpdateMemo() *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *ValueChargeUpsertBulk) ClearMemo() *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.ClearMemo()
	})
}

// SetIsDel sets the "is_del" field.
func (u *ValueChargeUpsertBulk) SetIsDel(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.SetIsDel(v)
	})
}

// AddIsDel adds v to the "is_del" field.
func (u *ValueChargeUpsertBulk) AddIsDel(v int) *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.AddIsDel(v)
	})
}

// UpdateIsDel sets the "is_del" field to the value that was provided on create.
func (u *ValueChargeUpsertBulk) UpdateIsDel() *ValueChargeUpsertBulk {
	return u.Update(func(s *ValueChargeUpsert) {
		s.UpdateIsDel()
	})
}

// Exec executes the query.
func (u *ValueChargeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ValueChargeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ValueChargeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ValueChargeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
