// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/h2o/chrgg/orm/ent/predicate"
	"github.com/twiglab/h2o/chrgg/orm/ent/valuecharge"
)

// ValueChargeUpdate is the builder for updating ValueCharge entities.
type ValueChargeUpdate struct {
	config
	hooks    []Hook
	mutation *ValueChargeMutation
}

// Where appends a list predicates to the ValueChargeUpdate builder.
func (_u *ValueChargeUpdate) Where(ps ...predicate.ValueCharge) *ValueChargeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ValueChargeUpdate) SetUpdateTime(v time.Time) *ValueChargeUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetAlarm1 sets the "alarm1" field.
func (_u *ValueChargeUpdate) SetAlarm1(v int) *ValueChargeUpdate {
	_u.mutation.ResetAlarm1()
	_u.mutation.SetAlarm1(v)
	return _u
}

// SetNillableAlarm1 sets the "alarm1" field if the given value is not nil.
func (_u *ValueChargeUpdate) SetNillableAlarm1(v *int) *ValueChargeUpdate {
	if v != nil {
		_u.SetAlarm1(*v)
	}
	return _u
}

// AddAlarm1 adds value to the "alarm1" field.
func (_u *ValueChargeUpdate) AddAlarm1(v int) *ValueChargeUpdate {
	_u.mutation.AddAlarm1(v)
	return _u
}

// SetAlarm2 sets the "alarm2" field.
func (_u *ValueChargeUpdate) SetAlarm2(v int) *ValueChargeUpdate {
	_u.mutation.ResetAlarm2()
	_u.mutation.SetAlarm2(v)
	return _u
}

// SetNillableAlarm2 sets the "alarm2" field if the given value is not nil.
func (_u *ValueChargeUpdate) SetNillableAlarm2(v *int) *ValueChargeUpdate {
	if v != nil {
		_u.SetAlarm2(*v)
	}
	return _u
}

// AddAlarm2 adds value to the "alarm2" field.
func (_u *ValueChargeUpdate) AddAlarm2(v int) *ValueChargeUpdate {
	_u.mutation.AddAlarm2(v)
	return _u
}

// SetAlarm3 sets the "alarm3" field.
func (_u *ValueChargeUpdate) SetAlarm3(v int) *ValueChargeUpdate {
	_u.mutation.ResetAlarm3()
	_u.mutation.SetAlarm3(v)
	return _u
}

// SetNillableAlarm3 sets the "alarm3" field if the given value is not nil.
func (_u *ValueChargeUpdate) SetNillableAlarm3(v *int) *ValueChargeUpdate {
	if v != nil {
		_u.SetAlarm3(*v)
	}
	return _u
}

// AddAlarm3 adds value to the "alarm3" field.
func (_u *ValueChargeUpdate) AddAlarm3(v int) *ValueChargeUpdate {
	_u.mutation.AddAlarm3(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ValueChargeUpdate) SetStatus(v int) *ValueChargeUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ValueChargeUpdate) SetNillableStatus(v *int) *ValueChargeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ValueChargeUpdate) AddStatus(v int) *ValueChargeUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetMemo sets the "memo" field.
func (_u *ValueChargeUpdate) SetMemo(v string) *ValueChargeUpdate {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *ValueChargeUpdate) SetNillableMemo(v *string) *ValueChargeUpdate {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *ValueChargeUpdate) ClearMemo() *ValueChargeUpdate {
	_u.mutation.ClearMemo()
	return _u
}

// SetIsDel sets the "is_del" field.
func (_u *ValueChargeUpdate) SetIsDel(v int) *ValueChargeUpdate {
	_u.mutation.ResetIsDel()
	_u.mutation.SetIsDel(v)
	return _u
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_u *ValueChargeUpdate) SetNillableIsDel(v *int) *ValueChargeUpdate {
	if v != nil {
		_u.SetIsDel(*v)
	}
	return _u
}

// AddIsDel adds value to the "is_del" field.
func (_u *ValueChargeUpdate) AddIsDel(v int) *ValueChargeUpdate {
	_u.mutation.AddIsDel(v)
	return _u
}

// Mutation returns the ValueChargeMutation object of the builder.
func (_u *ValueChargeUpdate) Mutation() *ValueChargeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ValueChargeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ValueChargeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ValueChargeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ValueChargeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ValueChargeUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := valuecharge.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *ValueChargeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(valuecharge.Table, valuecharge.Columns, sqlgraph.NewFieldSpec(valuecharge.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(valuecharge.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		_spec.ClearField(valuecharge.FieldOwner, field.TypeString)
	}
	if value, ok := _u.mutation.Alarm1(); ok {
		_spec.SetField(valuecharge.FieldAlarm1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAlarm1(); ok {
		_spec.AddField(valuecharge.FieldAlarm1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Alarm2(); ok {
		_spec.SetField(valuecharge.FieldAlarm2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAlarm2(); ok {
		_spec.AddField(valuecharge.FieldAlarm2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Alarm3(); ok {
		_spec.SetField(valuecharge.FieldAlarm3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAlarm3(); ok {
		_spec.AddField(valuecharge.FieldAlarm3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(valuecharge.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(valuecharge.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(valuecharge.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(valuecharge.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.IsDel(); ok {
		_spec.SetField(valuecharge.FieldIsDel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIsDel(); ok {
		_spec.AddField(valuecharge.FieldIsDel, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{valuecharge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ValueChargeUpdateOne is the builder for updating a single ValueCharge entity.
type ValueChargeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ValueChargeMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ValueChargeUpdateOne) SetUpdateTime(v time.Time) *ValueChargeUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetAlarm1 sets the "alarm1" field.
func (_u *ValueChargeUpdateOne) SetAlarm1(v int) *ValueChargeUpdateOne {
	_u.mutation.ResetAlarm1()
	_u.mutation.SetAlarm1(v)
	return _u
}

// SetNillableAlarm1 sets the "alarm1" field if the given value is not nil.
func (_u *ValueChargeUpdateOne) SetNillableAlarm1(v *int) *ValueChargeUpdateOne {
	if v != nil {
		_u.SetAlarm1(*v)
	}
	return _u
}

// AddAlarm1 adds value to the "alarm1" field.
func (_u *ValueChargeUpdateOne) AddAlarm1(v int) *ValueChargeUpdateOne {
	_u.mutation.AddAlarm1(v)
	return _u
}

// SetAlarm2 sets the "alarm2" field.
func (_u *ValueChargeUpdateOne) SetAlarm2(v int) *ValueChargeUpdateOne {
	_u.mutation.ResetAlarm2()
	_u.mutation.SetAlarm2(v)
	return _u
}

// SetNillableAlarm2 sets the "alarm2" field if the given value is not nil.
func (_u *ValueChargeUpdateOne) SetNillableAlarm2(v *int) *ValueChargeUpdateOne {
	if v != nil {
		_u.SetAlarm2(*v)
	}
	return _u
}

// AddAlarm2 adds value to the "alarm2" field.
func (_u *ValueChargeUpdateOne) AddAlarm2(v int) *ValueChargeUpdateOne {
	_u.mutation.AddAlarm2(v)
	return _u
}

// SetAlarm3 sets the "alarm3" field.
func (_u *ValueChargeUpdateOne) SetAlarm3(v int) *ValueChargeUpdateOne {
	_u.mutation.ResetAlarm3()
	_u.mutation.SetAlarm3(v)
	return _u
}

// SetNillableAlarm3 sets the "alarm3" field if the given value is not nil.
func (_u *ValueChargeUpdateOne) SetNillableAlarm3(v *int) *ValueChargeUpdateOne {
	if v != nil {
		_u.SetAlarm3(*v)
	}
	return _u
}

// AddAlarm3 adds value to the "alarm3" field.
func (_u *ValueChargeUpdateOne) AddAlarm3(v int) *ValueChargeUpdateOne {
	_u.mutation.AddAlarm3(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ValueChargeUpdateOne) SetStatus(v int) *ValueChargeUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ValueChargeUpdateOne) SetNillableStatus(v *int) *ValueChargeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ValueChargeUpdateOne) AddStatus(v int) *ValueChargeUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetMemo sets the "memo" field.
func (_u *ValueChargeUpdateOne) SetMemo(v string) *ValueChargeUpdateOne {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *ValueChargeUpdateOne) SetNillableMemo(v *string) *ValueChargeUpdateOne {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *ValueChargeUpdateOne) ClearMemo() *ValueChargeUpdateOne {
	_u.mutation.ClearMemo()
	return _u
}

// SetIsDel sets the "is_del" field.
func (_u *ValueChargeUpdateOne) SetIsDel(v int) *ValueChargeUpdateOne {
	_u.mutation.ResetIsDel()
	_u.mutation.SetIsDel(v)
	return _u
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_u *ValueChargeUpdateOne) SetNillableIsDel(v *int) *ValueChargeUpdateOne {
	if v != nil {
		_u.SetIsDel(*v)
	}
	return _u
}

// AddIsDel adds value to the "is_del" field.
func (_u *ValueChargeUpdateOne) AddIsDel(v int) *ValueChargeUpdateOne {
	_u.mutation.AddIsDel(v)
	return _u
}

// Mutation returns the ValueChargeMutation object of the builder.
func (_u *ValueChargeUpdateOne) Mutation() *ValueChargeMutation {
	return _u.mutation
}

// Where appends a list predicates to the ValueChargeUpdate builder.
func (_u *ValueChargeUpdateOne) Where(ps ...predicate.ValueCharge) *ValueChargeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ValueChargeUpdateOne) Select(field string, fields ...string) *ValueChargeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ValueCharge entity.
func (_u *ValueChargeUpdateOne) Save(ctx context.Context) (*ValueCharge, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ValueChargeUpdateOne) SaveX(ctx context.Context) *ValueCharge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ValueChargeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ValueChargeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ValueChargeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := valuecharge.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *ValueChargeUpdateOne) sqlSave(ctx context.Context) (_node *ValueCharge, err error) {
	_spec := sqlgraph.NewUpdateSpec(valuecharge.Table, valuecharge.Columns, sqlgraph.NewFieldSpec(valuecharge.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ValueCharge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, valuecharge.FieldID)
		for _, f := range fields {
			if !valuecharge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != valuecharge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(valuecharge.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		_spec.ClearField(valuecharge.FieldOwner, field.TypeString)
	}
	if value, ok := _u.mutation.Alarm1(); ok {
		_spec.SetField(valuecharge.FieldAlarm1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAlarm1(); ok {
		_spec.AddField(valuecharge.FieldAlarm1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Alarm2(); ok {
		_spec.SetField(valuecharge.FieldAlarm2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAlarm2(); ok {
		_spec.AddField(valuecharge.FieldAlarm2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Alarm3(); ok {
		_spec.SetField(valuecharge.FieldAlarm3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAlarm3(); ok {
		_spec.AddField(valuecharge.FieldAlarm3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(valuecharge.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(valuecharge.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(valuecharge.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(valuecharge.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.IsDel(); ok {
		_spec.SetField(valuecharge.FieldIsDel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIsDel(); ok {
		_spec.AddField(valuecharge.FieldIsDel, field.TypeInt, value)
	}
	_node = &ValueCharge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{valuecharge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
