// Code generated by ent, DO NOT EDIT.

package viewrecord

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the viewrecord type in the database.
	Label = "view_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeviceCode holds the string denoting the device_code field in the database.
	FieldDeviceCode = "device_code"
	// FieldDeviceType holds the string denoting the device_type field in the database.
	FieldDeviceType = "device_type"
	// FieldDataValue holds the string denoting the data_value field in the database.
	FieldDataValue = "data_value"
	// FieldDataTime holds the string denoting the data_time field in the database.
	FieldDataTime = "data_time"
	// FieldDataTs holds the string denoting the data_ts field in the database.
	FieldDataTs = "data_ts"
	// FieldDeviceSn holds the string denoting the device_sn field in the database.
	FieldDeviceSn = "device_sn"
	// FieldDeviceName holds the string denoting the device_name field in the database.
	FieldDeviceName = "device_name"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// FieldPosCode holds the string denoting the pos_code field in the database.
	FieldPosCode = "pos_code"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMemo holds the string denoting the memo field in the database.
	FieldMemo = "memo"
	// Table holds the table name of the viewrecord in the database.
	Table = "view_record"
)

// Columns holds all SQL columns for viewrecord fields.
var Columns = []string{
	FieldID,
	FieldDeviceCode,
	FieldDeviceType,
	FieldDataValue,
	FieldDataTime,
	FieldDataTs,
	FieldDeviceSn,
	FieldDeviceName,
	FieldRate,
	FieldProject,
	FieldPosCode,
	FieldStatus,
	FieldMemo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ViewRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeviceCode orders the results by the device_code field.
func ByDeviceCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceCode, opts...).ToFunc()
}

// ByDeviceType orders the results by the device_type field.
func ByDeviceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceType, opts...).ToFunc()
}

// ByDataValue orders the results by the data_value field.
func ByDataValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataValue, opts...).ToFunc()
}

// ByDataTime orders the results by the data_time field.
func ByDataTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataTime, opts...).ToFunc()
}

// ByDataTs orders the results by the data_ts field.
func ByDataTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataTs, opts...).ToFunc()
}

// ByDeviceSn orders the results by the device_sn field.
func ByDeviceSn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceSn, opts...).ToFunc()
}

// ByDeviceName orders the results by the device_name field.
func ByDeviceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceName, opts...).ToFunc()
}

// ByRate orders the results by the rate field.
func ByRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRate, opts...).ToFunc()
}

// ByProject orders the results by the project field.
func ByProject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProject, opts...).ToFunc()
}

// ByPosCode orders the results by the pos_code field.
func ByPosCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosCode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMemo orders the results by the memo field.
func ByMemo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemo, opts...).ToFunc()
}
